// GENERATED by engine/tools/gen-contract.mjs from contract/tables.json — DO NOT EDIT.
// Single source for every shared cross-layer value + the vision-reading
// schema (embedded from contract/garment-spec.schema.json $defs.visionReading
// so the browser validates without fetching the contract dir).

export const CONTRACT = {
  "version": "1.0.0",
  "draft": {
    "skirtLengthMM": {
      "mini": 450,
      "midi": 650,
      "maxi": 900
    },
    "gatherRatios": {
      "drawstring": 1.8,
      "shirred": 2,
      "smocked": 3
    },
    "euSizes": [
      "EU34",
      "EU36",
      "EU38",
      "EU40",
      "EU42",
      "EU44",
      "EU46",
      "EU48",
      "EU50",
      "EU52"
    ],
    "euSizeChart": {
      "EU34": [
        80,
        62,
        86,
        36,
        39.5,
        57,
        34
      ],
      "EU36": [
        84,
        66,
        90,
        36.5,
        40,
        57.5,
        34.5
      ],
      "EU38": [
        88,
        70,
        94,
        37,
        40.5,
        58,
        35
      ],
      "EU40": [
        92,
        74,
        98,
        37.5,
        41,
        58.5,
        36
      ],
      "EU42": [
        96,
        78,
        102,
        38,
        41.5,
        59,
        36.5
      ],
      "EU44": [
        100,
        82,
        106,
        38.5,
        42,
        59.5,
        37
      ],
      "EU46": [
        104,
        86,
        110,
        39,
        42,
        60,
        38
      ],
      "EU48": [
        110,
        92,
        116,
        40,
        42.5,
        60.5,
        39
      ],
      "EU50": [
        116,
        98,
        122,
        41,
        43,
        61,
        40
      ],
      "EU52": [
        122,
        104,
        128,
        42,
        43.5,
        61.5,
        41
      ]
    },
    "euSizeChartFields": [
      "bustCM",
      "waistCM",
      "hipCM",
      "shoulderCM",
      "backLengthCM",
      "armLengthCM",
      "neckCM"
    ]
  },
  "flat": {
    "unitPX": 5.6,
    "len": {
      "mini": 42,
      "knee": 58,
      "midi": 74
    },
    "size": {
      "_fields": [
        "neck",
        "shp",
        "strap",
        "bust",
        "emp",
        "ad"
      ],
      "EU34": {
        "neck": 6.6,
        "shp": 11.9,
        "strap": 6.8,
        "bust": 14.6,
        "emp": 13.2,
        "ad": 19.6
      },
      "EU36": {
        "neck": 6.8,
        "shp": 12.2,
        "strap": 7.1,
        "bust": 15,
        "emp": 13.7,
        "ad": 20
      },
      "EU38": {
        "neck": 7,
        "shp": 12.6,
        "strap": 7.4,
        "bust": 15.5,
        "emp": 14.2,
        "ad": 20.6
      },
      "EU40": {
        "neck": 7.3,
        "shp": 13.1,
        "strap": 7.7,
        "bust": 16.2,
        "emp": 14.9,
        "ad": 21.2
      },
      "EU42": {
        "neck": 7.6,
        "shp": 13.6,
        "strap": 8,
        "bust": 17,
        "emp": 15.7,
        "ad": 21.8
      }
    }
  },
  "mappings": {
    "sleeveHeadToSleeveCap": {
      "plain": "plain",
      "gathered": "gathered",
      "puffed": "puffed",
      "puff": "puffed",
      "capped": "cap",
      "cap": "cap"
    },
    "nullEquivalence": {
      "sleeveStyle": "none"
    },
    "backDetailSplit": {
      "openBack": {
        "target": "backOpening",
        "value": "round"
      },
      "keyholeBack": {
        "target": "backOpening",
        "value": "keyhole"
      },
      "vBack": {
        "target": "backOpening",
        "value": "lowV"
      },
      "tieBack": {
        "target": "tieClosure",
        "value": "tieBack"
      },
      "lacedBack": {
        "target": "honest"
      },
      "buttonBack": {
        "target": "honest"
      }
    },
    "seenFlags": [
      "backDetailDrawn",
      "backOpeningDrawn",
      "bardotDrawn",
      "buttonRowDrawn",
      "capSleeveDrawn",
      "closureDrawn",
      "collarDrawn",
      "cuffDrawn",
      "exposedZipDrawn",
      "gatherDrawn",
      "hemShapeDrawn",
      "hemSlitDrawn",
      "peplumDrawn",
      "placketAsymDrawn",
      "pocketDrawn",
      "ruffledStrapsDrawn",
      "sleeveCapDrawn",
      "tieDrawn"
    ]
  }
};

export const VISION_SCHEMA = {
  "description": "What the vision layer is allowed to say about a photo. SEMANTIC ONLY. Unknown fields are rejected (additionalProperties:false); a value outside its enum is invalid. The bridge (web/js/vision-bridge.js) compiles this into draftSpec; the declared cross-layer translations live in contract/tables.json mappings.*.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "garment": {
      "enum": [
        "skirt",
        "dress",
        "top",
        "trousers",
        "other"
      ]
    },
    "neckline": {
      "enum": [
        "crew",
        "scoop",
        "vNeck",
        "square",
        "boat",
        "sweetheart",
        "halter",
        "cowl",
        "pussyBow",
        null
      ]
    },
    "sleeveStyle": {
      "enum": [
        "none",
        "straight",
        "balloon",
        null
      ]
    },
    "sleeveLength": {
      "enum": [
        "short",
        "elbow",
        "long",
        null
      ]
    },
    "skirtStyle": {
      "enum": [
        "aLine",
        "straight",
        "gathered",
        "halfCircle",
        "pleated",
        "gore",
        null
      ]
    },
    "length": {
      "enum": [
        "mini",
        "midi",
        "maxi",
        null
      ]
    },
    "topLength": {
      "enum": [
        "cropped",
        "hip",
        "tunic",
        null
      ]
    },
    "shaping": {
      "enum": [
        "princess",
        "dart",
        null
      ]
    },
    "waistline": {
      "enum": [
        "natural",
        "empire",
        null
      ]
    },
    "fabric": {
      "enum": [
        "woven",
        "knit",
        null
      ]
    },
    "hemRuffle": {
      "enum": [
        "none",
        "single",
        "tiered",
        null
      ]
    },
    "keyhole": {
      "type": [
        "boolean",
        "null"
      ]
    },
    "fabricName": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 60
    },
    "closure": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "buttons",
            "placket",
            "zipper",
            "ties",
            "lace-up",
            "hookEye",
            "none",
            null
          ]
        },
        "location": {
          "enum": [
            "centerFront",
            "centerBack",
            "sideSeam",
            "shoulder",
            "neck",
            "waist",
            null
          ]
        }
      }
    },
    "collar": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "stand",
            "shirt",
            "peterPan",
            "mandarin",
            "notched",
            "sailor",
            "other",
            null
          ]
        },
        "name": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 80
        }
      }
    },
    "straps": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "shoulder",
            "spaghetti",
            "wide",
            "halter",
            "ruffled",
            "oneShoulder",
            "offShoulder",
            null
          ]
        },
        "count": {
          "enum": [
            1,
            2,
            null
          ]
        }
      }
    },
    "cupSeams": {
      "type": [
        "boolean",
        "null"
      ]
    },
    "sleeveHead": {
      "enum": [
        "plain",
        "gathered",
        "puffed",
        "capped",
        null
      ]
    },
    "yoke": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "shoulderYoke",
            "shirring",
            "smocking",
            null
          ]
        },
        "location": {
          "enum": [
            "frontBodice",
            "backBodice",
            "shoulder",
            "waist",
            null
          ]
        }
      }
    },
    "backDetail": {
      "enum": [
        "none",
        "openBack",
        "keyholeBack",
        "vBack",
        "tieBack",
        "lacedBack",
        "buttonBack",
        null
      ]
    },
    "outOfVocab": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 120
      },
      "maxItems": 24
    },
    "details": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 400
    }
  }
};
