// GENERATED by engine/tools/gen-vocab.mjs from engine/vocab.json — DO NOT EDIT.
// values order == C++ enum declaration order, so indexOf(name) == enum int.
// synonyms map alternate inputs (vision phrasing, legacy aliases) to canonical
// values — resolve them BEFORE the engine boundary; the boundary itself only
// accepts canonical values.

export const VOCAB = {
  "garment": {
    "type": "string",
    "enum": "GarmentType",
    "values": [
      "skirt",
      "dress",
      "top"
    ]
  },
  "shaping": {
    "type": "string",
    "enum": "Shaping",
    "values": [
      "princess",
      "dart"
    ]
  },
  "waistline": {
    "type": "string",
    "enum": "Waistline",
    "values": [
      "natural",
      "empire"
    ]
  },
  "fabric": {
    "type": "string",
    "enum": "Fabric",
    "values": [
      "woven",
      "knit"
    ]
  },
  "neckline": {
    "type": "string",
    "enum": "Neckline",
    "values": [
      "crew",
      "scoop",
      "vNeck",
      "square",
      "boat",
      "sweetheart",
      "halter",
      "cowl",
      "pussyBow"
    ]
  },
  "sleeveStyle": {
    "type": "string",
    "enum": "SleeveStyle",
    "values": [
      "none",
      "straight",
      "balloon"
    ],
    "synonyms": {
      "puff": "balloon",
      "bishop": "balloon",
      "set-in": "straight",
      "fitted": "straight"
    }
  },
  "sleeveLength": {
    "type": "string",
    "enum": "SleeveLength",
    "values": [
      "short",
      "elbow",
      "long"
    ]
  },
  "skirtStyle": {
    "type": "string",
    "enum": "SkirtStyle",
    "values": [
      "aLine",
      "straight",
      "gathered",
      "halfCircle",
      "pleated",
      "gore"
    ],
    "synonyms": {
      "gored": "gore",
      "sixGore": "gore",
      "panelled": "gore",
      "paneled": "gore"
    }
  },
  "skirtLength": {
    "type": "string",
    "enum": "SkirtLength",
    "values": [
      "mini",
      "midi",
      "maxi"
    ]
  },
  "topLength": {
    "type": "string",
    "enum": "TopLength",
    "values": [
      "cropped",
      "hip",
      "tunic"
    ]
  },
  "tieClosure": {
    "type": "int",
    "enum": "TiePlacement",
    "values": [
      "none",
      "backWaist",
      "backWaistBow",
      "frontNeckBow",
      "tieBack",
      "cuffTies",
      "frontWaistTie",
      "wrapFront",
      "frontWaistBow"
    ]
  },
  "sleeveCap": {
    "type": "int",
    "enum": "SleeveCap",
    "values": [
      "plain",
      "gathered",
      "puffed",
      "cap"
    ]
  },
  "collarType": {
    "type": "int",
    "enum": "CollarType",
    "values": [
      "none",
      "stand",
      "mock",
      "flat",
      "peterPan",
      "shirt"
    ]
  },
  "collarEdge": {
    "type": "int",
    "enum": "CollarEdge",
    "values": [
      "round",
      "pointed",
      "scallop"
    ]
  },
  "gatherType": {
    "type": "int",
    "enum": "GatherType",
    "values": [
      "none",
      "drawstring",
      "shirred",
      "smocked"
    ]
  },
  "gatherZone": {
    "type": "int",
    "enum": "GatherZone",
    "values": [
      "neckline",
      "bust",
      "waist",
      "sleeve"
    ]
  },
  "backOpening": {
    "type": "int",
    "enum": "BackOpening",
    "values": [
      "none",
      "round",
      "lowV",
      "square",
      "keyhole"
    ]
  },
  "laceUpBack": {
    "type": "int",
    "enum": "LaceUpBack",
    "values": [
      "none",
      "corset"
    ]
  },
  "wrapFront": {
    "type": "int",
    "enum": "WrapFront",
    "values": [
      "none",
      "surplice"
    ]
  },
  "backSlit": {
    "type": "int",
    "enum": "HemSlit",
    "values": [
      "none",
      "vent",
      "slit"
    ]
  },
  "ruffledStraps": {
    "type": "int",
    "enum": "StrapStyle",
    "values": [
      "none",
      "ruffled",
      "wide",
      "spaghetti"
    ]
  },
  "peplum": {
    "type": "int",
    "enum": "PeplumStyle",
    "values": [
      "none",
      "full",
      "half",
      "pointed"
    ]
  },
  "hemFlounce": {
    "type": "int",
    "enum": "HemFlounce",
    "values": [
      "none",
      "gathered"
    ]
  },
  "placketStyle": {
    "type": "int",
    "enum": "PlacketStyle",
    "values": [
      "none",
      "standard",
      "asymmetric"
    ]
  },
  "edgeFinish": {
    "type": "int",
    "enum": "EdgeFinish",
    "values": [
      "biasBinding",
      "facing"
    ],
    "synonyms": {
      "bias": "biasBinding"
    }
  },
  "pocketStyle": {
    "type": "int",
    "enum": "PocketStyle",
    "values": [
      "none",
      "patch",
      "sideSeam",
      "slash"
    ]
  },
  "cuffStyle": {
    "type": "int",
    "enum": "CuffStyle",
    "values": [
      "none",
      "button",
      "ribbed"
    ]
  },
  "hemShape": {
    "type": "int",
    "enum": "HemShape",
    "values": [
      "straight",
      "shirttail",
      "highLow",
      "pointedV",
      "boxPleatHem"
    ]
  },
  "shoulderStyle": {
    "type": "int",
    "enum": "ShoulderStyle",
    "values": [
      "set",
      "dropped",
      "raglan"
    ]
  },
  "buttonRow": {
    "type": "int",
    "enum": "ButtonRow",
    "values": [
      "none",
      "functional",
      "decorative"
    ]
  },
  "exposedZip": {
    "type": "int",
    "enum": "ExposedZip",
    "values": [
      "none",
      "centerFront",
      "centerBack"
    ]
  },
  "backDetail": {
    "type": "int",
    "enum": "BackDetail",
    "values": [
      "none",
      "ruffle",
      "cape",
      "flounce"
    ]
  },
  "bardotStyle": {
    "type": "int",
    "enum": "BardotStyle",
    "values": [
      "none",
      "plain",
      "frill"
    ]
  },
  "cupSeam": {
    "type": "int",
    "enum": "CupSeam",
    "values": [
      "none",
      "horizontal",
      "bugra"
    ]
  },
  "yoke": {
    "type": "int",
    "enum": "Yoke",
    "values": [
      "none",
      "plain",
      "gathered"
    ]
  },
  "boxPleat": {
    "type": "int",
    "enum": "BoxPleat",
    "values": [
      "none",
      "centerInverted"
    ]
  }
};

// Canonical value name -> enum int for an int-typed field; -1 when unknown.
export function enumInt(field, name) {
  const def = VOCAB[field];
  if (!def) return -1;
  return def.values.indexOf(name);
}

// Resolve a synonym to its canonical value (returns the input when it is
// already canonical, undefined when the value is unknown to the field).
export function canonical(field, name) {
  const def = VOCAB[field];
  if (!def) return undefined;
  if (def.values.includes(name)) return name;
  if (def.synonyms && Object.prototype.hasOwnProperty.call(def.synonyms, name)) return def.synonyms[name];
  return undefined;
}
