#pragma once
// GENERATED by engine/tools/gen-constants.mjs from engine/constants.yaml — DO NOT EDIT.
// The K4 constants table relocates embedded design assumptions; it never
// changes them. The golden reference is the guard: a value drift here fails
// the byte-identical diff. Status per row (verified/assumed/refuted) lives in
// constants.yaml with its source + experiment; refuted values stay unchanged
// in this chain (a value change is a behaviour change — v1.1 candidates).

namespace stitchu {
namespace constants {

// seamAllowanceMM [mm] — verified
inline constexpr double kSeamAllowanceMM = 15;
// seamAllowanceBandMM [mm] — assumed
inline constexpr double kSeamAllowanceBandMM = 10;
// seamAllowanceRuffleJoinMM [mm] — assumed
inline constexpr double kSeamAllowanceRuffleJoinMM = 12;
// buttonDiameterMM [mm] — assumed
inline constexpr double kButtonDiameterMM = 18;
// bicepsBustRatio [ratio] — refuted
inline constexpr double kBicepsBustRatio = 0.30;
// shoulderDropFactorDeprecated [ratio] — refuted
inline constexpr double kShoulderDropFactorDeprecated = 0.23;
// shoulderSlopeDeg [deg] — verified
inline constexpr double kShoulderSlopeDeg = 22.0;
// shoulderSeamTargetMM [mm] — verified
inline constexpr double kShoulderSeamTargetMM = 126.0;
// underbustOffsetMM [mm] — assumed
inline constexpr double kUnderbustOffsetMM = 70;
// capWingDepthMM [mm] — assumed
inline constexpr double kCapWingDepthMM = 55;
// strapFinishedWidthMM [mm] — assumed
inline constexpr double kStrapFinishedWidthMM = 22;
// ventExtensionMM [mm] — assumed
inline constexpr double kVentExtensionMM = 40;
// strapFullness [ratio] — assumed
inline constexpr double kStrapFullness = 2.2;
// backRuffleFullness [ratio] — assumed
inline constexpr double kBackRuffleFullness = 2.2;
// bardotFrillFullness [ratio] — assumed
inline constexpr double kBardotFrillFullness = 2.0;
// ruffleFullnessDefault [ratio] — assumed
inline constexpr double kRuffleFullnessDefault = 2.5;

} // namespace constants
} // namespace stitchu
