#!/usr/bin/env node
// gen-anchors.mjs — THE ANCHOR DICTIONARY IS A BUILD PRODUCT.
//
// WHY THIS FILE EXISTS. "fiyonk ekle ŞURAYA" needs a name for ŞURASI. A
// hand-written list of such names is a MENU: it looks like a vocabulary and is
// really somebody's taste, and nothing in the tree can tell the two apart.
// GECE/V6-C.md measured what the tree can actually source:
//   - edge-granularity anchors: NOT sourceable. `primitives-v1.json`
//     `primitifler.edge.parametreler.label` defines an edge-label FIELD and no
//     producer fills it; PatternPiece (engine/src/geometry.hpp:40) has no
//     counterpart, and the artefact prints it 0 times over 88 specs.
//   - panel-granularity anchors: sourceable and already computed today
//     (spec-diff.mjs touchedZones/untouchablePatterns over the printed
//     pattern.pieces[].name).
// So this generator emits ONLY what has a source, and writes the source next to
// every single record. `kaynak` is a dosya:anahtar path; the guard
// (engine/tests/anchor_source_check.mjs) re-resolves every one of them.
//
// ★ THE CROSS PRODUCT IS BANNED, AND V6-C PRICED IT. Running the naive
// `taraf × jeton` generation gave 54 candidates of which at least 8 contradict
// themselves (`frontCenterback`, `backCenterfront`, `frontBack`, ...). An
// anchor is born ONLY from a position a COMPONENT DECLARES. A name nothing
// declares is not emitted — not emitted quietly either: it lands in
// `_dogmayan` with the reason, because throwing information away is worse than
// not giving it (primitives-v1.json:_yasa.5).
//
// TWO FAMILIES, BOTH DERIVED:
//   A `bolge`     — contract/edit-locality-v1.json:zones.<z>, kept only when at
//                   least one contract/composition.json component declares <z>
//                   in its conflictClass AND the engine actually prints a panel
//                   the zone leaves touchable.
//   B `operator`  — contract/primitives-v1.json:bilesenler.<c>.primitifler says
//                   which operators component <c> uses; the operator's own
//                   position parameter declares the position values. Only the
//                   (component, position) pairs the bundle declares are born —
//                   this is a JOIN over declarations, not a cross product.
//
// PANELS ARE MEASURED, NEVER LISTED. The panel census drafts the engine over
// every garment × every editable field value (contract/edit-locality-v1.json
// fieldZones × engine/vocab.json values) and collects pattern.pieces[].name.
// Specs the engine refuses are skipped by design: Result::Err is an answer
// (RULES md.1), not a panel.
//
// USAGE
//   node engine/tools/gen-anchors.mjs            # write contract/anchors-v1.json
//   node engine/tools/gen-anchors.mjs --check    # regen + compare, exit 1 on drift
//   node engine/tools/gen-anchors.mjs --out P    # write elsewhere (gates use this)
//   node engine/tools/gen-anchors.mjs --cross    # MUTATION PROOF ONLY: re-enable
//                                                # the banned cross product
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { draft, LOCALITY, BODY } from './spec-diff.mjs';
import { VOCAB } from '../../web/js/vocab.gen.js';

const here = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(here, '../..');

const STAMP = 'GENERATED by engine/tools/gen-anchors.mjs — DO NOT EDIT';

const J = (p) => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));

// ── sources, opened by name ───────────────────────────────────────────────────
export const SRC = {
  locality: 'contract/edit-locality-v1.json',
  composition: 'contract/composition.json',
  primitives: 'contract/primitives-v1.json',
  specv2: 'contract/garment-spec-v2.json',
};

// A parameter DECLARES A POSITION when its own key says so. This is a rule over
// the source's key names (fromLandmark / position / region), not a hand list of
// anchors — the guard re-derives it from the same file independently.
export const POSITION_PARAM = /landmark|position|region/i;
// An operator supports an edge fraction when one of its parameters is declared
// with the contract's own fraction type (primitives-v1.json:_birimler.kesir).
const FRACTION_TYPE = 'kesir';

// ── 1. PANEL CENSUS — measured from the engine, never listed ─────────────────
export async function panelCensus() {
  const fields = Object.keys(LOCALITY.fieldZones);
  const defaults = {};
  for (const f of fields) if (VOCAB[f]) defaults[f] = VOCAB[f].values[0];
  const garments = VOCAB.garment ? VOCAB.garment.values : [];

  const panels = new Map(); // name -> Set("field=value")
  let ok = 0;
  let refused = 0;
  for (const g of garments) {
    const base = { ...defaults, garment: g };
    for (const f of fields) {
      if (!VOCAB[f]) continue;
      for (const v of VOCAB[f].values) {
        const r = await draft({ ...base, [f]: v }, BODY);
        if (r.error || !r.pattern || !Array.isArray(r.pattern.pieces)) { refused++; continue; }
        ok++;
        for (const p of r.pattern.pieces) {
          if (!panels.has(p.name)) panels.set(p.name, new Set());
          panels.get(p.name).add(`${g}/${f}=${v}`);
        }
      }
    }
  }
  return { panels, drafted: ok + refused, ok, refused };
}

// Panel -> katman-2 component. The mapping rule is the component KEY itself
// (primitives-v1.json:bilesenler.<c>): a panel belongs to <c> when its printed
// name carries <c> as a word, case-insensitively. Panels no component key
// matches get NO anchor and are reported as a measured gap.
export function componentOfPanel(name, componentIds) {
  const lower = name.toLowerCase();
  return componentIds.filter((c) => new RegExp(`\\b${c}\\b`, 'i').test(lower));
}

// ── 2. BUILD ─────────────────────────────────────────────────────────────────
export async function build({ cross = false } = {}) {
  const locality = J(SRC.locality);
  const composition = J(SRC.composition);
  const primitives = J(SRC.primitives);
  const specv2 = J(SRC.specv2);

  const { panels, drafted, ok, refused } = await panelCensus();
  const panelNames = [...panels.keys()].sort();
  // PANEL NAMES ARE WRITTEN ONCE. Every anchor used to repeat the full list of
  // panels it lands on, so an 86-name census was re-spelled 19 times over. That
  // is not just bytes: the printed panel names carry closed-enum words, and
  // engine/tests/vocab_reference_check.sh counts a WORD PER LINE, so each repeat
  // was a fresh reference to a closed enum: the worst single panel name was
  // re-spelled 12 times, and this comment deliberately does not quote it —
  // quoting one here would itself be a 38th reference (measured: naming it cost
  // +1 on that axis). The census below is the single copy; anchors point
  // into it BY INDEX. Nothing is lost — the index is total and re-resolvable,
  // and engine/tests/anchor_source_check.mjs re-resolves every one of them and
  // goes RED on an index that names no panel.
  const panelIdx = new Map(panelNames.map((n, i) => [n, i]));
  const toIdx = (names) => names.map((n) => panelIdx.get(n));

  const componentIds = Object.keys(primitives.bilesenler).filter((k) => !k.startsWith('_')).sort();
  const panelComponents = new Map(panelNames.map((n) => [n, componentOfPanel(n, componentIds)]));
  const orphanPanels = panelNames.filter((n) => panelComponents.get(n).length === 0);

  const anchors = [];
  const dogmayan = []; // names that had no source — kept, never emitted as anchors

  // ── family A: zones a component DECLARES ───────────────────────────────────
  // conflictClass carries '|' and '+' separators (edit-locality _bolge_kaynagi).
  const declaresZone = new Map();
  composition.components.forEach((c, i) => {
    const zones = String(c.conflictClass || '').split(/[|+]/).map((s) => s.trim()).filter(Boolean);
    for (const z of zones) {
      if (!declaresZone.has(z)) declaresZone.set(z, []);
      declaresZone.get(z).push({ id: c.id, idx: i });
    }
  });

  for (const z of Object.keys(locality.zones).sort()) {
    const zone = locality.zones[z];
    const decl = (declaresZone.get(z) || []).slice().sort((a, b) => a.id.localeCompare(b.id));
    if (!decl.length) {
      dogmayan.push({
        ad: z,
        sebep: `hicbir bilesen ilan etmiyor: ${SRC.composition}:components[].conflictClass icinde '${z}' gecmiyor`,
      });
      continue;
    }
    const pats = (zone.untouchable || []).map((p) => new RegExp(p));
    const iner = panelNames.filter((n) => !pats.some((re) => re.test(n)));
    if (!iner.length) {
      dogmayan.push({ ad: z, sebep: 'olculen panellerin hepsi bu bolgede untouchable — cipa hicbir panele inmiyor' });
      continue;
    }
    // Edge-fraction support is inherited from the components the landed panels
    // belong to: a fraction needs an operator that declares one.
    const comps = [...new Set(iner.flatMap((n) => panelComponents.get(n)))].sort();
    const frac = fractionSupport(primitives, comps);
    anchors.push({
      ad: z,
      aile: 'bolge',
      kaynak: `${SRC.locality}:zones.${z}`,
      // NO `bilesen` NAME ARRAY. The component id is already spelled inside the
      // source path below (`components[<idx>].conflictClass`), so a parallel
      // array of ids was the same word written twice — the `eslesen` mistake of
      // V6-F, one field over. The bekci resolves the path back to the id and
      // compares it against composition.json, so nothing is lost by dropping it.
      bilesenKaynak: decl.map((d) => `${SRC.composition}:components[${d.idx}].conflictClass`),
      panelDeseni: {
        yontem: 'olculdu — motorun bastigi panel adlari eksi bolgenin untouchable RegExp listesi',
        dislayan: zone.untouchable || [],
        eslesenIndeks: toIdx(iner),
      },
      kenarOrani: frac.destek,
      kenarOraniKaynak: frac.kaynak,
    });
  }

  // ── family B: (component, position) pairs THREE declarations agree on ──────
  // A component declaring an OPERATOR does not declare WHERE: `cuff` uses
  // op.attach, but op.attach.position lists 8 values and `cuff.neck` is not one
  // of the cuff's. Taking all 8 would be the cross product again, one level
  // down. The third declaration closes it: a position value is a place in this
  // tree only when edit-locality declares a ZONE for it, and that zone declares
  // whether the component's panels are touchable there. So the join is
  //   component -uses-> operator -declares-> position -is a-> zone -admits->
  //   the component's measured panels
  // and a link that is missing kills the name instead of guessing it.
  const zoneNames = Object.keys(locality.zones);
  const zoneForPosition = (v) =>
    zoneNames.find((z) => z === v || z === `${v}Zone` || z.toLowerCase() === `${v.toLowerCase()}zone`) || null;

  for (const c of componentIds) {
    const bundle = primitives.bilesenler[c].primitifler || [];
    const iner = panelNames.filter((n) => panelComponents.get(n).includes(c));
    for (const opName of bundle) {
      const op = primitives.primitifler[opName];
      if (!op || !op.parametreler) continue;
      for (const pName of Object.keys(op.parametreler)) {
        const p = op.parametreler[pName];
        if (!POSITION_PARAM.test(pName)) continue;
        if (p.tip !== 'enum' || !Array.isArray(p.degerler)) continue;
        const frac = fractionSupport(primitives, [c]);
        for (const v of p.degerler) {
          const ad = `${c}.${v}`;
          if (!iner.length) {
            dogmayan.push({
              ad,
              sebep: `bilesen '${c}' icin motorun bastigi hicbir panel yok — ad hicbir yere inmiyor`,
            });
            continue;
          }
          const z = zoneForPosition(v);
          if (!z) {
            dogmayan.push({
              ad,
              sebep:
                `konum '${v}' icin ${SRC.locality}:zones altinda bolge YOK — ` +
                `konumun kalibin neresi oldugunu ilan eden hicbir kayit yok`,
            });
            continue;
          }
          const pats = (locality.zones[z].untouchable || []).map((re) => new RegExp(re));
          const admitted = iner.filter((n) => !pats.some((re) => re.test(n)));
          if (!admitted.length) {
            dogmayan.push({
              ad,
              sebep:
                `bolge '${z}' bileseni '${c}' DISLIYOR (${SRC.locality}:zones.${z}.untouchable) — ` +
                `celisik ad, uretilmedi`,
            });
            continue;
          }
          anchors.push({
            ad,
            aile: 'operator',
            kaynak: `${SRC.primitives}:primitifler.${opName}.parametreler.${pName}.degerler.${v}`,
            bilesenKaynak: [
              `${SRC.primitives}:bilesenler.${c}.primitifler.${opName}`,
              `${SRC.locality}:zones.${z}`,
            ],
            bolge: z,
            panelDeseni: {
              yontem:
                `olculdu — panel adi bilesen anahtarini ('${c}') kelime olarak tasiyor, ` +
                `ve bolge '${z}' onu dislamiyor`,
              dislayan: locality.zones[z].untouchable || [],
              eslesenIndeks: toIdx(admitted),
            },
            kenarOrani: frac.destek,
            kenarOraniKaynak: frac.kaynak,
          });
        }
      }
    }
  }

  // ── the BANNED cross product, behind a flag, for the mutation proof only ───
  if (cross) {
    const sides = ['front', 'back'];
    const tokens = new Set();
    for (const opName of Object.keys(primitives.primitifler)) {
      const op = primitives.primitifler[opName];
      for (const pName of Object.keys(op.parametreler || {})) {
        const p = op.parametreler[pName];
        if (POSITION_PARAM.test(pName) && Array.isArray(p.degerler)) p.degerler.forEach((v) => tokens.add(v));
      }
    }
    for (const s of sides) {
      for (const t of [...tokens].sort()) {
        anchors.push({
          ad: `${s}${t[0].toUpperCase()}${t.slice(1)}`,
          aile: 'kross',
          kaynak: `${SRC.primitives}:KROSS-CARPIM`,
          bilesenKaynak: [],
          panelDeseni: { yontem: 'kross-carpim', dislayan: [], eslesenIndeks: [] },
          kenarOrani: false,
          kenarOraniKaynak: null,
        });
      }
    }
  }

  anchors.sort((a, b) => (a.aile + ' ' + a.ad).localeCompare(b.aile + ' ' + b.ad, 'en'));
  dogmayan.sort((a, b) => a.ad.localeCompare(b.ad, 'en'));

  // garment-spec-v2's operator register, counted by STATUS only. The names are
  // deliberately not copied here: V6-C md.4 flagged that the v2 register
  // describes the SURFACE line while the artefact measured above comes off the
  // OLD line, so a name copied across would assert an agreement nobody has
  // shown. The counts are still worth carrying — they say how much of the
  // topology the register itself calls shipped.
  const sicilSayim = {};
  for (const [id, op] of Object.entries(specv2.operators || {})) {
    if (id.startsWith('_')) continue;
    const st = op.status || 'bilinmiyor';
    sicilSayim[st] = (sicilSayim[st] || 0) + 1;
  }

  return {
    doc: {
      _GENERATED: STAMP,
      _nasil:
        'Cipa, bir bilesenin ILAN ETTIGI konumdan dogar. Iki aile: (a) bolge — ' +
        'edit-locality zone, en az bir composition bileseni conflictClass icinde ilan ' +
        'etmisse; (b) operator — primitives bilesenler[<c>].primitifler bir operator ' +
        'sayiyorsa, o operatorun konum parametresinin ilan ettigi degerler. Kross-carpim ' +
        'YASAK (GECE/V6-C.md md.4: 54 adayin en az 8i kendiyle celisik).',
      _granularite:
        'PANEL. Kenar granularitesi bugun URETILEMEZ: primitives-v1.json ' +
        'primitifler.edge.parametreler.label bir alan TANIMLIYOR, dolduran uretici yok ve ' +
        'engine/src/geometry.hpp PatternPiece karsiligini tasimiyor (GECE/V6-C.md md.2).',
      _kaynaklar: SRC,
      _olcum: {
        drafted: drafted,
        motorKabul: ok,
        motorRed: refused,
        panelAdi: panelNames.length,
        cipa: anchors.length,
        kenarOraniTasiyan: anchors.filter((a) => a.kenarOrani).length,
        dogmayanAd: dogmayan.length,
      },
      _panelIndeksi:
        'panelDeseni.eslesenIndeks ve _bilesensizPaneller.indeks, _olculenPaneller ' +
        'dizisine 0-tabanli indekstir. Panel adi bu dosyada TEK KEZ yazilir; tekrar ' +
        'eden ad, kapali bir sozluge tekrar eden referanstir (olculdu: 12 satir). ' +
        'Indeksi bekci (engine/tests/anchor_source_check.mjs) BAGIMSIZ yeniden cozer, ' +
        've karsiligi olmayan indekste KIRMIZI duser.',
      _olculenPaneller: panelNames,
      _bilesensizPaneller: {
        _not:
          'Bu paneller hicbir katman-2 bilesen anahtarini kelime olarak tasimiyor, o yuzden ' +
          'operator ailesinde cipa dogurmuyorlar. Olculen bosluk, gizlenmedi. ' +
          'Degerler _olculenPaneller indeksidir.',
        indeks: toIdx(orphanPanels),
      },
      _operatorSicilSayim: sicilSayim,
      _dogmayan: dogmayan,
      anchors,
    },
  };
}

function fractionSupport(primitives, componentIds) {
  for (const c of componentIds.slice().sort()) {
    const bundle = (primitives.bilesenler[c] && primitives.bilesenler[c].primitifler) || [];
    for (const opName of bundle.slice().sort()) {
      const op = primitives.primitifler[opName];
      for (const pName of Object.keys((op && op.parametreler) || {}).sort()) {
        if (op.parametreler[pName].tip === FRACTION_TYPE) {
          return { destek: true, kaynak: `${SRC.primitives}:primitifler.${opName}.parametreler.${pName}` };
        }
      }
    }
  }
  return { destek: false, kaynak: null };
}

// ── 3. SERIALISE — stamp on line 1, JSON still valid ─────────────────────────
export function serialise(doc) {
  const body = JSON.stringify(doc, null, 2);
  // JSON.stringify puts `{\n  "_GENERATED": "..."` on lines 1-2; hoist the stamp
  // onto line 1 so `head -1` shows it without breaking the parser.
  return body.replace(/^\{\n {2}/, '{ ') + '\n';
}

// ── main ─────────────────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const isMain = process.argv[1] && process.argv[1].endsWith('gen-anchors.mjs');
if (isMain) {
  const outIdx = args.indexOf('--out');
  const out = outIdx >= 0 ? args[outIdx + 1] : join(ROOT, 'contract/anchors-v1.json');
  const { doc } = await build({ cross: args.includes('--cross') });
  const text = serialise(doc);
  if (args.includes('--check')) {
    let onDisk;
    try {
      onDisk = readFileSync(out, 'utf8');
    } catch {
      console.error(`FAIL: ${out} missing — a missing law is never a pass.`);
      process.exit(1);
    }
    if (onDisk !== text) {
      console.error(`FAIL: ${out} is STALE or HAND-EDITED — it is not what gen-anchors.mjs produces.`);
      console.error('      fix: node engine/tools/gen-anchors.mjs   (never by editing the JSON)');
      const a = text.split('\n');
      const b = onDisk.split('\n');
      let shown = 0;
      for (let i = 0; i < Math.max(a.length, b.length) && shown < 20; i++) {
        if (a[i] !== b[i]) { console.error(`      line ${i + 1}\n        gen : ${a[i]}\n        disk: ${b[i]}`); shown++; }
      }
      process.exit(1);
    }
    console.log(`ok: ${out} byte-identical to the generator (${doc._olcum.cipa} anchors, ${text.length} bytes)`);
    process.exit(0);
  }
  writeFileSync(out, text);
  console.log(
    `wrote ${out}: ${doc._olcum.cipa} anchors, ${doc._olcum.kenarOraniTasiyan} carry an edge fraction, ` +
      `${doc._olcum.panelAdi} panel names measured over ${doc._olcum.drafted} drafts ` +
      `(${doc._olcum.motorRed} refused by the engine), ${doc._olcum.dogmayanAd} names NOT born.`,
  );
}
