// GENERATED by engine/tools/gen-contract.mjs from contract/tables.json — DO NOT EDIT.
// Single source for every shared cross-layer value + the vision-reading
// schema (embedded from contract/garment-spec.schema.json $defs.visionReading
// so the browser validates without fetching the contract dir).

export const CONTRACT = {
  "version": "1.0.0",
  "draft": {
    "skirtLengthMM": {
      "mini": 450,
      "midi": 650,
      "maxi": 900
    },
    "gatherRatios": {
      "drawstring": 1.8,
      "shirred": 2,
      "smocked": 3,
      "sleeveCapPuffed": 1.29,
      "sleeveCapGathered": 1.235,
      "sleeveCapPuffedLift": 1.08
    },
    "euSizes": [
      "EU34",
      "EU36",
      "EU38",
      "EU40",
      "EU42",
      "EU44",
      "EU46",
      "EU48",
      "EU50",
      "EU52"
    ],
    "euSizeChart": {
      "EU34": [
        80,
        62,
        86,
        36,
        39.5,
        57,
        34
      ],
      "EU36": [
        84,
        66,
        90,
        36.5,
        40,
        57.5,
        34.5
      ],
      "EU38": [
        88,
        70,
        94,
        37,
        40.5,
        58,
        35
      ],
      "EU40": [
        92,
        74,
        98,
        37.5,
        41,
        58.5,
        36
      ],
      "EU42": [
        96,
        78,
        102,
        38,
        41.5,
        59,
        36.5
      ],
      "EU44": [
        100,
        82,
        106,
        38.5,
        42,
        59.5,
        37
      ],
      "EU46": [
        104,
        86,
        110,
        39,
        42,
        60,
        38
      ],
      "EU48": [
        110,
        92,
        116,
        40,
        42.5,
        60.5,
        39
      ],
      "EU50": [
        116,
        98,
        122,
        41,
        43,
        61,
        40
      ],
      "EU52": [
        122,
        104,
        128,
        42,
        43.5,
        61.5,
        41
      ]
    },
    "euSizeChartFields": [
      "bustCM",
      "waistCM",
      "hipCM",
      "shoulderCM",
      "backLengthCM",
      "armLengthCM",
      "neckCM"
    ]
  },
  "flat": {
    "unitPX": 5.6,
    "len": {
      "mini": 42,
      "knee": 58,
      "midi": 74
    },
    "size": {
      "_fields": [
        "neck",
        "shp",
        "strap",
        "bust",
        "emp",
        "ad"
      ],
      "EU34": {
        "neck": 6.6,
        "shp": 11.9,
        "strap": 6.8,
        "bust": 14.6,
        "emp": 13.2,
        "ad": 19.6
      },
      "EU36": {
        "neck": 6.8,
        "shp": 12.2,
        "strap": 7.1,
        "bust": 15,
        "emp": 13.7,
        "ad": 20
      },
      "EU38": {
        "neck": 7,
        "shp": 12.6,
        "strap": 7.4,
        "bust": 15.5,
        "emp": 14.2,
        "ad": 20.6
      },
      "EU40": {
        "neck": 7.3,
        "shp": 13.1,
        "strap": 7.7,
        "bust": 16.2,
        "emp": 14.9,
        "ad": 21.2
      },
      "EU42": {
        "neck": 7.6,
        "shp": 13.6,
        "strap": 8,
        "bust": 17,
        "emp": 15.7,
        "ad": 21.8
      }
    }
  },
  "mappings": {
    "sleeveHeadToSleeveCap": {
      "plain": "plain",
      "gathered": "gathered",
      "puffed": "puffed",
      "puff": "puffed",
      "capped": "cap",
      "cap": "cap"
    },
    "nullEquivalence": {
      "sleeveStyle": "none"
    },
    "backDetailSplit": {
      "openBack": {
        "target": "backOpening",
        "value": "round"
      },
      "keyholeBack": {
        "target": "backOpening",
        "value": "keyhole"
      },
      "vBack": {
        "target": "backOpening",
        "value": "lowV"
      },
      "tieBack": {
        "target": "tieClosure",
        "value": "tieBack"
      },
      "lacedBack": {
        "target": "honest"
      },
      "buttonBack": {
        "target": "honest"
      }
    },
    "seenFlags": [
      "backDetailDrawn",
      "backOpeningDrawn",
      "bardotDrawn",
      "buttonRowDrawn",
      "capSleeveDrawn",
      "closureDrawn",
      "collarDrawn",
      "cuffDrawn",
      "exposedZipDrawn",
      "gatherDrawn",
      "hemShapeDrawn",
      "hemSlitDrawn",
      "peplumDrawn",
      "placketAsymDrawn",
      "pocketDrawn",
      "ruffledStrapsDrawn",
      "sleeveCapDrawn",
      "tieDrawn"
    ]
  }
};

export const VISION_SCHEMA = {
  "description": "What the vision layer is allowed to say about a photo. SEMANTIC ONLY. Unknown fields are rejected (additionalProperties:false); a value outside its enum is invalid. The bridge (web/js/vision-bridge.js) compiles this into draftSpec; the declared cross-layer translations live in contract/tables.json mappings.*.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "garment": {
      "enum": [
        "skirt",
        "dress",
        "top",
        "trousers",
        "other"
      ]
    },
    "neckline": {
      "enum": [
        "crew",
        "scoop",
        "vNeck",
        "square",
        "boat",
        "sweetheart",
        "halter",
        "cowl",
        "pussyBow",
        null
      ]
    },
    "sleeveStyle": {
      "enum": [
        "none",
        "straight",
        "balloon",
        null
      ]
    },
    "sleeveLength": {
      "enum": [
        "short",
        "elbow",
        "long",
        null
      ]
    },
    "skirtStyle": {
      "enum": [
        "aLine",
        "straight",
        "gathered",
        "halfCircle",
        "pleated",
        "gore",
        null
      ]
    },
    "length": {
      "enum": [
        "mini",
        "midi",
        "maxi",
        null
      ]
    },
    "topLength": {
      "enum": [
        "cropped",
        "hip",
        "tunic",
        null
      ]
    },
    "shaping": {
      "enum": [
        "princess",
        "dart",
        null
      ]
    },
    "waistline": {
      "enum": [
        "natural",
        "empire",
        null
      ]
    },
    "fabric": {
      "enum": [
        "woven",
        "knit",
        null
      ]
    },
    "hemRuffle": {
      "enum": [
        "none",
        "single",
        "tiered",
        null
      ]
    },
    "keyhole": {
      "type": [
        "boolean",
        "null"
      ]
    },
    "fabricName": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 60
    },
    "closure": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "buttons",
            "placket",
            "zipper",
            "ties",
            "lace-up",
            "hookEye",
            "none",
            null
          ]
        },
        "location": {
          "enum": [
            "centerFront",
            "centerBack",
            "sideSeam",
            "shoulder",
            "neck",
            "waist",
            null
          ]
        }
      }
    },
    "collar": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "stand",
            "shirt",
            "peterPan",
            "mandarin",
            "notched",
            "sailor",
            "other",
            null
          ]
        },
        "name": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 80
        }
      }
    },
    "straps": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "shoulder",
            "spaghetti",
            "wide",
            "halter",
            "ruffled",
            "oneShoulder",
            "offShoulder",
            null
          ]
        },
        "count": {
          "enum": [
            1,
            2,
            null
          ]
        }
      }
    },
    "cupSeams": {
      "type": [
        "boolean",
        "null"
      ]
    },
    "sleeveHead": {
      "enum": [
        "plain",
        "gathered",
        "puffed",
        "capped",
        null
      ]
    },
    "yoke": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "type": {
          "enum": [
            "none",
            "shoulderYoke",
            "shirring",
            "smocking",
            null
          ]
        },
        "location": {
          "enum": [
            "frontBodice",
            "backBodice",
            "shoulder",
            "waist",
            null
          ]
        }
      }
    },
    "backDetail": {
      "enum": [
        "none",
        "openBack",
        "keyholeBack",
        "vBack",
        "tieBack",
        "lacedBack",
        "buttonBack",
        null
      ]
    },
    "outOfVocab": {
      "type": "array",
      "items": {
        "type": "string",
        "maxLength": 120
      },
      "maxItems": 24
    },
    "details": {
      "type": [
        "string",
        "null"
      ],
      "maxLength": 400
    },
    "ratios": {
      "description": "MEASURED garment proportions (foto-oran kablosu): each value is one garment measurement divided by another garment measurement, so flat-lay and worn photos read the same. null per-field when not visible.",
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false,
      "properties": {
        "hemToWaistWidth": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0.5,
          "maximum": 5
        },
        "lengthToWidth": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0.2,
          "maximum": 6
        },
        "neckDepthToLength": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 0.6
        },
        "neckWidthToShoulder": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 1.2
        },
        "sleeveLenToGarment": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 1.5
        },
        "waistYToLength": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 1
        },
        "strapWidthToShoulder": {
          "type": [
            "number",
            "null"
          ],
          "minimum": 0,
          "maximum": 0.5
        }
      }
    }
  }
};

// F2-vision: photo-reading carriage contract (embedded from
// contract/vision-tasima-v1.json — ratio wires + out-of-vocab mapping).
export const VISION_TASIMA = {
  "_baslik": "F2-vision (2026-09-01) — FOTOGRAF OKUMASININ MOTORA TASINMA SOZLESMESI. Iki tablo: (1) oranKablolari — measure.js'in 7 surekli oraninin her biri motorun HANGI ekseniyle kaliba iner; esik sayilarinin kaynagi motorun KENDI cizdigi mm'ler (engine/tools/vision-esik-olc.mjs, EU38 demo govde, sayilar her kalemin 'kaynak' alaninda) — hicbir esik tahmin degildir. (2) oovEsleme — sozluk disi (outOfVocab) kelimenin motor eksenine esleme DENEMESI; eslesen eksen contract/vocab-resolution-v1.json uzerinden Edge/Panel/Stitch (contract/primitives-v1.json) demetine COZULUR, eslesmeyen ADIYLA reddedilir ve yaninda en yakin cizilebilir oneri tasir. Tuketici: web/js/vision-bridge.js (applyRatioAxes / resolveOutOfVocab). Kapi: engine/tests/vision_tasima_check.mjs (ctest: vision_tasima_check).",
  "_yasa": [
    "1. Sessiz dusme yok: her outOfVocab kelimesi ya 'eslendi' ya 'reddedildi' cikar; uc yol yok.",
    "2. Reddin yaninda kullanicinin atabilecegi bir sonraki adim (oneri) durur.",
    "3. Dusuk guvenli oran ATILMAZ: 'belirsiz' etiketiyle tasinir, kalip tablonun (en kisitlayici) degerini kullanir, etiket ekranda kalir.",
    "4. Esik sayisi ancak motorun kendi cizdigi mm'den ya da motor sabitinden (dosya:satir) gelir. Kaynaksiz sayi bu dosyaya giremez.",
    "5. Yapisal etiket surekli orani EZER (pickSkirtFullness emsali): pili/dikis gibi bir genislik oraninin GOREMEYECEGI yapiyi yalnizca etiket okur."
  ],
  "oranKablolari": {
    "_not": "mm kestirimi pickSkirtLengthMM'in kopru yontemiyle: L_mm = lengthToWidth x bustFlatMM (bustFlat = bust x 10 x 1.08 / 2). Oran sadece seen.ratiosMeasured === true iken tuketilir (olcum tanigi, photo_ratio_wire_check).",
    "lengthToWidth": {
      "eksen": "skirtLengthMM",
      "tip": "surekli mm",
      "kaynak": "mevcut kablo — vision-bridge.js pickSkirtLengthMM (2026-07-27), motor bandi 250-1200mm (measurements.hpp skirtLengthMM)"
    },
    "hemToWaistWidth": {
      "eksen": "skirtStyle",
      "tip": "sinif",
      "kaynak": "mevcut kablo — vision-bridge.js SKIRT_FULLNESS_TABLE (esikler motorun EU38'de cizdigi etek stillerinin orta noktalari)"
    },
    "waistYToLength": {
      "eksen": "waistline",
      "tip": "sinif",
      "esikMM": 375.5,
      "siniflar": {
        "altinda": "empire",
        "ustunde": "natural"
      },
      "kaynak": "motorun kendi cizimi (vision-esik-olc.mjs, EU38): natural Bodice Front boyu 445.0mm, empire 306.0mm; esik orta nokta (445+306)/2"
    },
    "neckDepthToLength": {
      "eksen": "neckline",
      "tip": "sinif (yalniz yuvarlak aile: crew/scoop/boat)",
      "esikMM": 92,
      "siniflar": {
        "altinda": "crew",
        "ustunde": "scoop"
      },
      "kaynak": "motorun kendi cizimi (vision-esik-olc.mjs, EU38): crew CF yaka derinligi 74.5mm, scoop 109.5mm (bodice.cpp:34-35 neckW+15 / neckW+50); esik orta nokta"
    },
    "neckWidthToShoulder": {
      "eksen": "neckline",
      "tip": "sinif (yalniz yuvarlak aile)",
      "esikOran": 0.4377,
      "siniflar": {
        "ustunde": "boat"
      },
      "kaynak": "motorun kendi cizimi (vision-esik-olc.mjs, EU38): crew yaka-yarim/omuz-uc 59.5/164.08 = 0.3626, boat 110.075/214.655 = 0.5128 (bodice.cpp:24 boat carpani 1.85); esik orta nokta"
    },
    "strapWidthToShoulder": {
      "eksen": "ruffledStraps",
      "tip": "sinif (yalniz askili okuma)",
      "esikMM": 15,
      "siniflar": {
        "altinda": "spaghetti",
        "ustunde": "wide"
      },
      "kaynak": "motor sabitleri: spaghetti bitmis genislik 8mm (strap.hpp:40), genis aski bitmis genislik 22mm (constants.gen.hpp:33 kStrapFinishedWidthMM); esik orta nokta. Omuz mm kestirimi: body.shoulder x 10"
    },
    "sleeveLenToGarment": {
      "eksen": "sleeveLength",
      "tip": "sinif",
      "esiklerMM": [
        285.33,
        449.31
      ],
      "siniflar": [
        "short",
        "elbow",
        "long"
      ],
      "kaynak": "motorun kendi cizimi (vision-esik-olc.mjs, EU38 duz kol): short parca boyu 228.83mm, elbow 341.83mm, long 556.8mm; esikler ardil orta noktalar. TASIMA KUNYESI (2026-09-03, M2-bugra): onceki kayit 283.5/448.4 idi ve short 227.0 / elbow 340.0 okumasindan geliyordu. K1 kol oyugunu kendi yayinlanmis Aldrich genislik cizgisine oturttu (bodice.cpp, scye), oyuk cevresi 404.3 -> 422.9 mm buyudu, kol basi onunla birlikte 1.83 mm uzadi. Sayilar SESSIZ degismedi: kaynak kaydi ureticinin bugunku okumasina tasindi, esik GEVSETILMEDI (tolerans 0.6 mm ayni). measure.js v1 bu orani durustce null verir (sleeve_not_separable_from_silhouette_v1) — kablo, oran OLCULEBILDIGI gun icin haziri bekler ve fixture okumalarla test edilir"
    }
  },
  "oovEsleme": {
    "_not": "Kurallar SIRAYLA denenir; ilk eslesen kazanir (reddedilen-ozel kurallar eslenen-genel kurallardan ONCE durur: 'welt pocket' cep kurali yakalamadan reddedilir). 'eslendi' kuralin cozumu contract/vocab-resolution-v1.json '<eksen>.<deger>' anahtarindadir — primitif demeti orada, burada kopyasi tutulmaz. 'reddedildi' kurali sebep + en yakin cizilebilir oneri tasir.",
    "kurallar": [
      {
        "ad": "weltCep",
        "ara": "(welt|besom|bound|jetted|cargo|flap|kangaroo)\\s*pocket|zip(per)?\\s*pocket",
        "durum": "reddedildi",
        "sebep": {
          "en": "the engine cannot draft this pocket construction yet",
          "tr": "motor bu cep yapısını henüz çizemiyor"
        },
        "oneri": {
          "en": "closest it can sew: a patch or side-seam pocket",
          "tr": "en yakın dikebildiği: aplike (patch) ya da yan dikiş cebi"
        }
      },
      {
        "ad": "fransizManset",
        "ara": "(french|elastic|casing)\\s*cuff",
        "durum": "reddedildi",
        "sebep": {
          "en": "a French / elastic-casing cuff is a construction the engine cannot draft yet",
          "tr": "Fransız / lastikli manşet motorun henüz çizemediği bir yapı"
        },
        "oneri": {
          "en": "closest it can sew: a barrel button cuff",
          "tr": "en yakın dikebildiği: düğmeli manşet"
        }
      },
      {
        "ad": "kapusonWatteau",
        "ara": "hood|watteau|shoulder cape",
        "durum": "reddedildi",
        "sebep": {
          "en": "a hood / watteau / shoulder cape is not draftable yet",
          "tr": "kapüşon / watteau / omuz pelerini henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: a back-neck cape piece",
          "tr": "en yakın dikebildiği: arka pelerin parçası"
        }
      },
      {
        "ad": "klapaYaka",
        "ara": "(notched|sailor|lapel).{0,12}collar|\\blapel\\b",
        "durum": "reddedildi",
        "sebep": {
          "en": "tailored notched/sailor/lapel collars are not draftable yet",
          "tr": "klapa / bahriyeli / erkek yaka henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: a shirt or flat collar",
          "tr": "en yakın dikebildiği: gömlek ya da yatık yaka"
        }
      },
      {
        "ad": "kalipliKup",
        "ara": "(moulded|molded|foam|padded)\\s*(cup|bra)",
        "durum": "reddedildi",
        "sebep": {
          "en": "a moulded/padded cup has no seam to draft",
          "tr": "kalıplı/dolgulu kap çizilecek bir dikiş taşımıyor"
        },
        "oneri": {
          "en": "closest it can sew: a horizontal seamed cup",
          "tr": "en yakın dikebildiği: yatay kup dikişi"
        }
      },
      {
        "ad": "piliPeplum",
        "ara": "(pleated|draped|tiered)\\s*peplum",
        "durum": "reddedildi",
        "sebep": {
          "en": "only the circular flared peplum is draftable",
          "tr": "yalnız dairesel volan peplum çizilebiliyor"
        },
        "oneri": {
          "en": "closest it can sew: a full/half circular peplum",
          "tr": "en yakın dikebildiği: tam/yarım dairesel peplum"
        }
      },
      {
        "ad": "mendilEtekUcu",
        "ara": "handkerchief|asymmetric(al)?\\s*hem|diagonal\\s*hem",
        "durum": "reddedildi",
        "sebep": {
          "en": "a handkerchief / asymmetric hem is not draftable yet",
          "tr": "mendil ucu / asimetrik etek ucu henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: a shirt-tail or high-low hem",
          "tr": "en yakın dikebildiği: yuvarlak (shirttail) ya da önü kısa arkası uzun etek ucu"
        }
      },
      {
        "ad": "bicakPili",
        "ara": "(knife|accordion|sunburst|sunray)\\s*pleat",
        "durum": "reddedildi",
        "sebep": {
          "en": "distributed knife/accordion pleating is not draftable yet",
          "tr": "dağıtık bıçak/akordeon pili henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: a pleated skirt style or a single center box pleat",
          "tr": "en yakın dikebildiği: pileli etek stili ya da tek orta kutu pili"
        }
      },
      {
        "ad": "ayrilanFermuar",
        "ara": "(separating|two[\\s-]?way)\\s*zip(per)?",
        "durum": "reddedildi",
        "sebep": {
          "en": "a separating / two-way zip is not draftable yet",
          "tr": "ayrılan / çift yönlü fermuar henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: an exposed CF/CB zipper",
          "tr": "en yakın dikebildiği: görünür ön/arka fermuar"
        }
      },
      {
        "ad": "tekOmuz",
        "ara": "one[\\s-]?shoulder",
        "durum": "reddedildi",
        "sebep": {
          "en": "a one-shoulder cut is not draftable yet",
          "tr": "tek omuz kesim henüz çizilemiyor"
        },
        "oneri": {
          "en": "closest it can sew: an off-shoulder (bardot) band",
          "tr": "en yakın dikebildiği: düşük omuz (bardot) bandı"
        }
      },
      {
        "ad": "anvelopEtekCeket",
        "ara": "wrap[\\s-]?skirt|wrap\\s*(coat|jacket)|kimono|cardigan|\\brobe\\b",
        "durum": "reddedildi",
        "sebep": {
          "en": "a wrap skirt / wrap outerwear is a different build",
          "tr": "anvelop etek / dış giyim farklı bir yapı"
        },
        "oneri": {
          "en": "closest it can sew: a surplice wrap FRONT on a dress/top",
          "tr": "en yakın dikebildiği: elbise/üstte kruvaze ön"
        }
      },
      {
        "ad": "buzgu",
        "ara": "drawstring|shirr|smock|gather",
        "durum": "eslendi",
        "eksen": "gatherType",
        "deger": "shirred",
        "cozum": "vocab-resolution-v1.json: gatherType.shirred"
      },
      {
        "ad": "yaka",
        "ara": "peter\\s?-?pan|mandarin|mock neck|stand(ing)?\\s*collar|shirt\\s*collar|\\bcollar\\b",
        "durum": "eslendi",
        "eksen": "collarType",
        "deger": "peterPan",
        "cozum": "vocab-resolution-v1.json: collarType.*"
      },
      {
        "ad": "acikSirt",
        "ara": "open.?back|back.?cutout|backless",
        "durum": "eslendi",
        "eksen": "backOpening",
        "deger": "round",
        "cozum": "vocab-resolution-v1.json: backOpening.*"
      },
      {
        "ad": "korseBagcik",
        "ara": "corset|lace-?up|laced|eyelet|grommet",
        "durum": "eslendi",
        "eksen": "laceUpBack",
        "deger": "corset",
        "cozum": "vocab-resolution-v1.json: laceUpBack.corset"
      },
      {
        "ad": "kruvazeOn",
        "ara": "surplice|cross[\\s-]?over|faux[\\s-]?wrap|kruvaze|\\bwrap\\b",
        "durum": "eslendi",
        "eksen": "wrapFront",
        "deger": "surplice",
        "cozum": "vocab-resolution-v1.json: wrapFront.surplice"
      },
      {
        "ad": "yirtmac",
        "ara": "\\bslit\\b|\\bvent\\b|kick\\s*pleat",
        "durum": "eslendi",
        "eksen": "backSlit",
        "deger": "slit",
        "cozum": "vocab-resolution-v1.json: backSlit.*"
      },
      {
        "ad": "firfirliAski",
        "ara": "(ruffled?|frilled?|flutter)\\s*(shoulder\\s*)?strap",
        "durum": "eslendi",
        "eksen": "ruffledStraps",
        "deger": "ruffled",
        "cozum": "vocab-resolution-v1.json: ruffledStraps.ruffled"
      },
      {
        "ad": "spagettiAski",
        "ara": "spaghetti\\s*strap|cami\\s*strap",
        "durum": "eslendi",
        "eksen": "ruffledStraps",
        "deger": "spaghetti",
        "cozum": "vocab-resolution-v1.json: ruffledStraps.spaghetti"
      },
      {
        "ad": "genisAski",
        "ara": "(wide|thick)\\s*strap",
        "durum": "eslendi",
        "eksen": "ruffledStraps",
        "deger": "wide",
        "cozum": "vocab-resolution-v1.json: ruffledStraps.wide"
      },
      {
        "ad": "peplum",
        "ara": "peplum|waist\\s*(flounce|frill)",
        "durum": "eslendi",
        "eksen": "peplum",
        "deger": "full",
        "cozum": "vocab-resolution-v1.json: peplum.*"
      },
      {
        "ad": "etekUcuVolani",
        "ara": "(flounce|ruffle|frill|volan|tier(ed)?).{0,20}(hem|bottom|skirt)|(hem|bottom|dropped[\\s-]?waist).{0,20}(flounce|ruffle|frill|tier)",
        "durum": "eslendi",
        "eksen": "hemFlounce",
        "deger": "gathered",
        "cozum": "vocab-resolution-v1.json: hemFlounce.gathered"
      },
      {
        "ad": "cep",
        "ara": "pocket",
        "durum": "eslendi",
        "eksen": "pocketStyle",
        "deger": "patch",
        "cozum": "vocab-resolution-v1.json: pocketStyle.*"
      },
      {
        "ad": "manset",
        "ara": "\\bcuff\\b",
        "durum": "eslendi",
        "eksen": "cuffStyle",
        "deger": "button",
        "cozum": "vocab-resolution-v1.json: cuffStyle.*"
      },
      {
        "ad": "etekUcuSekli",
        "ara": "shirt[\\s-]?tail|shirttail|high[\\s-]?low|mullet|curved hem|corset hem|basque",
        "durum": "eslendi",
        "eksen": "hemShape",
        "deger": "shirttail",
        "cozum": "vocab-resolution-v1.json: hemShape.*"
      },
      {
        "ad": "asimetrikPat",
        "ara": "(asymmetric|asymmetrical|offset|off[\\s-]?cent|diagonal).{0,20}(button|placket|closure|front)",
        "durum": "eslendi",
        "eksen": "placketStyle",
        "deger": "asymmetric",
        "cozum": "vocab-resolution-v1.json: placketStyle.asymmetric"
      },
      {
        "ad": "dugmeSirasi",
        "ara": "button",
        "durum": "eslendi",
        "eksen": "buttonRow",
        "deger": "decorative",
        "cozum": "vocab-resolution-v1.json: buttonRow.*"
      },
      {
        "ad": "arkaDetay",
        "ara": "(back|caped?).{0,15}(cape|ruffle|frill|flounce|cascade)|pelerin",
        "durum": "eslendi",
        "eksen": "backDetail",
        "deger": "cape",
        "cozum": "vocab-resolution-v1.json: backDetail.*"
      },
      {
        "ad": "gorunurFermuar",
        "ara": "(exposed|visible|statement|contrast)\\s*zip(per)?",
        "durum": "eslendi",
        "eksen": "exposedZip",
        "deger": "centerBack",
        "cozum": "vocab-resolution-v1.json: exposedZip.*"
      },
      {
        "ad": "omuzAcik",
        "ara": "off[\\s-]?shoulder|bardot",
        "durum": "eslendi",
        "eksen": "bardotStyle",
        "deger": "plain",
        "cozum": "vocab-resolution-v1.json: bardotStyle.*"
      },
      {
        "ad": "kupDikisi",
        "ara": "cup seam|bra[\\s-]?cup|bustier cup|seamed cup|underbust seam",
        "durum": "eslendi",
        "eksen": "cupSeam",
        "deger": "horizontal",
        "cozum": "vocab-resolution-v1.json: cupSeam.horizontal"
      },
      {
        "ad": "roba",
        "ara": "\\byoke\\b|babydoll|baby doll|swing dress",
        "durum": "eslendi",
        "eksen": "yoke",
        "deger": "plain",
        "cozum": "vocab-resolution-v1.json: yoke.*"
      },
      {
        "ad": "kutuPili",
        "ara": "(box|inverted)[\\s-]*pleat",
        "durum": "eslendi",
        "eksen": "boxPleat",
        "deger": "centerInverted",
        "cozum": "vocab-resolution-v1.json: boxPleat.centerInverted"
      },
      {
        "ad": "fiyonkKusak",
        "ara": "\\b(bow|sash|ties?|ribbon)\\b",
        "durum": "eslendi",
        "eksen": "tieClosure",
        "deger": "backWaistBow",
        "cozum": "vocab-resolution-v1.json: tieClosure.*"
      },
      {
        "ad": "degaje",
        "ara": "cowl",
        "durum": "eslendi",
        "eksen": "neckline",
        "deger": "cowl",
        "cozum": "vocab-resolution-v1.json: neckline.cowl"
      },
      {
        "ad": "kadinFularYaka",
        "ara": "pussy[\\s-]?bow|tie[\\s-]?neck",
        "durum": "eslendi",
        "eksen": "neckline",
        "deger": "pussyBow",
        "cozum": "vocab-resolution-v1.json: neckline.pussyBow"
      }
    ],
    "bilinmeyen": {
      "sebep": {
        "en": "I cannot sew this yet — the word is outside the pattern engine's vocabulary",
        "tr": "bunu henüz dikemiyorum — kelime kalıp motorunun sözlüğü dışında"
      },
      "oneri": {
        "en": "the pattern still sews without it; the closest drawable details live on the spec screen (Edge/Panel/Stitch primitives, contract/primitives-v1.json)",
        "tr": "kalıp onsuz da dikiliyor; en yakın çizilebilir detaylar spec ekranındaki eksenlerde (Edge/Panel/Stitch primitifleri, contract/primitives-v1.json)"
      }
    }
  }
};

// F7-edit: edit-locality contract (embedded from contract/edit-locality-v1.json)
// — zones + untouchable panel patterns + field->zone map, so the create screen
// runs the SAME locality judgement the gate (edit_locality_check.mjs) runs.
export const EDIT_LOCALITY = {
  "zones": {
    "neckZone": {
      "ne": "yaka oyuğu, yaka parçası, ön/arka boyun bitişi",
      "untouchable": [
        "^Skirt",
        "Sleeve",
        "Cuff",
        "Pocket",
        "Peplum",
        "Hem Flounce",
        "Ruffle strip"
      ]
    },
    "shoulderZone": {
      "ne": "omuz dikişi, omuz noktası, askı",
      "untouchable": [
        "^Skirt",
        "Cuff",
        "Pocket",
        "Peplum",
        "Hem Flounce"
      ]
    },
    "sleeveZone": {
      "ne": "kol, kol kapağı, manşet",
      "untouchable": [
        "^Skirt",
        "^Bodice",
        "^Top ",
        "Collar",
        "Pocket",
        "Peplum",
        "Hem Flounce"
      ]
    },
    "waistZone": {
      "ne": "bel dikişi, kemer, bele takılan parça",
      "untouchable": [
        "Sleeve",
        "Cuff",
        "Collar",
        "Bias binding",
        "Neck Facing"
      ]
    },
    "hemZone": {
      "ne": "etek ucu, boy, yırtmaç, volan",
      "untouchable": [
        "^Bodice",
        "^Top ",
        "Sleeve",
        "Cuff",
        "Collar",
        "Bias binding",
        "Neck Facing",
        "Yoke"
      ]
    },
    "cfZone": {
      "ne": "ön orta: pat, düğme, kuşgözü, ön bağ, keyhole",
      "untouchable": [
        "Back",
        "Sleeve",
        "Cuff",
        "Collar"
      ]
    },
    "backZone": {
      "ne": "arka: sırt oyuğu, bağcık, arka fermuar, arka detay",
      "untouchable": [
        "^(Bodice|Top) (Center |Side )?Front",
        "Front Body",
        "Sleeve",
        "Cuff"
      ],
      "_f5_gerekce": "F5-parca (2026-09-02): eski liste 'Front' kalibiyla ETEK panellerini de koruyordu. Etek arka fermuara BAGLIDIR: gorunmez CB fermuar govdeden etege devam eder (garment.cpp), ve sirti acan her ozellik (bagcik, sirt oyugu, arka bag) fermuari dusurur — fermuarsiz etek tek kalip 'Skirt Front & Back' olarak birlesir (gecis kurali, contract/parca-gecis-v1.json). Yani bir SIRT editi etegin parca yapisini MESRU olarak degistirir; onu dokunulmaz ilan etmek dogru davranisi yasaklamakti. Govde on panelleri + kol + manset dokunulmaz kalir."
    },
    "sideSeamZone": {
      "ne": "yan dikiş (in-seam cep)",
      "untouchable": [
        "Collar",
        "Sleeve",
        "Cuff",
        "Peplum",
        "Bias binding"
      ]
    },
    "surface": {
      "ne": "panel yüzeyi (yama cep)",
      "untouchable": [
        "Collar",
        "Sleeve",
        "Cuff",
        "Bias binding",
        "Neck Facing"
      ]
    },
    "global": {
      "ne": "giysinin tamamını yeniden kuran alan (garment, shaping, fabric) — LOKALLİK İDDİASI YOK",
      "untouchable": []
    }
  },
  "fieldZones": {
    "shoulderStyle": [
      "shoulderZone"
    ],
    "keyhole": [
      "cfZone"
    ],
    "placketStyle": [
      "cfZone"
    ],
    "frontPlacket": [
      "cfZone"
    ],
    "tieClosure": [
      "cfZone",
      "backZone",
      "waistZone"
    ],
    "collarType": [
      "neckZone"
    ],
    "collarEdge": [
      "neckZone"
    ],
    "gatherType": [
      "neckZone"
    ],
    "gatherZone": [
      "neckZone"
    ],
    "backOpening": [
      "backZone"
    ],
    "laceUpBack": [
      "backZone"
    ],
    "backSlit": [
      "backZone",
      "hemZone"
    ],
    "ruffledStraps": [
      "shoulderZone"
    ],
    "peplum": [
      "waistZone"
    ],
    "pocketStyle": [
      "surface",
      "sideSeamZone"
    ],
    "cuffStyle": [
      "sleeveZone"
    ],
    "hemShape": [
      "hemZone"
    ],
    "ruffle": [
      "hemZone"
    ],
    "hemFlounce": [
      "hemZone"
    ],
    "bardotStyle": [
      "shoulderZone",
      "neckZone"
    ],
    "buttonRow": [
      "cfZone"
    ],
    "exposedZip": [
      "cfZone",
      "backZone"
    ],
    "backDetail": [
      "backZone"
    ],
    "sleeveCap": [
      "sleeveZone",
      "shoulderZone"
    ],
    "edgeFinish": [
      "neckZone"
    ],
    "wrapFront": [
      "cfZone"
    ],
    "boxPleat": [
      "cfZone"
    ],
    "yoke": [
      "shoulderZone",
      "neckZone"
    ],
    "cupSeam": [
      "neckZone",
      "cfZone"
    ],
    "neckline": [
      "neckZone",
      "shoulderZone"
    ],
    "sleeveStyle": [
      "sleeveZone",
      "shoulderZone"
    ],
    "sleeveLength": [
      "sleeveZone"
    ],
    "skirtStyle": [
      "hemZone",
      "waistZone"
    ],
    "skirtLength": [
      "hemZone"
    ],
    "skirtLengthMM": [
      "hemZone"
    ],
    "topLength": [
      "hemZone"
    ],
    "waistline": [
      "waistZone"
    ],
    "garment": [
      "global"
    ],
    "shaping": [
      "global"
    ],
    "fabric": [
      "global"
    ],
    "photoFabric": [
      "global"
    ],
    "editExtendMM": [
      "hemZone"
    ],
    "editShortenMM": [
      "hemZone"
    ],
    "editSleeveExtendMM": [
      "sleeveZone"
    ],
    "editNeckDeepenMM": [
      "neckZone"
    ],
    "editAttach": [
      "hemZone"
    ]
  }
};

// M3-primitif: KATMAN 3 -> KATMAN 1 cozumu. Bir sozluk-disi kelime bir eksene
// eslendiginde cevap bir EKSEN ADI degil, bir PRIMITIF DEMETI olsun diye burada.
// Kaynak contract/vocab-resolution-v1.json; kopya degil, uretim.
export const PRIMITIF_COZUM = {
  "gatherType.shirred": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.gather",
        "params": {
          "edge": "zoneEdge",
          "ratio": 1.9,
          "mode": "shirred"
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "zoneEdge"
          ],
          "cutCount": 1
        }
      }
    ],
    "note": "Ayni ratio, elastik dikisle sabitlenmis."
  },
  "collarType.peterPan": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "neckEdgeCopy",
            "outerEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "neckEdge",
          "panel": "collar",
          "position": "neck",
          "standHeightMM": 3,
          "ratio": 1
        }
      }
    ],
    "note": "flat ile arasindaki fark 3mm stand + kenar profili (round)."
  },
  "backOpening.round": {
    "status": "resolved",
    "bundle": [
      {
        "op": "edge",
        "params": {
          "kind": "curve",
          "label": "backCutout"
        }
      },
      {
        "op": "edge",
        "params": {
          "label": "backCutout",
          "subdivideLen": [
            0.3
          ]
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "backCutout"
          ],
          "cutCount": 1
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "backCutout",
          "panel": "facing",
          "position": "centerBack"
        }
      }
    ],
    "note": "Arka panelde IC KESIM (ASTM katman 11) + derinlik orani."
  },
  "laceUpBack.corset": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.extend",
        "params": {
          "edge": "centerBackEdge",
          "direction": "in",
          "deltaMM": -45
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "cbFacing"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "centerBackEdge",
          "panel": "cbFacing",
          "position": "centerBack"
        }
      },
      {
        "op": "seam",
        "params": {
          "a": [
            "cbLeft"
          ],
          "b": [
            "cbRight"
          ],
          "ratio": 1,
          "notchFractions": [
            0.1,
            0.3,
            0.5,
            0.7,
            0.9
          ]
        }
      }
    ],
    "note": "Bagcik = iki kenar arasinda ACIK bir seam + notchFractions'a oturan kopcalar."
  },
  "wrapFront.surplice": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.extend",
        "params": {
          "edge": "centerFrontEdge",
          "direction": "out",
          "deltaMM": 160
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "wrapEdge"
          ],
          "cutCount": 2,
          "mirrorAxis": "y"
        }
      }
    ],
    "note": "CF kenari merkezin OTESINE uzatilir, panel aynali 2 kesilir. Kruvaze bir isim degil, bir uzatma. F5-parca gecis kurali: wrap bir giydirme acikligidir, referans elbisenin gizli CB fermuari duser ve fermuarsiz etek tek kaliba birlesir ('Skirt Front & Back') — parca listesi degisir, olculen etki newPanel."
  },
  "backSlit.slit": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.split",
        "params": {
          "panel": "back",
          "axis": "vertical"
        }
      },
      {
        "op": "seam",
        "params": {
          "a": [
            "cbLeft"
          ],
          "b": [
            "cbRight"
          ],
          "ratio": 1,
          "sewnToFraction": 0.6
        }
      }
    ],
    "note": "vent ile AYNI operator, tek fark seam.sewnToFraction. Ara degerler gecerli. ⭐ K41 / F5-D IS 0b: kesir op.split.atFraction'dan TASINDI."
  },
  "ruffledStraps.ruffled": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "strapEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "shoulderEdge",
          "panel": "strap",
          "position": "shoulder",
          "ratio": 2.2
        }
      },
      {
        "op": "op.extend",
        "params": {
          "edge": "strapEdge",
          "direction": "out",
          "deltaMM": 45
        }
      }
    ],
    "note": "Aski = panel + genislik + ratio. Uc isim, iki sayi."
  },
  "ruffledStraps.spaghetti": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "strapEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "shoulderEdge",
          "panel": "strap",
          "position": "shoulder",
          "ratio": 1
        }
      },
      {
        "op": "op.extend",
        "params": {
          "edge": "strapEdge",
          "direction": "out",
          "deltaMM": 10
        }
      }
    ],
    "note": "Ayni panel, genislik kucuk."
  },
  "ruffledStraps.wide": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "strapEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "shoulderEdge",
          "panel": "strap",
          "position": "shoulder",
          "ratio": 1
        }
      },
      {
        "op": "op.extend",
        "params": {
          "edge": "strapEdge",
          "direction": "out",
          "deltaMM": 60
        }
      }
    ],
    "note": "Ayni panel, ratio 1.0 (duz), genislik buyuk."
  },
  "peplum.full": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "peplumInner",
            "peplumOuter"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.flare",
        "params": {
          "edge": "peplumInner",
          "sweepDeg": 360,
          "hemFactor": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "waistRing",
          "panel": "peplum",
          "position": "waist"
        }
      }
    ],
    "note": "Peplum = bel Interface'inden asilan flare paneli; sweep acisi."
  },
  "hemFlounce.gathered": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "flounceEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.gather",
        "params": {
          "edge": "flounceEdge",
          "ratio": 2,
          "mode": "free"
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "hem",
          "panel": "flounce",
          "position": "hem",
          "ratio": 2
        }
      }
    ],
    "note": "Etek ucu volani: peplum ile AYNI iki primitif, farkli host kenar (hem vs waist)."
  },
  "pocketStyle.patch": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "pocketEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "frontPanelEdge",
          "panel": "pocket",
          "position": "centerFront"
        }
      }
    ],
    "note": "Ustten dikilen panel."
  },
  "cuffStyle.button": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "cuffEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "wristEdge",
          "panel": "cuff",
          "position": "wrist",
          "ratio": 1.15
        }
      },
      {
        "op": "op.gather",
        "params": {
          "edge": "wristEdge",
          "ratio": 1.15,
          "mode": "free"
        }
      }
    ],
    "note": "Manset = bant paneli + toplama orani."
  },
  "hemShape.shirttail": {
    "status": "resolved",
    "bundle": [
      {
        "op": "edge",
        "params": {
          "kind": "curve",
          "label": "hem"
        }
      },
      {
        "op": "op.extend",
        "params": {
          "edge": "hem",
          "fromLandmark": "hem",
          "direction": "up",
          "deltaMM": 45
        }
      }
    ],
    "note": "Yan uc yukari kalkiyor: tek sayi (yan yukselme mm)."
  },
  "placketStyle.asymmetric": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.extend",
        "params": {
          "edge": "centerFrontEdge",
          "direction": "out",
          "deltaMM": 32
        }
      },
      {
        "op": "edge",
        "params": {
          "kind": "line",
          "label": "foldLine"
        }
      },
      {
        "op": "op.extend",
        "params": {
          "edge": "centerFrontEdge",
          "direction": "in",
          "deltaMM": -45
        }
      }
    ],
    "note": "Ayni uzatma, merkezden kaydirilmis. Kayma miktari surekli bir sayi."
  },
  "buttonRow.decorative": {
    "status": "resolved",
    "bundle": [
      {
        "op": "edge",
        "params": {
          "label": "centerFrontEdge",
          "subdivideLen": [
            0.1,
            0.3,
            0.5,
            0.7,
            0.9
          ]
        }
      }
    ],
    "note": "Ayni kesir dizisi, uzatma YOK. Tek fark bir primitifin varligi."
  },
  "backDetail.cape": {
    "status": "resolved",
    "bundle": [
      {
        "op": "panel",
        "params": {
          "edges": [
            "detailEdge"
          ],
          "cutCount": 1
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "backNeckEdge",
          "panel": "backDetail",
          "position": "neck",
          "ratio": 1
        }
      },
      {
        "op": "op.flare",
        "params": {
          "edge": "detailEdge",
          "sweepDeg": 90,
          "hemFactor": 1.25
        }
      }
    ],
    "note": "Ayni asma, ratio 1 ve sweep buyuk."
  },
  "exposedZip.centerBack": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.split",
        "params": {
          "panel": "back",
          "atFraction": 0,
          "axis": "vertical"
        }
      },
      {
        "op": "seam",
        "params": {
          "a": [
            "cbLeft"
          ],
          "b": [
            "cbRight"
          ],
          "ratio": 1,
          "easeMM": 0
        }
      }
    ],
    "note": "Ayni demet, baska landmark. F5-parca gecis kurali: gizli CB fermuar duser, etek tek kaliba birlesir — olculen etki newPanel."
  },
  "bardotStyle.plain": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.extend",
        "params": {
          "edge": "neckEdge",
          "fromLandmark": "shoulder",
          "direction": "down",
          "deltaMM": 70
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "casingEdge"
          ],
          "cutCount": 1
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "neckEdge",
          "panel": "casing",
          "position": "neck",
          "ratio": 1
        }
      }
    ],
    "note": "Ust kenarin omzun ALTINA indirilmesi (tek sayi) + lastik kasnak."
  },
  "cupSeam.horizontal": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.split",
        "params": {
          "panel": "frontPrincess",
          "atFraction": 0.5,
          "axis": "horizontal",
          "seamRatio": 1
        }
      },
      {
        "op": "seam",
        "params": {
          "a": [
            "upperCup"
          ],
          "b": [
            "lowerCup"
          ],
          "ratio": 1,
          "notchFractions": [
            0.5
          ]
        }
      }
    ],
    "note": "Kup dikisi = on panelin gogus apex'inden YATAY bolunmesi."
  },
  "yoke.plain": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.split",
        "params": {
          "panel": "bodice",
          "atFraction": 0.22,
          "axis": "horizontal",
          "seamRatio": 1
        }
      },
      {
        "op": "seam",
        "params": {
          "a": [
            "yokeLower"
          ],
          "b": [
            "bodyUpper"
          ],
          "ratio": 1
        }
      }
    ],
    "note": "Roba = govdenin gogus ustunden YATAY bolunmesi. atFraction surekli."
  },
  "boxPleat.centerInverted": {
    "status": "resolved",
    "bundle": [
      {
        "op": "op.extend",
        "params": {
          "edge": "centerFrontEdge",
          "direction": "out",
          "deltaMM": 60
        }
      },
      {
        "op": "op.gather",
        "params": {
          "edge": "centerFrontEdge",
          "ratio": 1,
          "mode": "free"
        }
      },
      {
        "op": "edge",
        "params": {
          "kind": "line",
          "label": "pleatFoldLine"
        }
      }
    ],
    "note": "LOKAL fazlalik: dagitilmis gather'in tek noktaya toplanmis hali."
  },
  "tieClosure.backWaistBow": {
    "status": "absent",
    "bundle": [],
    "note": ""
  },
  "neckline.cowl": {
    "status": "resolved",
    "bundle": [
      {
        "op": "edge",
        "params": {
          "kind": "curve",
          "label": "neckEdge"
        }
      },
      {
        "op": "edge",
        "params": {
          "label": "neckEdge",
          "subdivideLen": [
            0.24
          ]
        }
      },
      {
        "op": "op.gather",
        "params": {
          "edge": "neckEdge",
          "ratio": 1.45,
          "mode": "free"
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "neckEdge"
          ],
          "grainAngleDeg": 45,
          "cutCount": 1
        }
      }
    ],
    "note": "Boyun kenarinda ratio>1 (dokme kivrim) + 45 derece grain."
  },
  "neckline.pussyBow": {
    "status": "resolved",
    "bundle": [
      {
        "op": "edge",
        "params": {
          "kind": "curve",
          "label": "neckEdge"
        }
      },
      {
        "op": "edge",
        "params": {
          "label": "neckEdge",
          "subdivideLen": [
            0.1
          ]
        }
      },
      {
        "op": "panel",
        "params": {
          "edges": [
            "tieEdge"
          ],
          "cutCount": 2
        }
      },
      {
        "op": "op.attach",
        "params": {
          "hostEdge": "neckEdge",
          "panel": "bowTie",
          "position": "neck"
        }
      }
    ],
    "note": "crew kenari + ayri bag paneli (op.attach). Yaka degil, ASILAN parca."
  }
};
