// GENERATED by engine/tools/gen-flat-tables.mjs — DO NOT EDIT.
// The five contract tables web/lib/flat-core.js reads, so the flat pen runs
// in a browser (no node:fs). Gate: ctest -R flat_tables_check.
// Sources:
//   contract/flat-convention-v1.json
//   contract/garment-spec-v2.json
//   engine/vocab.json
//   contract/spec-grammar.json
//   contract/spec-v1-v2-map.json

export const LAW = {
  "_contract": "FLAT KONVANSIYONU v1 (F-D, 2026-08-23). Damla: 'flatlerin hepsi ayni convention'da degil, hepsinin AYNI MODELDEN CIKMA gibi olmasi lazim' + 'flat tarz sorunu degil, CS hesap ve matematik isidir'. Bu dosya flat cizim kanununun TEK kaynagi. Kapi: engine/tests/flat_convention_check.mjs. Uretim kalemi: engine/tools/render-garment-flat.mjs. DEGERLERI BURADAN OKUR, kendi kopyasini tutmaz.",
  "version": 1,
  "scale": {
    "_law": "Her flat SVG kokunde data-scale + data-unit-mm beyan eder. unitMM = bir SVG kullanici biriminin temsil ettigi GERCEK giysi milimetresi. Kagit uzerinde 1 kullanici birimi = 1 mm kabul edilir, dolayisiyla data-scale = 1:unitMM.",
    "unitMM": 3,
    "declared": "1:3",
    "_why_3": "unitMM, asagidaki KAYNAKLI cevre capalarindan cozuldu (uydurulmadi): duz serilmis kapali bir tup icin yari-genislik = cevre/4 (geometri zorunlulugu, turetmesi: tup duz serilince iki kat olur, gorunen genislik = cevre/2, yari-genislik = cevre/4). EU38 bust 88.0 cm -> 220 mm yari-genislik. Croquis gogus yari-genisligi 73.333 birim -> 220/73.333 = 3.0 mm/birim. Ayni unitMM bel capasini da tutturur: EU38 bel 70.0 cm -> 175 mm; croquis bel yari-genisligi 58.333 birim x 3.0 = 175.0 mm. Iki bagimsiz capa ayni sayiyi veriyor."
  },
  "referenceBody": {
    "_law": "Flat MANKENE gore cizilir, kalip INSANA gore (Damla, SSB-10). Bugun elimizde YAYINLANMIS bir manken cizelgesi YOK; uydurmak yasak. Bu yuzden croquis capalari bugun contract/tables.json draft.euSizeChart EU38'in KAYNAKLI uc kolonuna (bustCM/waistCM/hipCM, burda style Damen Masstabellen, status=verified) bagli. MANKEN-INSAN AYRIMI ACIK KALEM: kaynakli bir manken cizelgesi gelene kadar croquis insan blokunun uzerinde duruyor ve bu ACIKCA beyan ediliyor, gizlenmiyor.",
    "size": "EU38",
    "chartPath": "contract/tables.json -> draft.euSizeChart.EU38",
    "fields": {
      "bustCM": 88,
      "waistCM": 70,
      "hipCM": 94
    },
    "sourceStatus": "verified (burda style, Damen Masstabellen, Koergroesse 168)",
    "openItem": "manken cizelgesi (gercek kadindan ince) — KAYNAK YOK, Damla karari bekliyor"
  },
  "croquis": {
    "_law": "TEK CROQUIS. Butun flat'ler bu tek isaret kumesinden cikar. Bir stilin YAKASI/KOLU/ETEGI degisir; omuz ucu, gogus (koltukalti) hatti ve bel hatti YUKSEKLIGI DEGISMEZ. Kapi bu isaretleri her flat'ten olcup +-2 mm icinde ayni olduklarini dogrular.",
    "id": "eu38-flat-v1",
    "toleranceMM": 2,
    "units": "SVG kullanici birimi; x=0 on-orta (CF), y=0 omuz cizgisi, +y asagi",
    "landmarks": {
      "shoulderTipX": {
        "u": 70.1799,
        "mm": 210.54,
        "derivation": "chestX 73.3333u x sideSeamProfile._normalizedToChest.shoulder 0.9570 = 70.1799u = 210.54 mm yari-omuz (omuzdan omuza 421.1 mm).",
        "source": "OLCULDU — satin alinmis Bugra Locket EU38 'Back Body' parcasinda omuz/gogus yari-genislik orani 196.13/204.94 = 0.9570. Olcum: GECE/log/F-E.bugra-olcum.txt. Bugra sayisi yalnizca BUYUKLUGU besliyor; SARTIN kendisi geometrik yasadir (set-in kollu giyside omuz ucu gogus hattinin disinda olamaz), 'Bugra'ya benzerlik' bir esik DEGILDIR.",
        "_previous": {
          "u": 78,
          "mm": 234,
          "source": "ACIK — kaynaksiz, eski kalemden devralindi. Kapi yalnizca STILLER ARASI AYNILIGINI zorluyordu, dis bir yayina esitligini DEGIL."
        },
        "_V4_A_NEDEN_DEGISTI": "24 Agu (V4-A): F-E'de olculup dogru bulunan duzeltme UYGULANDI. Eski 78.0u = 234 mm yari-omuz iken ayni croquis'in gogus yari-genisligi 73.3333u = 220 mm idi; oran 1.0636, yani omuz ucu BUSTUN DISINDAYDI. Set-in kollu bir giyside bu geometrik olarak imkansizdir: kol oyugu omuz ucundan asagi iner ve kol oyugu egrisi omuz ucu ile koltukaltini paylasir (sleeveLaw.sleeveSharesArmholeEndpoints); omuz ucu bustun disinda olursa omuz bir raf gibi durur. Damla'nin 5. kusuru ('boyun cok genis, omuz cok dar') bunun gorunen yuzuydu.",
        "_V4_A_ENGEL_NASIL_KALKTI": "F-E'de duzeltme uygulanamamisti cunku engine/tests/flat_convention_check.mjs'nin measureCroquis() cikarimi omuz ucunu 'x'in ilk yerel maksimumu' diye buluyordu; o sezgi yalnizca omuz gogusten GENISSE calisir, yani kapi duzeltmeye calistigi kusuru VARSAYIYORDU. V4-A once cikarimi KOKTEN degistirdi (omuz ucu = sig+disa giden omuz kirisi ile dik inen kol oyugu kirisinin bulustugu kose; omuz-gogus oranindan bagimsiz), iki croquis'te de dogru buldugu KANITLANDI (GECE/log/V4-A.inference.txt), sonra bu deger degistirildi.",
        "_F_E_OLCULDU_AMA_DEGISTIRILMEDI": "23 Agu (F-E): bu deger OLCULEREK YANLIS bulundu ama BU GECE DEGISTIRILMEDI, gerekcesi asagida. Yanlisligi: 78.0u = 234 mm yari-omuz = 468 mm omuzdan omuza; ayni croquis'in gogus yari-genisligi 73.3333u = 220 mm. Yani omuz ucu BUSTUN DISINDA (oran 1.0636). Set-in kollu hicbir giyside omuz noktasi gogus cizgisinin disinda olamaz — kol oyugu omuzdan asagi ve ICERI iner; disarida olursa omuz bir raf gibi durur. SATIN ALINMIS Bugra Locket EU38 Arka Beden parcasinda olculen oran 196.13/204.94 = 0.9570 (bkz. sideSeamProfile), yani DOGRU deger 73.3333 x 0.9570 = 70.1799u (210.54 mm) ve tureyen shoulderTipY 16.8576u. Damla'nin 5. kusuru ('boyun cok genis, omuz cok dar') bunun gorunen yuzu.",
        "_NEDEN_DEGISTIRILMEDI": "Degisiklik denendi ve ISE YARADI (flat_geometry_sellable_check S1 yesile dondu), AMA mevcut engine/tests/flat_convention_check.mjs'yi KIRDI: o kapinin measureCroquis() cikarimi omuz ucunu 'CF yakadan asagi yurunurken x'in ILK YEREL MAKSIMUMU' diye buluyor. Bu sezgi sadece omuz gogusten GENISSE dogrudur — yani kapi, duzeltmeye calistigimiz kusurun kendisini varsayiyor. Omuz iceri alininca yerel maksimum kalmiyor, cikarim koltukaltini omuz sanip 27.00 mm / 153.00 mm / 750.00 mm sapma basiyor. Duzeltmek MEVCUT BIR TESTIN cikarimini degistirmeyi gerektiriyor; GECE/KART/ORTAK.md md.5 'Var olan teste dokunma' diyor. Esik gevsetilmedi, kapi susturulmadi, karar Damla'ya birakildi: DAMLA-KUYRUK.md K-FE-1."
      },
      "shoulderTipY": {
        "u": 16.8576,
        "mm": 50.57,
        "derivation": "neckDrop 4.0 + (shoulderTipX 70.1799 - neckBase 30.0) x omuz egimi 0.32 = 4.0 + 12.8576 = 16.8576. ONCEDEN yakanin genisligine (nHalf) bagliydi -> her yakada baska yukseklik; croquis olamaz. Artik yakadan BAGIMSIZ.",
        "source": "ACIK — egim 0.32 kaynaksiz, stiller arasi ayniligi zorunlu; buyukluk shoulderTipX'ten TURER",
        "_previous": {
          "u": 19.36,
          "mm": 58.08,
          "derivation": "neckDrop 4.0 + (shoulderTipX 78.0 - neckBase 30.0) x 0.32"
        },
        "_V4_A_NEDEN_DEGISTI": "Bagimsiz bir sayi degil, shoulderTipX'in turevi. shoulderTipX 78.0 -> 70.1799 degisince ayni formulden 19.36 -> 16.8576 duser."
      },
      "chestX": {
        "u": 73.3333,
        "mm": 220,
        "derivation": "bustCM 88.0 -> 880 mm; duz serili tup yari-genisligi = 880/4 = 220 mm; 220 / unitMM 3.0",
        "source": "burda EU38 bustCM (verified) + tup geometrisi"
      },
      "chestY": {
        "u": 92,
        "mm": 276,
        "source": "ACIK — koltukalti derinligi kaynaksiz devralindi. NOT: Aldrich p.11 armscye DEPTH 21.0 cm NAPE'ten olculur, omuz cizgisinden degil; dogrudan capa olarak KULLANILMADI (yanlis temel olurdu)."
      },
      "waistY": {
        "u": 150,
        "mm": 450,
        "source": "ACIK — kaynaksiz. draft.euSizeChart.backLengthCM KAYNAKSIZ kolon (K10), bilerek capa yapilmadi."
      },
      "waistX": {
        "u": 58.3333,
        "mm": 175,
        "derivation": "waistCM 70.0 -> 700 mm; 700/4 = 175 mm; 175 / unitMM 3.0. Sadece vucuda oturan (fitted/princess/darts/empire) govdede siluet bu genislige iner; salkim (shift) govde daha genis kalir — bu GIYSI ozelligi, croquis degil.",
        "source": "burda EU38 waistCM (verified) + tup geometrisi"
      },
      "hipX": {
        "u": 78.3333,
        "mm": 235,
        "derivation": "hipCM 94.0 -> 940 mm; 940/4 = 235 mm; 235 / unitMM 3.0",
        "source": "burda EU38 hipCM (verified) + tup geometrisi"
      },
      "neckBase": {
        "u": 30,
        "mm": 90,
        "source": "ACIK — kaynaksiz devralindi"
      },
      "neckDrop": {
        "u": 4,
        "mm": 12,
        "source": "ACIK — kaynaksiz devralindi"
      },
      "shoulderSlope": {
        "value": 0.32,
        "unit": "dy/dx",
        "source": "ACIK — kaynaksiz devralindi"
      }
    },
    "sideSeamProfile": {
      "_law": "YAN DIKIS SEKIL KANUNU (F-E, 2026-08-23). Bir flat'in 'giysi' okunmasini saglayan sey mutlak genislikler degil, yan dikisin OMUZ -> GOGUS -> BEL -> ETEK boyunca izledigi ORAN dizisidir. Bu dizi bizim ciktimizdan TURETILEMEZ (dairesel olurdu); SATIN ALINMIS Bugra Locket EU38 kalibindan OLCULDU.",
      "_source": "patterns_real/geometry/geometry-full.json -> rings[pattern=locket_top, piece='Back Body', sizeGuess='38']. Arka beden secildi cunku ARKA ORTA kenari tam dikey (90.00 deg, 413.97 mm duz kosu) ve on bedenin aksine pens/placket parcanin dis konturunu kirletmiyor. Olcum: GECE/log/F-E.bugra-olcum.txt. Yari-genislikler arka-ortadan.",
      "_measuredMM": {
        "shoulder": 196.13,
        "chestMax": 204.94,
        "waistMin": 157.46,
        "hem": 179.22,
        "shoulderToHem": 413.97,
        "waistBelowShoulder": 289.8
      },
      "_normalizedToChest": {
        "shoulder": 0.957,
        "chest": 1,
        "waist": 0.7683,
        "hem": 0.8745
      },
      "shoulder": 0.957,
      "hemRisePerU": 0.1881,
      "_hemRiseDerivation": "Belden asagi inen govde yan dikisi yeniden ACILIR (bel en dar yer, etek kalcaya dogru genisler). Bugra'da bel 0.7683 -> etek 0.8745, arada 124.17 mm = 41.39 birim dusus. Egim = (0.8745 - 0.7683) x chestX 73.3333 / 41.39 = 0.1881 birim/birim. Ust etek yari-genisligi artik SABIT kalca genisligi degil, bu egimle bel genisliginden turuyor; tavan hipX x 0.98.",
      "_whyItMatters": "ESKI KALEM her ust icin hemHalf = hipX x 0.98 = 76.75u yaziyordu, yani etek gogusten GENIS (76.75 > 73.3333, oran 1.047). Bugra'da oran 0.8745 — etek gogusten DAR. Damla'nin '3. bel yok' ve '4. etek ucu kavisi abartili' kusurlarinin TEK kok sebebi buydu: bel dogru daralıyordu ama hemen ardindan kalca genisligine acildigi icin bel okunmuyor, ve crop boyda o acilma 72 mm'ye sıkısıp bir can/kase kavisi uretiyordu."
    },
    "sleeveLaw": {
      "_law": "KOL KANUNU (F-E, 2026-08-23). Uc sart, ucu de ESITSIZLIK/OZDESLIK — disaridan sayi gerekmez, o yuzden gevsetilemez de.",
      "armholeNeverBulgesOutward": true,
      "_a1": "Kol oyugu ICBUKEYDIR: egrinin hicbir noktasi kendi IKI UCUNUN disina tasamaz, yani max x <= max(shoulderTipX, chestX). Eski kalem ikinci kontrol noktasini underX + 12 = 85.33u koyuyordu; egri 80.4u'ya kadar sisip her iki ucunu da (omuz ucu 78u, koltukalti 73.33u) asiyordu — govde konturu kolun icinden disari sizip ikinci bir cizgi gibi okunuyordu. Kolun gövdeye degmedigi hissi tam olarak buydu. Damla'nin '1. kollar govdeden KOPUK' kusuru.",
      "sleeveSharesArmholeEndpoints": true,
      "_a2": "Kol path'i govde silueti ile IKI ucu da paylasmak zorunda: omuz ucu (shoulderTipX, shoulderTipY) ve koltukalti (chestX, chestY). Aradaki bosluk 0 mm.",
      "puffHemNarrowerThanWidest": true,
      "puffHemOverWidestMax": 0.9327,
      "_puffRatioSource": "Bugra Locket EU38 ALT KOL parcasi, kendi min-alan donuk kutusunda olculdu: en genis 342.22 mm, dis ucu 319.20 mm -> 0.9327. Olcum: GECE/log/F-E.bugra-olcum.txt. Bu KASITLI OLARAK MUHAFAZAKAR bir tavandir: alt kol, puff'in ICINDEKI duz katmandir ve eti neredeyse hic toplanmaz; gorunen puff (Ust Kol) ondan cok daha fazla toplanir (kapak buzgu orani 1.549x). Yani gercek bir puff bu tavanin ALTINDA kalir; tavan sadece 'boru cizip puff demeyi' yasaklar. Salt esitsizlik (< 1.0) yetmiyordu: olculdu, 0.9889'luk bir boru ondan geciyordu (GECE/log/F-E.mutasyon.txt, MUTASYON C).",
      "_a3": "PUFF kolun et (hem) yari-genisligi, kolun EN GENIS yari-genisliginden KUCUK olmak zorunda. 'Puff' tanimi budur: dolgunluk yukarida, et toplanmis. Esitlik (duz kesik boru) = puff degil. Damla'nin '2. puff kol alttan duz kesik ve sivriliyor' kusuru. Bugra Locket'te de olculuyor: Alt Kol parcasi kendi ekseninde en genis 342.22 mm, dis ucu 319.20 mm (oran 0.933) — yani gercek kalipta bile et en genis yerden DAR."
    },
    "easeNote": "Croquis BEDEN CIZGISIDIR (sifir bolluk). Giysi bollugu bugun flat siluetine EKLENMIYOR — yani flat, giysiyi vucut cizgisinde gosteriyor. ACIK KALEM: bolluk ekseni (FreeSewing seatEase/sleeveEase gibi bolge-bazli) F-H'nin isi."
  },
  "ink": {
    "_law": "TEK MUREKKEP RENGI. Hiyerarsi RENKLE degil AGIRLIK ve KESIKLE kurulur — teknik flat kanunu budur. Ikinci bir renk (eski #5c7aa0 seam mavisi) hiyerarsiyi renge kacirmakti; kaldirildi.",
    "color": "#1f3a5f",
    "paper": "#ffffff"
  },
  "lineClasses": {
    "_law": "Her cizili elemanin (stroke-width, stroke-dasharray) cifti bu tablodan BIR sinifa esit olmak zorunda. Tablodaki her sinif matriste EN AZ BIR kez kullanilmis olmak zorunda (beyan edilip kullanilmayan sinif = olu beyan).",
    "_source": "Agirliklar contract/gusto-corpus.json line_hierarchy (stroke_layers 3, outline_width 2.0, interior_widths [1.4, 1.0]) — repo icinde donmus, Damla-onayli flat korpusundan olculmus katman yapisi. Kesik/noktali ayrimi teknik cizim (tech-pack) konvansiyonu: gorunen ust dikis kesik, gizli hat noktali.",
    "classes": {
      "outline": {
        "width": 2,
        "dash": null,
        "role": "dis siluet + kol dis konturu"
      },
      "seam": {
        "width": 1.4,
        "dash": null,
        "role": "konstruksiyon dikisi: prenses, pens, bel birlesimi, panel dikisi, yaka"
      },
      "mark": {
        "width": 1,
        "dash": null,
        "role": "yardimci isaret: buton, buzgu tirtigi, fiyonk"
      },
      "topstitch": {
        "width": 1,
        "dash": "4 3",
        "role": "gorunen ust dikis: etek ucu, fermuar hatti"
      },
      "hidden": {
        "width": 1,
        "dash": "1 3",
        "role": "gizli/arkada kalan hat: sirt acikligi kenari, alt bindirme"
      }
    },
    "ratios": {
      "outline:seam": 1.4286,
      "seam:mark": 1.4,
      "outline:mark": 2
    }
  },
  "fillLaw": {
    "_law": "Sifir golge, sifir gradyan, sifir tint. Izin verilen fill degerleri SADECE: 'none', kagit beyazi, ve murekkep rengi (taper murekkep degisken-kalinlikli cizgiyi dolu poligon olarak basar — o bir CIZGI, alan degil). Eski #fbfcfe govde tinti bir alan boyamasiydi, kaldirildi.",
    "allowedFills": [
      "none",
      "#fff",
      "#ffffff",
      "#1f3a5f"
    ],
    "forbidden": [
      "linearGradient",
      "radialGradient",
      "pattern",
      "filter",
      "feGaussianBlur",
      "feDropShadow",
      "fill-opacity",
      "stroke-opacity"
    ]
  },
  "views": {
    "_law": "ON + ARKA zorunlu. Her panel <g data-view=\"front|back\"> ile isaretlenir ve croquis isaretlerini data-* olarak beyan eder; kapi bu beyanin GERCEKTEN cizilen path'in bir ucu oldugunu dogrular (beyan yalan soyleyemez).",
    "required": [
      "front",
      "back"
    ]
  }
};

export const SICIL = {
  "_contract": "garment-spec v2 — SEALED 2026-08-17 (H2.1). K1 discipline: this file is the SINGLE SOURCE. contract/garment-spec-v2.schema.json is GENERATED from it by engine/tools/gen-spec-v2.mjs; consumers never copy values out of here by hand, and engine/tools/specv2-check.mjs (ctest: specv2_check) fails if the generated schema drifts, if an operator's engine binding has vanished, or if a declared quantity's default no longer matches engine/src/surfacepattern.hpp. It replaces contract/garment-spec-v2.DRAFT.md (12 Ağu), whose topology/quantity split is kept and whose scope was re-measured against the engine of 17 Ağu.",
  "version": "2.0.0",
  "specVersion": "garment-spec/2",
  "_law": [
    "1. AN LLM WRITES JSON, NEVER CODE. Every topology axis is a CLOSED enum; every quantity is a bounded scalar with a unit. additionalProperties is false everywhere in the generated schema. A field the schema does not declare is a rejection, not a warning.",
    "2. NO SILENT SUBSTITUTION. DERSLER: a quiet enum fallback (puff -> None) is hallucination. If a requested enum value is not in the registry as `shipped`, the spec is REFUSED and the refusal names the operator. Never the nearest neighbour, never a default.",
    "3. THE REGISTRY IS THE SCOPE. `operators` below is the sicil. An enum value declares which operators it requires. A spec is expressible if and only if every operator it requires has status `shipped`. This is the machine side of the bitiş tanımı: 'the remaining two refuse honestly, naming the missing operator'.",
    "4. SOLVER KNOBS ARE NOT SPEC. `solverKnobs` lists the numerical dials of the flattener. They are declared here so nobody re-declares them elsewhere, and they are EXCLUDED from the generated schema — an LLM/VLM that writes arapRounds is writing code, and rule 1 forbids it.",
    "5. NOTHING IS WRITTEN HERE THAT THE ENGINE CANNOT DO. An operator with no engine binding today carries status `absent` and says so in its own line. A field with a fake capability is a painted gate."
  ],
  "_statuses": {
    "shipped": "runs on the DEFAULT path the buyer receives today (surface-pattern with a default-constructed SheathOptions). Binding is a real symbol in engine/src/surfacepattern.hpp.",
    "flagged": "the code exists and is measured, but it is switched OFF in the shipped configuration because turning it on breaks a green gate. A spec requiring it is REFUSED — an unshippable capability is not a capability.",
    "absent": "SİCİLDE YOK. No engine symbol, no derivative, no approximation. A spec requiring it is REFUSED and the refusal names it."
  },
  "_serh": {
    "_role": "ŞERH = sicile düşülen ölçülmüş çelişki notu. Status DEĞİŞTİRMEZ, kapı DEĞİŞTİRMEZ; sicilin hangi motoru anlattığını, artefaktın hangi motoru sevk ettiğini yazar. Bir şerhi silmek, çelişkinin ölçülerek kapandığını göstermeyi gerektirir.",
    "_neden_isaretci": "V7-G (25.08): bu şerhin uzun kanıt düz yazısı (kaynak dosya adları + ham dizgi sayımları) sicilden ÇIKARILDI, çünkü vocab_reference_check ratchet'i o düz yazıyı kapalı bir enuma eklenmiş YENİ referans sayıp kırmızıya düştü ve sözlük hiçbir eksen/değer kazanmadığı için taban yeniden kesilemezdi. Metnin tamamı GECE/V7-F.md §5'te kelimesi kelimesine duruyor. Hiçbir cümle yok olmadı; bu bir yer değiştirmedir.",
    "V7-F-2026-08-24": {
      "başlık": "SİCİL↔ARTEFAKT KAPSAM KAYMASI — sicil bir motoru anlatıyor, sevkiyat başka bir motoru yapıyor",
      "hüküm": "İki cümle de aynı anda doğru: (a) yüzey hattında `sleeve` operatörü YOK (absent, doğru); (b) alıcının indirdiği motor kol çiziyor. Çelişki bir yalan değil, KAPSAM kaymasıdır.",
      "shippedTanımıBugünYanlış": "_statuses.shipped kendini 'alıcının bugün aldığı VARSAYILAN yol' diye tanımlıyor ve o yolu yüzey hattı olarak adlandırıyor; V7-F ölçtü: sevk edilen paketin içinde yüzey hattı YOK, yani bu tanım bugün fiilen YANLIŞTIR.",
      "kanıt": "GECE/V7-F.md — ölçümlerin, dosya adlarının ve ham dizgi sayımlarının tam metni orada.",
      "KARARA BAĞLANMAMIŞ": "Ürünün gerçeği hangi motor? Bu bir Damla kararıdır; V7-F ölçtü, seçmedi."
    }
  },
  "operators": {
    "bodiceSurface": {
      "status": "shipped",
      "tr": "gövde yüzeyi (bel halkasından omuza)",
      "binds": "SheathOptions::skimBodice, SheathOptions::shoulderTop",
      "proof": "surfacepattern.cpp buildSheathPattern; ftorso/btorso panels, 8 sizes"
    },
    "skirtSurface": {
      "status": "shipped",
      "tr": "etek yüzeyi (bel -> basen -> etek ucu)",
      "binds": "SheathOptions::hemDropBelowHipMM",
      "proof": "surfacepattern.cpp panel row {true, hemH, ...}; skirt_front/skirt_back"
    },
    "hemSweepCone": {
      "status": "shipped",
      "tr": "A-line etek açılımı (koni)",
      "binds": "SheathOptions::hemSweepMM",
      "proof": "surfacepattern.cpp:1100 surf.hemScale = hemSweepMM / base; skirt develop-deficit +0.000 deg (it is a cone, it develops exactly)"
    },
    "princessCut": {
      "status": "shipped",
      "tr": "dikey tam kesim (prenses / yan dikiş)",
      "binds": "SheathOptions::bodiceCutFracs, SheathOptions::skirtCutFracs",
      "proof": "surfacepattern.cpp:1133-1134; 8 panels from one waist ring"
    },
    "waistAnchoredDart": {
      "status": "shipped",
      "tr": "bel çapalı pens (yüzeyde yarık)",
      "binds": "SheathOptions::skirtDartFracs, SheathOptions::bodiceApexFrac, SheathOptions::skirtApexFrac",
      "proof": "Slit, waist row anchor; G2: dart angle falls out of develop-deficit, only the total is a law"
    },
    "topAnchoredDart": {
      "status": "shipped",
      "tr": "üst çapalı pens (omuz / yaka pensi)",
      "binds": "SheathOptions::topDartSplitFrac, SheathOptions::topDartApexFrac, SheathOptions::maxDartDeg",
      "proof": "surfacepattern.hpp topDartApexFrac note; Tur 8: the load is now SIGNED, a net-negative band derives NO dart",
      "defect": "on the shipped garment the torso derives top anchors only and, since Tur 8, a net-negative shoulder band derives none at all (STITCHU_SLIT_DEBUG: empty list). The operator exists and runs; it produces nothing on this garment."
    },
    "necklineDraft": {
      "status": "shipped",
      "tr": "yaka açıklığı (Aldrich katsayılarıyla, bedenden türetilir)",
      "binds": "SheathOptions::neckWidthCoefCM, SheathOptions::frontNeckDropCoefCM, SheathOptions::backNeckDropMM",
      "proof": "Aldrich 5th ed. p.16 + GRAFIS + Hofenbitzer, three systems inside 5mm",
      "defect": "ONE top boundary sampled over the whole circle: the front neck cannot be 5mm narrower than the back. Written down in surfacepattern.hpp, not hidden. Expressing it is a change to the law, not a number."
    },
    "armholeNotch": {
      "status": "shipped",
      "tr": "kol oyuğu",
      "binds": "SheathOptions::armhole, SheathOptions::shoulderNarrowMM",
      "proof": "Aldrich close-fitting sleeveless block p.28",
      "defect": "H1.0 K1, MEASURED: the armhole is not a 2D hole but a thin lens in phi in [0, 19.9 deg] — EU38 33.55cm against Buğra Locket-38 43.30cm, 22% short. Shipped and defective, NOT absent."
    },
    "backOpening": {
      "status": "shipped",
      "tr": "arka açıklık (dikilmeyen kenar)",
      "binds": "SheathOptions::backOpeningMM",
      "proof": "surfacepattern.cpp:1665-1682; 558.8mm = 22 inch, the 1960s envelope default. T10: the 'BURAYI DİKMEYİN' warning reaches print-info.pdf s.2 and the pattern itself.",
      "defect": "an UNSEWN SEAM, not a drafted zip. See operator `zipperPiece`."
    },
    "shoulderSeam": {
      "status": "flagged",
      "tr": "omuz dikişi (tüp -> katlanmış crest)",
      "binds": "SheathOptions::shoulderSeam (default false), SheathOptions::shoulderCrestBandMM, SheathOptions::shoulderSeamForwardMM",
      "proof": "Tur 6: ON -> h10_gate_check 52/63 -> 24/63 FAIL, K3 0 -> 30 shoulder stitches 8/8, K5 neck closed 8/8, K6 +2.91mm 8/8",
      "refusalReason": "omuz dikişi bayrak arkasında: açıkken surface_pattern_check 0 -> 4 FAIL (gövde kesim çizgisi %0.4162/%0.2908 iç gerinim %24.07/%18.14, kapı %3.0). Sevk edilen giysi kolsuz ve omuz dikişsizdir.",
      "ring": "H1.0a"
    },
    "gatheredOverlayLayer": {
      "status": "absent",
      "tr": "büzgülü overlay katmanı (ikinci, dış katman)",
      "binds": null,
      "proof": "T14 (17.08): Buğra'nın Upper Sleeve'i aynı kapağın yatayda ölçeklenmiş kopyası — kapak sagitta oranı 8 bedende BİT-SABİT 1.227, kiriş oranı 1.549->1.347 (= büzgü payı). İki KATMAN, yatay bölünme değil; patterns_real/BUGRA-DEFTER.md'nin 'kol yatay 2'ye bölünmüş' satırı bununla çürüdü. Motorda karşılığı: surfacepattern.cpp + .hpp içinde 'gather|pleat|ruffle' geçen SIFIR satır (17.08 ölçüldü).",
      "refusalReason": "büzgülü overlay katmanı operatörü sicilde YOK: motor tek katmanlı bir yüzey kesiyor, bir panelin üstüne büzgüyle oturan ikinci katman üretemez."
    },
    "sleeve": {
      "status": "absent",
      "tr": "kol (ayrı yüzey yaması)",
      "binds": null,
      "proof": "surfacepattern.cpp/.hpp içinde 'sleeve' geçen 6 satırın 6'sı da 'sleeveless' kelimesi, hepsi yorum (17.08 ölçüldü). Kol oyuğu var, kol yok. engine/src/sleeve.cpp ESKİ 2B-formül motoruna aittir (CLAUDE.md: 'AT'), sevk edilen yüzey hattına bağlı değildir.",
      "refusalReason": "kol operatörü sicilde YOK: sevk edilen giysi kolsuzdur ve kol oyuğu bugün gerçek bir 2B delik değil (H1.0b). Kol, omuz dikişi (flagged) açılmadan konulamaz.",
      "blockedBy": "shoulderSeam",
      "blockedByStillValid": "V7-F (24.08) ÖLÇÜLDÜ, GEÇERLİ: shoulderSeam hâlâ `flagged` ve motorun kendi varsayılanı KAPALI. _statuses'a göre flagged bir operatörü isteyen spec REDDEDİLİR, dolayısıyla kol da bugün konulamaz. Gerekçe bayat DEĞİL. Ölçümün tam metni: GECE/V7-F.md §1 (ve §5.2).",
      "serh": "V7-F (24.08) — SİCİL↔ARTEFAKT ÇELİŞKİSİ, KARAR (B): motorun bastığı kol bu operatör DEĞİLDİR. Bu sicilin evreni yalnız yüzey hattıdır ve o kolu basan kod o evrenin dışındadır; çelişki bir yalan değil KAPSAM kaymasıdır (bkz. _serh.V7-F-2026-08-24). Bu satır bir status DEĞİŞTİRMEZ: `sleeve` yüzey hattında absent olmaya devam eder. Ayrıntılı ölçüm: GECE/V7-F.md."
    },
    "collarFamily": {
      "status": "absent",
      "tr": "yaka ailesi (ayrı yaka parçası: peterPan / stand / shirt / notched)",
      "binds": null,
      "proof": "surfacepattern.cpp/.hpp içinde 'collar' geçen SIFIR satır (17.08). contract/spec-grammar.json yalnız ESKİ flat/2B motorun peterPan'ini 'pinli' diye taşır; yüzey hattında karşılığı yok.",
      "refusalReason": "yaka ailesi operatörü sicilde YOK: motor bir yaka AÇIKLIĞI (necklineDraft) keser, boyna oturan ayrı bir yaka parçası üretemez."
    },
    "skirtFamily": {
      "status": "absent",
      "tr": "etek ailesi (gore / fullCircle / gathered / pleated / straight)",
      "binds": null,
      "proof": "yüzey hattının tek etek operatörü hemSweepCone (hemSweepMM ile ölçeklenen koni). 'pleat' geçen SIFIR satır (17.08). contract/spec-grammar.json'un gore/fullCircle/gathered değerleri ESKİ flat/2B motorundandır.",
      "refusalReason": "etek ailesi operatörü sicilde YOK: motorun tek eteği bel halkasından açılan bir konidir (A-line); gore, tam daire, büzgülü ve pileli etekler üretilemez."
    },
    "zipperPiece": {
      "status": "absent",
      "tr": "fermuar (kendi payıyla çizilmiş)",
      "binds": null,
      "proof": "backOpening bir DİKİLMEYEN KENAR üretir; fermuarın kendi payı/parçası çizilmez. web/js/missing.js zaten bunu ESKİ motor için ilan ediyor: 'fermuar kendi payıyla çizili değil, o dikişe fermuarı kendin tak'.",
      "refusalReason": "fermuar operatörü sicilde YOK: motor açıklığı kesip 'burayı dikmeyin' diye işaretler, fermuarı kendi payıyla çizmez."
    }
  },
  "topology": {
    "_role": "AYRIK katman. Her eksen KAPALI enum; her değer gerektirdiği operatörleri `requires` ile ilan eder. Bir değer, gerektirdiği operatörlerden biri `shipped` değilse İFADE EDİLEMEZ ve red o operatörün ADIYLA verilir.",
    "garment": {
      "type": "enum",
      "values": {
        "sheathDress": {
          "requires": [
            "bodiceSurface",
            "skirtSurface",
            "necklineDraft",
            "armholeNotch"
          ]
        },
        "top": {
          "requires": [
            "bodiceSurface",
            "necklineDraft",
            "armholeNotch"
          ]
        },
        "skirt": {
          "requires": [
            "skirtSurface"
          ]
        }
      }
    },
    "skirtShape": {
      "type": "enum",
      "values": {
        "straight": {
          "requires": [
            "skirtSurface"
          ]
        },
        "aLine": {
          "requires": [
            "skirtSurface",
            "hemSweepCone"
          ]
        },
        "gore": {
          "requires": [
            "skirtFamily"
          ]
        },
        "fullCircle": {
          "requires": [
            "skirtFamily"
          ]
        },
        "gathered": {
          "requires": [
            "skirtFamily"
          ]
        },
        "pleated": {
          "requires": [
            "skirtFamily"
          ]
        }
      }
    },
    "shoulder": {
      "type": "enum",
      "values": {
        "strapless": {
          "requires": [
            "bodiceSurface"
          ]
        },
        "shoulderSeam": {
          "requires": [
            "shoulderSeam"
          ]
        }
      }
    },
    "sleeve": {
      "type": "enum",
      "values": {
        "none": {
          "requires": [
            "armholeNotch"
          ]
        },
        "setIn": {
          "requires": [
            "sleeve"
          ]
        },
        "puff": {
          "requires": [
            "sleeve",
            "gatheredOverlayLayer"
          ]
        },
        "cap": {
          "requires": [
            "sleeve"
          ]
        }
      }
    },
    "collar": {
      "type": "enum",
      "values": {
        "none": {
          "requires": []
        },
        "peterPan": {
          "requires": [
            "collarFamily"
          ]
        },
        "stand": {
          "requires": [
            "collarFamily"
          ]
        },
        "shirt": {
          "requires": [
            "collarFamily"
          ]
        }
      }
    },
    "closure": {
      "type": "enum",
      "values": {
        "none": {
          "requires": []
        },
        "backOpening": {
          "requires": [
            "backOpening"
          ]
        },
        "centreBackZip": {
          "requires": [
            "backOpening",
            "zipperPiece"
          ]
        },
        "buttonFront": {
          "requires": [
            "zipperPiece"
          ]
        }
      }
    },
    "suppression": {
      "type": "enum",
      "values": {
        "seamOnly": {
          "requires": [
            "princessCut"
          ]
        },
        "dart": {
          "requires": [
            "princessCut",
            "waistAnchoredDart"
          ]
        },
        "topDart": {
          "requires": [
            "princessCut",
            "topAnchoredDart"
          ]
        },
        "gather": {
          "requires": [
            "gatheredOverlayLayer"
          ]
        },
        "pleat": {
          "requires": [
            "skirtFamily"
          ]
        }
      }
    }
  },
  "quantities": {
    "_role": "SÜREKLİ katman. Her kadran bir SheathOptions alanına bağlı; `default` o alanın engine/src/surfacepattern.hpp'deki bugünkü değeridir ve specv2_check onu başlıktan okuyup karşılaştırır (sürüklenirse KIRMIZI). Sınırlar İLAN EDİLMİŞ tasarım bandıdır, ölçülmüş kanun değil — kaynağı olan `source` taşır.",
    "hemDropBelowHipMM": {
      "binds": "hemDropBelowHipMM",
      "unit": "mm",
      "min": 0,
      "max": 900,
      "default": 200
    },
    "hemSweepMM": {
      "binds": "hemSweepMM",
      "unit": "mm",
      "min": 0,
      "max": 2000,
      "default": 1270,
      "source": "1960s Big-4 envelope backs, 48.5-52.5 inch over a 36 inch hip; 1270mm = 50 inch"
    },
    "backOpeningMM": {
      "binds": "backOpeningMM",
      "unit": "mm",
      "min": 0,
      "max": 900,
      "default": 558.8,
      "source": "Vogue 6900 / Vogue Couturier 2063 '22 inch neckline zipper'"
    },
    "easeNeckMM": {
      "binds": "easeNeckMM",
      "unit": "mm",
      "min": 0,
      "max": 100,
      "default": 0
    },
    "easeBustMM": {
      "binds": "easeBustMM",
      "unit": "mm",
      "min": 0,
      "max": 200,
      "default": 60,
      "source": "Threads/RTW 2 inch bust; Aldrich close-fitting 7cm"
    },
    "easeWaistMM": {
      "binds": "easeWaistMM",
      "unit": "mm",
      "min": 0,
      "max": 200,
      "default": 25,
      "source": "Threads/RTW 1 inch waist"
    },
    "easeHipMM": {
      "binds": "easeHipMM",
      "unit": "mm",
      "min": 0,
      "max": 200,
      "default": 50,
      "source": "Threads/RTW 2 inch hip"
    },
    "shoulderNarrowMM": {
      "binds": "shoulderNarrowMM",
      "unit": "mm",
      "min": 0,
      "max": 40,
      "default": 10,
      "source": "Aldrich p.28, 1 cm in from the shoulder edge"
    },
    "backNeckDropMM": {
      "binds": "backNeckDropMM",
      "unit": "mm",
      "min": 0,
      "max": 120,
      "default": 15,
      "source": "Aldrich 0-1, a flat 1.5 cm at every size"
    },
    "neckWidthCoefCM": {
      "binds": "neckWidthCoefCM",
      "unit": "cm",
      "min": -3,
      "max": 3,
      "default": -0.2,
      "source": "Aldrich back neck width, off 1/5 neck"
    },
    "frontNeckDropCoefCM": {
      "binds": "frontNeckDropCoefCM",
      "unit": "cm",
      "min": -3,
      "max": 8,
      "default": -0.2,
      "source": "Aldrich front neck drop, off 1/5 neck"
    },
    "maxDartDeg": {
      "binds": "maxDartDeg",
      "unit": "deg",
      "min": 0,
      "max": 45,
      "default": 14
    },
    "bodiceApexFrac": {
      "binds": "bodiceApexFrac",
      "unit": "frac",
      "min": 0,
      "max": 2,
      "default": 0.8
    },
    "skirtApexFrac": {
      "binds": "skirtApexFrac",
      "unit": "frac",
      "min": 0,
      "max": 2,
      "default": 1.35
    },
    "topDartSplitFrac": {
      "binds": "topDartSplitFrac",
      "unit": "frac",
      "min": 0,
      "max": 1,
      "default": 0.55
    },
    "topDartApexFrac": {
      "binds": "topDartApexFrac",
      "unit": "frac",
      "min": 0,
      "max": 1,
      "default": 0.55
    },
    "hipBlendMM": {
      "binds": "hipBlendMM",
      "unit": "mm",
      "min": 0,
      "max": 300,
      "default": 90
    },
    "shoulderCrestBandMM": {
      "binds": "shoulderCrestBandMM",
      "unit": "mm",
      "min": 0,
      "max": 200,
      "default": 60,
      "requiresOperator": "shoulderSeam"
    },
    "shoulderSeamForwardMM": {
      "binds": "shoulderSeamForwardMM",
      "unit": "mm",
      "min": -30,
      "max": 30,
      "default": 0,
      "requiresOperator": "shoulderSeam"
    }
  },
  "solverKnobs": {
    "_role": "MOTORUN SAYISAL KADRANLARI — SPEC DEĞİL. Üretilen şemaya GİRMEZ; bunları yazan bir LLM kod yazıyordur (yasa 1/4). Burada, unutulmasınlar ve başka bir yerde ikinci kez ilan edilmesinler diye duruyorlar.",
    "fields": [
      "ringSamples",
      "rowStepMM",
      "arapRounds",
      "polishIters",
      "cutRounds",
      "cutSweeps",
      "cutEmphasis",
      "skimBodice",
      "shoulderTop",
      "armhole",
      "shoulderSeam",
      "bodiceCutFracs",
      "bodiceDartFracs",
      "skirtCutFracs",
      "skirtDartFracs"
    ]
  },
  "_notMigratedFromDraft": {
    "_role": "12 Ağu taslağının bugünkü motora karşı ölçümü. Taslağın taşımadığı, bu mühürde KARŞILANAN ve KARŞILANMAYAN kalemler.",
    "draftMissedAndNowSealed": [
      "shoulder ekseni + shoulderSeam operatörü (Tur 6, taslaktan 5 gün sonra)",
      "üst çapalı pens (topDartSplitFrac / topDartApexFrac) — taslakta suppression tek eksendi, çapa yoktu",
      "armholeNotch ve necklineDraft ayrı operatör olarak (taslakta 'attachment' diye G5+'a ertelenmişti)",
      "backOpening / açıklık (taslakta `closure` sadece bir enum satırıydı, motorda karşılığı ölçülmemişti)",
      "operatör sicili ve RED yolu — taslakta hiç yoktu"
    ],
    "draftHadNoEngineCounterpart": [
      "`bands` ekseni: motorun halka listesi (neck/bust/waist/hip) SEÇİLEBİLİR değil, BodySurface'in kendisi. Spec ekseni olarak yazılmadı — sahte kapsam olurdu.",
      "`edge-finish sınıfı` (hem/band/facing): motorda ek panel üreten hiçbir operatör yok. Sicile absent olarak bile yazılmadı çünkü ölçülmedi — DOĞRULANMADI.",
      "9 malzeme kategorisinden `stand & fall`, `roll line`, `contouring`, `spring`: bugünkü motorda kadran karşılığı yok. spring flatten'da kendiliğinden çıkıyor (kadran değil), diğer üçü G5+/collarFamily'ye bağlı."
    ],
    "notSpecFields": [
      "topColXMM ve shoulderCarryMM SPEC ALANI DEĞİL — SurfacePattern'in ÇIKTI alanları (surfacepattern.hpp:117,140). Taslağın onları taşımaması doğrudur."
    ]
  }
};

export const VOCAB = {
  "_source": "Single vocabulary source. Ground truth = engine/src/*.hpp enum declarations; every values[] array is in ENUM DECLARATION ORDER, so for int fields index == enum value and for string fields index == static_cast<int>(enum). Edit here, then run: node engine/tools/gen-vocab.mjs (regenerates engine/src/vocab.gen.hpp, web/js/vocab.gen.js, backend/vocab.gen.js). Never hand-edit the generated files. synonyms map alternate inputs (vision phrasing, legacy aliases) to a canonical value; the engine boundary itself accepts ONLY canonical values.",
  "fields": {
    "garment": {
      "type": "string",
      "enum": "GarmentType",
      "values": [
        "skirt",
        "dress",
        "top"
      ]
    },
    "shaping": {
      "type": "string",
      "enum": "Shaping",
      "values": [
        "princess",
        "dart"
      ]
    },
    "waistline": {
      "type": "string",
      "enum": "Waistline",
      "values": [
        "natural",
        "empire"
      ]
    },
    "fabric": {
      "type": "string",
      "enum": "Fabric",
      "values": [
        "woven",
        "knit"
      ]
    },
    "neckline": {
      "type": "string",
      "enum": "Neckline",
      "values": [
        "crew",
        "scoop",
        "vNeck",
        "square",
        "boat",
        "sweetheart",
        "halter",
        "cowl",
        "pussyBow"
      ]
    },
    "sleeveStyle": {
      "type": "string",
      "enum": "SleeveStyle",
      "values": [
        "none",
        "straight",
        "balloon"
      ],
      "synonyms": {
        "puff": "balloon",
        "bishop": "balloon",
        "set-in": "straight",
        "fitted": "straight"
      }
    },
    "sleeveLength": {
      "type": "string",
      "enum": "SleeveLength",
      "values": [
        "short",
        "elbow",
        "long"
      ]
    },
    "skirtStyle": {
      "type": "string",
      "enum": "SkirtStyle",
      "values": [
        "aLine",
        "straight",
        "gathered",
        "halfCircle",
        "pleated",
        "gore"
      ],
      "synonyms": {
        "gored": "gore",
        "sixGore": "gore",
        "panelled": "gore",
        "paneled": "gore"
      }
    },
    "skirtLength": {
      "type": "string",
      "enum": "SkirtLength",
      "values": [
        "mini",
        "midi",
        "maxi"
      ]
    },
    "topLength": {
      "type": "string",
      "enum": "TopLength",
      "values": [
        "cropped",
        "hip",
        "tunic"
      ]
    },
    "tieClosure": {
      "type": "int",
      "enum": "TiePlacement",
      "values": [
        "none",
        "backWaist",
        "backWaistBow",
        "frontNeckBow",
        "tieBack",
        "cuffTies",
        "frontWaistTie",
        "wrapFront",
        "frontWaistBow"
      ]
    },
    "sleeveCap": {
      "type": "int",
      "enum": "SleeveCap",
      "values": [
        "plain",
        "gathered",
        "puffed",
        "cap"
      ]
    },
    "collarType": {
      "type": "int",
      "enum": "CollarType",
      "values": [
        "none",
        "stand",
        "mock",
        "flat",
        "peterPan",
        "shirt",
        "crescent"
      ]
    },
    "collarEdge": {
      "type": "int",
      "enum": "CollarEdge",
      "values": [
        "round",
        "pointed",
        "scallop"
      ]
    },
    "gatherType": {
      "type": "int",
      "enum": "GatherType",
      "values": [
        "none",
        "drawstring",
        "shirred",
        "smocked"
      ]
    },
    "gatherZone": {
      "type": "int",
      "enum": "GatherZone",
      "values": [
        "neckline",
        "bust",
        "waist",
        "sleeve"
      ]
    },
    "backOpening": {
      "type": "int",
      "enum": "BackOpening",
      "values": [
        "none",
        "round",
        "lowV",
        "square",
        "keyhole"
      ]
    },
    "laceUpBack": {
      "type": "int",
      "enum": "LaceUpBack",
      "values": [
        "none",
        "corset"
      ]
    },
    "wrapFront": {
      "type": "int",
      "enum": "WrapFront",
      "values": [
        "none",
        "surplice"
      ]
    },
    "backSlit": {
      "type": "int",
      "enum": "HemSlit",
      "values": [
        "none",
        "vent",
        "slit"
      ]
    },
    "ruffledStraps": {
      "type": "int",
      "enum": "StrapStyle",
      "values": [
        "none",
        "ruffled",
        "wide",
        "spaghetti"
      ]
    },
    "peplum": {
      "type": "int",
      "enum": "PeplumStyle",
      "values": [
        "none",
        "full",
        "half",
        "pointed"
      ]
    },
    "hemFlounce": {
      "type": "int",
      "enum": "HemFlounce",
      "values": [
        "none",
        "gathered"
      ]
    },
    "placketStyle": {
      "type": "int",
      "enum": "PlacketStyle",
      "values": [
        "none",
        "standard",
        "asymmetric"
      ]
    },
    "edgeFinish": {
      "type": "int",
      "enum": "EdgeFinish",
      "values": [
        "biasBinding",
        "facing"
      ],
      "synonyms": {
        "bias": "biasBinding"
      }
    },
    "pocketStyle": {
      "type": "int",
      "enum": "PocketStyle",
      "values": [
        "none",
        "patch",
        "sideSeam",
        "slash"
      ]
    },
    "cuffStyle": {
      "type": "int",
      "enum": "CuffStyle",
      "values": [
        "none",
        "button",
        "ribbed"
      ]
    },
    "hemShape": {
      "type": "int",
      "enum": "HemShape",
      "values": [
        "straight",
        "shirttail",
        "highLow",
        "pointedV",
        "boxPleatHem"
      ]
    },
    "shoulderStyle": {
      "type": "int",
      "enum": "ShoulderStyle",
      "values": [
        "set",
        "dropped",
        "raglan"
      ]
    },
    "buttonRow": {
      "type": "int",
      "enum": "ButtonRow",
      "values": [
        "none",
        "functional",
        "decorative"
      ]
    },
    "exposedZip": {
      "type": "int",
      "enum": "ExposedZip",
      "values": [
        "none",
        "centerFront",
        "centerBack"
      ]
    },
    "backDetail": {
      "type": "int",
      "enum": "BackDetail",
      "values": [
        "none",
        "ruffle",
        "cape",
        "flounce"
      ]
    },
    "bardotStyle": {
      "type": "int",
      "enum": "BardotStyle",
      "values": [
        "none",
        "plain",
        "frill"
      ]
    },
    "cupSeam": {
      "type": "int",
      "enum": "CupSeam",
      "values": [
        "none",
        "horizontal",
        "bugra"
      ]
    },
    "locketTop": {
      "type": "int",
      "enum": "LocketTop",
      "values": [
        "none",
        "bugra"
      ]
    },
    "yoke": {
      "type": "int",
      "enum": "Yoke",
      "values": [
        "none",
        "plain",
        "gathered"
      ]
    },
    "boxPleat": {
      "type": "int",
      "enum": "BoxPleat",
      "values": [
        "none",
        "centerInverted"
      ]
    }
  }
};

export const GRAMMAR = {
  "_OLU_2B_HATTI": "⛔ BU DOSYA HÜKÜM TAŞIMAZ. Damgalandı 2026-08-17 (Tur 10). Buradaki 'çizilebilir' iddiaları ESKİ 2B/flat formül motorunun sicilidir ve o hat 2026-07-29'da kök kusur olarak terk edildi (CLAUDE.md § YÖN DEĞİŞTİ). Bugün sevk edilen yüzey hattında bu dosyanın peterPan · gore · fullCircle · balloon değerlerinin HİÇBİRİNİN karşılığı yoktur — ölçüldü, contract/garment-spec-v2.json satır 108 ve 115'te kanıtıyla yazılı ('collar' geçen sıfır satır, 'pleat' geçen sıfır satır, yüzey hattının tek eteği hemSweepCone). 'Hangi giysiler çıkar' sorusunun TEK cevabı contract/garment-spec-v2.json'un `operators` sicilidir (H2.1, mühürlü, ctest: specv2_check). İki doğru bırakılmaz (HEDEF.md). Dosya SİLİNMEDİ çünkü ölü değil, DAR: hâlâ engine/compiler/parse.mjs'in (→ compile.mjs → ctest compile_dialect_check) okuduğu bir PARSER SÖZLÜĞÜDÜR. (2026-08-17 Tur 11: ikinci tüketici engine/tools/faz6-driver.mjs SİLİNDİ — sıfır çağıranı vardı; kalan TEK tüketici parse.mjs'tir) — kelime dağarcığı olarak koşar, kapsam beyanı olarak KOŞMAZ. Buradaki bir değere bakıp 'motor bunu çıkarır' DEME.",
  "_ROL": "DERLEYICI ARA DİLİ — motorun DÜRÜST envanteri (2026-07-22, FAZ 1). ⚠ Bu satırın 'dürüst envanter' iddiası ESKİ 2B hattı içindi, bkz. _OLU_2B_HATTI. KURAL: burada YAZAN her değer o gün ESKİ flat motor tarafından ÇİZİLEBİLİRDİ (hakem-kanıtlı ya da pinli-kanıtlı). Parser bu gramere karşı doğrular; gramerde olmayan alan üretilemez. 'ikame' YASAK — primitif yoksa ÜRETİLEMEZ + eksik.",
  "_kanit_seviyeleri": {
    "hakem": "en az 1 hedefte çift kanat hakemden geçti (geçen 11 hedef)",
    "pinli": "STYLE-PIN'de Damla-onaylı bir stilde çiziliyor ama tek-primitif hakem turu yok",
    "PARK": "gramerde YOK — henüz çizilemez ya da kanıtsız"
  },
  "_schema_version": 1,
  "slots": {
    "garment": {
      "values": {
        "top": {
          "kanit": "hakem",
          "note": "kolsuz + kollu, hip/cropped"
        },
        "dress": {
          "kanit": "hakem",
          "note": "korsaj + etek, princess/dart"
        }
      },
      "PARK": [
        "skirt",
        "trousers"
      ]
    },
    "neckline": {
      "values": {
        "crew": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ]
        },
        "scoop": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ]
        },
        "boat": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ]
        },
        "square": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ],
          "note": "gerçek square: düz taban + dik kenar (2026-07-22)"
        },
        "vNeck": {
          "kanit": "pinli",
          "kumas": [
            "woven",
            "knit"
          ],
          "note": "lace_vneck/princess_dress pininde çiziliyor"
        },
        "sweetheart": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ],
          "note": "kalp yaka: CF sığ merkez çentik + iki dolgun bust cup (kalbin yarısı). Kalıp Neckline::Sweetheart (bodice.cpp); flat kap dili (buildHalf sweetheart dalı, sadece ön; arka roundNeck scoop). styleKey dress_sweetheart_princess_circle; id54 (2026-07-23)."
        },
        "straight": {
          "kanit": "hakem",
          "kumas": [
            "woven",
            "knit"
          ],
          "note": "strapless bandeau düz üst kenar (omuz/askı yok, düz yatay bant bust üstünde). Kalıp band-top gövde (bodice strapless edge); flat top:'band' düz üst kenar (top_bandeau_shirred_peplum'da çiziliyor). Woven'da kapanış/elastik şart (wearability). styleKey top_bandeau_shirred_peplum; id40 (2026-07-23). alt_ad: strapless."
        }
      },
      "PARK": [
        "halter",
        "cowl",
        "pussyBow"
      ]
    },
    "shaping": {
      "values": {
        "dart": {
          "kanit": "hakem"
        },
        "princess": {
          "kanit": "hakem",
          "note": "ön+arka princess seam"
        },
        "boxy": {
          "kanit": "hakem",
          "note": "yan dikiş düz, bel çekmesi yok (kutu); garment=top ile",
          "gerektirir": {
            "garment": "top"
          }
        }
      },
      "PARK": []
    },
    "sleeve": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "straight": {
          "kanit": "hakem",
          "note": "plainSleeve düz set-in",
          "alt": {
            "sleeveLength": [
              "short",
              "elbow",
              "long"
            ]
          }
        },
        "balloon": {
          "kanit": "pinli",
          "note": "puffSleeve, capPuff>0; babydoll/princess pininde",
          "alt": {
            "sleeveLength": [
              "short"
            ],
            "sleeveHead": [
              "puffed"
            ]
          }
        },
        "cap": {
          "kanit": "hakem",
          "note": "cap sleeve: kısa set-in, omuzu kaplar kanat açmaz; kalıp Sleeve parçası (sleeve.cpp capCurve), flat drop=34 outW=16; id47 hakem-geçti 2026-07-22. sleeveHead='capped' de bu yola çözülür."
        }
      },
      "PARK": []
    },
    "skirt": {
      "values": {
        "aLine": {
          "kanit": "hakem",
          "note": "figürlü drape'li etek"
        },
        "gore": {
          "kanit": "pinli",
          "note": "gore_skirt_dress pininde (gorePanels)"
        },
        "fullCircle": {
          "kanit": "hakem",
          "note": "full circle etek: iki yarım-daireden kesilir; kalıp halfCirclePanel (skirt.cpp), flat geniş süpürme+dalgalı hem; id47 hakem-geçti 2026-07-22. Ad birliği: circle/full/fullCircle/halfCircle → circleSkirt() tek yol.",
          "alt_ad": [
            "circle",
            "full",
            "halfCircle"
          ]
        },
        "gathered": {
          "kanit": "hakem",
          "note": "dirndl büzgülü etek: belde büzülen dolgun etek (aLine gibi konik açılmaz, dik-düşen). Kalıp gatheredPanel (skirt.cpp SkirtStyle::Gathered); flat gatheredSkirt bayrağı → belde fizik-büzgü (cloth-solver profile:'skirt', ikinci kıvrım yolu yok). styleKey dress_vneck_gathered; id24/57 (2026-07-23)."
        }
      },
      "PARK": [
        "straight",
        "pleated"
      ]
    },
    "length": {
      "values": {
        "mini": {
          "kanit": "hakem"
        },
        "midi": {
          "kanit": "hakem"
        }
      },
      "PARK": [
        "maxi"
      ]
    },
    "topLength": {
      "values": {
        "cropped": {
          "kanit": "hakem"
        },
        "hip": {
          "kanit": "hakem"
        }
      },
      "PARK": [
        "tunic"
      ]
    },
    "peplum": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "full": {
          "kanit": "hakem",
          "note": "bele takılı dairesel flare, garment=top",
          "gerektirir": {
            "garment": "top"
          }
        },
        "half": {
          "kanit": "pinli",
          "note": "aynı geometri, sığ flare"
        },
        "pointed": {
          "kanit": "pinli",
          "note": "sivri handkerchief flare"
        }
      },
      "PARK": []
    },
    "hemRuffle": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "single": {
          "kanit": "hakem",
          "note": "peplum dış hem'ine dikilen büzgülü tek fırfır katı. Kalıp Ruffle strip (RuffleBlock, peplum hemCircumferenceMM'e trued); flat st.peplumRuffle (peplum hem'i altına dalgalı kat). SADECE peplum!=none top'ta (motor peplumsuz top'ta reddeder). id84/91 (2026-07-23)."
        }
      },
      "PARK": [
        "tiered",
        "scalloped"
      ]
    },
    "shirred": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "physics": {
          "kanit": "hakem",
          "note": "cloth-solver fizik büzgü (physicsShirr), üst-yoğun-sönümlü panel",
          "alt": {
            "gatherRatio": [
              1.8,
              3.2
            ],
            "gatherZone": [
              "bust"
            ]
          },
          "acik_kart": "bant sapması (sönüm %26 vs bant %15-25, yoğunluk 27 vs 4-6) — kart-shirred-bant-sapmasi.md"
        }
      },
      "PARK": [
        "smocked",
        "casing-drawstring-panel"
      ]
    },
    "closure": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "buttons": {
          "kanit": "pinli",
          "note": "front placket, drawstring_babydoll değil princess pin"
        },
        "zipper": {
          "kanit": "hakem",
          "note": "kalıp CB zip; flat outline'ı değiştirmez"
        },
        "tieBack": {
          "kanit": "hakem",
          "note": "arka belde bağ, ayrı kesim parçası (id53)"
        },
        "wrapFront": {
          "kanit": "pinli",
          "note": "surplice çapraz ön kapanma + yan-dikiş bel bağı; kalıp TiePlacement::WrapFront, wrap_dress pininde çiziliyor; id13/68 (2026-07-22)"
        }
      },
      "PARK": [
        "placket-asymmetric",
        "lace-up",
        "hookEye",
        "exposed-zip"
      ]
    },
    "collar": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "peterPan": {
          "kanit": "pinli",
          "note": "collarShape, peterpan_puff pininde çiziliyor — tek-primitif hakem turu YOK"
        }
      },
      "PARK": [
        "stand",
        "shirt",
        "mandarin",
        "notched",
        "sailor"
      ]
    },
    "straps": {
      "values": {
        "none": {
          "kanit": "hakem"
        },
        "ruffled": {
          "kanit": "pinli",
          "note": "strapShape, drawstring_babydoll pininde"
        },
        "wide": {
          "kanit": "hakem",
          "note": "düz self-lined geniş askı (22mm tube, no gather); kalıp StrapBlock Wide; id4/31/56/58/79/102 (2026-07-22 ASKI ailesi)"
        },
        "spaghetti": {
          "kanit": "hakem",
          "note": "ince self-lined tube (8mm); kalıp StrapBlock Spaghetti; id46/74"
        }
      },
      "PARK": [
        "shoulder",
        "halter",
        "oneShoulder",
        "offShoulder"
      ]
    },
    "detay-pinli": {
      "note": "pinli stillerde çizilen ama tek-primitif hakem turu OLMAYAN öğeler. Kombinasyonda kullanılabilir ama hedef bunlara İNDİRGENİRSE hakem şart.",
      "values": {
        "laceNeck": {
          "kanit": "pinli"
        },
        "laceSleeve": {
          "kanit": "pinli"
        },
        "laceHem": {
          "kanit": "pinli"
        },
        "cfGather": {
          "kanit": "pinli"
        },
        "wrapSurplice": {
          "kanit": "pinli"
        },
        "wrapTie": {
          "kanit": "pinli"
        },
        "backSeam": {
          "kanit": "hakem"
        },
        "casing": {
          "kanit": "pinli"
        }
      }
    }
  },
  "gecersiz_kombinasyonlar": [
    {
      "kural": "sleeve=none + sleeveLength/sleeveHead",
      "neden": "kolsuzda kol parametresi olamaz"
    },
    {
      "kural": "sleeve=none + balloon/straight",
      "neden": "kolsuz ile kol stili çelişir"
    },
    {
      "kural": "peplum!=none + garment=dress",
      "neden": "peplum top belden takılır; dress'te etek zaten var (şimdilik)"
    },
    {
      "kural": "shirred=physics + garment=dress",
      "neden": "shirred panel top gövdesine kalibre; dress kombinasyonu kanıtsız"
    },
    {
      "kural": "boxy + shaping=princess",
      "neden": "boxy düz yan, princess figürlü — çelişir"
    },
    {
      "kural": "collar!=none + neckline=halter",
      "neden": "halter yaka collar taşımaz (halter PARK zaten)"
    }
  ],
  "kumas_siniflari": {
    "woven": {
      "note": "dokuma, esnemez. kapanışsız dar yaka GİYİLEMEZ (baş geçmez) — closure zorunlu"
    },
    "knit": {
      "note": "örme, esner. kapanışsız dar yaka OK (35cm yaka örmede kafadan geçer)"
    },
    "_kural": "garment kapanışsız + neckOpening dar + woven → wearability FAIL. knit ise geç. (id82 numune dersi)"
  }
};

export const V1V2 = {
  "_contract": "v1 (okuma dili) <-> v2 (operator sicili) ESLEME TABLOSU. URETILMIS DOSYA — elle duzenleme. Kaynak: engine/tools/gen-spec-v1v2-map.mjs. Hukum (expressible/missing) YAZILMAZ, contract/garment-spec.schema.json + contract/garment-spec-v2.json okunarak HESAPLANIR.",
  "_law": [
    "v1 OLU DEGIL: contract_check ve collar_bridge_check onu okuyor, gen-contract.mjs $defs.visionReading i backend/ ve web/ e gomuyor. Damgalanacak ceset degil.",
    "v1 v2 nin TUREVI de DEGIL: bir giysiyi ADIYLA reddedebilmek icin once onu OKUYABILMEK gerekir (HEDEF.md bitis tanimi). v1 i v2 ye daraltmak red cumlesini susturur.",
    "IKI DOGRU YOK, cunku iki AYRI SORU var: v1 = \"ne goruyorum?\", v2 = \"uretebiliyor muyum?\". Uretilebilirligin TEK cevabi v2.operators tir.",
    "Bir v1 enum degerine bakip \"motor bunu cikarir\" DEME. Bu tablodaki expressible alanina bak."
  ],
  "generatedFrom": {
    "v1": "contract/garment-spec.schema.json",
    "v2": "contract/garment-spec-v2.json",
    "v2specVersion": "garment-spec/2"
  },
  "summary": {
    "v1EnumValuesMapped": 79,
    "expressibleToday": 31,
    "notExpressibleToday": 48
  },
  "v1NonEnumFields": [
    "keyhole",
    "fabricName",
    "cupSeams",
    "outOfVocab",
    "details",
    "ratios"
  ],
  "axes": {
    "garment": {
      "note": null,
      "values": {
        "skirt": {
          "v2": "garment.skirt",
          "layer": "topology",
          "requires": [
            "skirtSurface"
          ],
          "expressible": true,
          "missing": []
        },
        "dress": {
          "v2": "garment.sheathDress",
          "layer": "topology",
          "requires": [
            "bodiceSurface",
            "skirtSurface",
            "necklineDraft",
            "armholeNotch"
          ],
          "expressible": true,
          "missing": []
        },
        "top": {
          "v2": "garment.top",
          "layer": "topology",
          "requires": [
            "bodiceSurface",
            "necklineDraft",
            "armholeNotch"
          ],
          "expressible": true,
          "missing": []
        },
        "trousers": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 garment enum pantolon tasimiyor; motorda bacak yuzeyi yok",
          "expressible": false,
          "missing": []
        },
        "other": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "kapali enum kacak degeri kabul etmez",
          "expressible": false,
          "missing": []
        }
      }
    },
    "neckline": {
      "note": "v2 YAKA SEKLI ekseni tasimiyor. necklineDraft operatoru SHIPPED ama sekli enum ile degil, quantities.neckDrop*/neckWidth* kadranlariyla ciziyor. Yani bu dokuz kelime OKUNUR, motor tarafindan AYIRT EDILMEZ.",
      "values": {
        "crew": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "scoop": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "vNeck": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "square": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "boat": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "sweetheart": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "halter": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "cowl": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        },
        "pussyBow": {
          "v2": "QUANTITY.necklineDraft",
          "layer": "quantity",
          "requires": [
            "necklineDraft"
          ],
          "expressible": true,
          "missing": []
        }
      }
    },
    "sleeveStyle": {
      "note": null,
      "values": {
        "none": {
          "v2": "sleeve.none",
          "layer": "topology",
          "requires": [
            "armholeNotch"
          ],
          "expressible": true,
          "missing": []
        },
        "straight": {
          "v2": "sleeve.setIn",
          "layer": "topology",
          "requires": [
            "sleeve"
          ],
          "expressible": false,
          "missing": [
            "sleeve"
          ]
        },
        "balloon": {
          "v2": "sleeve.puff",
          "layer": "topology",
          "requires": [
            "sleeve",
            "gatheredOverlayLayer"
          ],
          "expressible": false,
          "missing": [
            "sleeve",
            "gatheredOverlayLayer"
          ]
        }
      }
    },
    "sleeveLength": {
      "note": "kol UZUNLUGU v2 de hic yok: sleeve operatoru absent oldugu icin bagli bir kadran da yok.",
      "values": {
        "short": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "sleeve operatoru absent",
          "expressible": false,
          "missing": []
        },
        "elbow": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "sleeve operatoru absent",
          "expressible": false,
          "missing": []
        },
        "long": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "sleeve operatoru absent",
          "expressible": false,
          "missing": []
        }
      }
    },
    "skirtStyle": {
      "note": null,
      "values": {
        "aLine": {
          "v2": "skirtShape.aLine",
          "layer": "topology",
          "requires": [
            "skirtSurface",
            "hemSweepCone"
          ],
          "expressible": true,
          "missing": []
        },
        "straight": {
          "v2": "skirtShape.straight",
          "layer": "topology",
          "requires": [
            "skirtSurface"
          ],
          "expressible": true,
          "missing": []
        },
        "gathered": {
          "v2": "skirtShape.gathered",
          "layer": "topology",
          "requires": [
            "skirtFamily"
          ],
          "expressible": false,
          "missing": [
            "skirtFamily"
          ]
        },
        "pleated": {
          "v2": "skirtShape.pleated",
          "layer": "topology",
          "requires": [
            "skirtFamily"
          ],
          "expressible": false,
          "missing": [
            "skirtFamily"
          ]
        },
        "gore": {
          "v2": "skirtShape.gore",
          "layer": "topology",
          "requires": [
            "skirtFamily"
          ],
          "expressible": false,
          "missing": [
            "skirtFamily"
          ]
        },
        "halfCircle": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 sadece fullCircle tasiyor; yarim daire EN YAKIN karsilik ama AYNI degil",
          "expressible": false,
          "missing": []
        }
      }
    },
    "length": {
      "note": "v1 kelimeyle (mini/midi/maxi), v2 mm ile olcer: quantities.hemDropBelowHipMM.",
      "values": {
        "mini": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "midi": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "maxi": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        }
      }
    },
    "topLength": {
      "note": null,
      "values": {
        "cropped": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "hip": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "tunic": {
          "v2": "QUANTITY.hemDropBelowHipMM",
          "layer": "quantity",
          "requires": [],
          "expressible": true,
          "missing": []
        }
      }
    },
    "shaping": {
      "note": null,
      "values": {
        "princess": {
          "v2": "suppression.seamOnly",
          "layer": "topology",
          "requires": [
            "princessCut"
          ],
          "expressible": true,
          "missing": []
        },
        "dart": {
          "v2": "suppression.dart",
          "layer": "topology",
          "requires": [
            "princessCut",
            "waistAnchoredDart"
          ],
          "expressible": true,
          "missing": []
        }
      }
    },
    "waistline": {
      "note": null,
      "values": {
        "natural": {
          "v2": "QUANTITY.bodiceSurface",
          "layer": "quantity",
          "requires": [
            "bodiceSurface"
          ],
          "expressible": true,
          "missing": []
        },
        "empire": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "v2 de bel yuksekligi ekseni yok; govde yuzeyi tek dogal bel halkasi tasiyor",
          "expressible": false,
          "missing": []
        }
      }
    },
    "fabric": {
      "note": "malzeme geometri ekseni degil; v2 topolojisi kumas tanimaz (kumas onerisi H1.1b, ayri hat).",
      "values": {
        "woven": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "kumas v2 topolojisinde yok",
          "expressible": false,
          "missing": []
        },
        "knit": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "kumas v2 topolojisinde yok",
          "expressible": false,
          "missing": []
        }
      }
    },
    "hemRuffle": {
      "note": null,
      "values": {
        "none": {
          "v2": "closure.none",
          "layer": "topology",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "single": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "etek ucu firfiri icin operator yok",
          "expressible": false,
          "missing": []
        },
        "tiered": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "etek ucu firfiri icin operator yok",
          "expressible": false,
          "missing": []
        }
      }
    },
    "closure": {
      "note": null,
      "values": {
        "none": {
          "v2": "closure.none",
          "layer": "topology",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "zipper": {
          "v2": "closure.centreBackZip",
          "layer": "topology",
          "requires": [
            "backOpening",
            "zipperPiece"
          ],
          "expressible": false,
          "missing": [
            "zipperPiece"
          ]
        },
        "buttons": {
          "v2": "closure.buttonFront",
          "layer": "topology",
          "requires": [
            "zipperPiece"
          ],
          "expressible": false,
          "missing": [
            "zipperPiece"
          ]
        },
        "placket": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum patlet tasimiyor",
          "expressible": false,
          "missing": []
        },
        "ties": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum bag tasimiyor",
          "expressible": false,
          "missing": []
        },
        "lace-up": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum kordon tasimiyor",
          "expressible": false,
          "missing": []
        },
        "hookEye": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum kopca tasimiyor",
          "expressible": false,
          "missing": []
        }
      }
    },
    "collar": {
      "note": null,
      "values": {
        "none": {
          "v2": "collar.none",
          "layer": "topology",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "stand": {
          "v2": "collar.stand",
          "layer": "topology",
          "requires": [
            "collarFamily"
          ],
          "expressible": false,
          "missing": [
            "collarFamily"
          ]
        },
        "shirt": {
          "v2": "collar.shirt",
          "layer": "topology",
          "requires": [
            "collarFamily"
          ],
          "expressible": false,
          "missing": [
            "collarFamily"
          ]
        },
        "peterPan": {
          "v2": "collar.peterPan",
          "layer": "topology",
          "requires": [
            "collarFamily"
          ],
          "expressible": false,
          "missing": [
            "collarFamily"
          ]
        },
        "mandarin": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 collar enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "notched": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 collar enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "sailor": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 collar enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "other": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "kapali enum kacak degeri kabul etmez",
          "expressible": false,
          "missing": []
        }
      }
    },
    "straps": {
      "note": null,
      "values": {
        "none": {
          "v2": "shoulder.strapless",
          "layer": "topology",
          "requires": [
            "bodiceSurface"
          ],
          "expressible": true,
          "missing": []
        },
        "shoulder": {
          "v2": "shoulder.shoulderSeam",
          "layer": "topology",
          "requires": [
            "shoulderSeam"
          ],
          "expressible": false,
          "missing": [
            "shoulderSeam"
          ]
        },
        "spaghetti": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        },
        "wide": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        },
        "halter": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        },
        "ruffled": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        },
        "oneShoulder": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        },
        "offShoulder": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 shoulder enum sadece strapless|shoulderSeam",
          "expressible": false,
          "missing": []
        }
      }
    },
    "sleeveHead": {
      "note": null,
      "values": {
        "plain": {
          "v2": "sleeve.setIn",
          "layer": "topology",
          "requires": [
            "sleeve"
          ],
          "expressible": false,
          "missing": [
            "sleeve"
          ]
        },
        "gathered": {
          "v2": "sleeve.puff",
          "layer": "topology",
          "requires": [
            "sleeve",
            "gatheredOverlayLayer"
          ],
          "expressible": false,
          "missing": [
            "sleeve",
            "gatheredOverlayLayer"
          ]
        },
        "puffed": {
          "v2": "sleeve.puff",
          "layer": "topology",
          "requires": [
            "sleeve",
            "gatheredOverlayLayer"
          ],
          "expressible": false,
          "missing": [
            "sleeve",
            "gatheredOverlayLayer"
          ]
        },
        "capped": {
          "v2": "sleeve.cap",
          "layer": "topology",
          "requires": [
            "sleeve"
          ],
          "expressible": false,
          "missing": [
            "sleeve"
          ]
        }
      }
    },
    "yoke": {
      "note": null,
      "values": {
        "none": {
          "v2": "closure.none",
          "layer": "topology",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "shoulderYoke": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "roba operatoru yok",
          "expressible": false,
          "missing": []
        },
        "shirring": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "buzgu katmani absent",
          "expressible": false,
          "missing": []
        },
        "smocking": {
          "v2": null,
          "reason": "NO_AXIS",
          "why": "buzgu katmani absent",
          "expressible": false,
          "missing": []
        }
      }
    },
    "backDetail": {
      "note": null,
      "values": {
        "none": {
          "v2": "closure.none",
          "layer": "topology",
          "requires": [],
          "expressible": true,
          "missing": []
        },
        "openBack": {
          "v2": "closure.backOpening",
          "layer": "topology",
          "requires": [
            "backOpening"
          ],
          "expressible": true,
          "missing": []
        },
        "keyholeBack": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "vBack": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "tieBack": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "lacedBack": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum tasimiyor",
          "expressible": false,
          "missing": []
        },
        "buttonBack": {
          "v2": null,
          "reason": "NO_VALUE",
          "why": "v2 closure enum tasimiyor",
          "expressible": false,
          "missing": []
        }
      }
    }
  }
};

