#!/usr/bin/env node
// anchor_source_check.mjs — THE ANCHOR DICTIONARY IS A BUILD PRODUCT.
//
// WHY THIS FILE EXISTS. A list of place-names ("neckZone", "skirt.hem") is the
// one artefact in this tree that CANNOT be told from taste by looking at it. A
// hand-written one and a derived one are the same bytes. GECE/V6-C.md priced
// the failure mode: the naive `taraf × jeton` generation produces 54 candidates
// of which at least 8 contradict themselves (`frontCenterback`, `frontBack`,
// `backCenterfront`, ...) — a MENU that reads like a vocabulary. So the file is
// not judged by reading it; it is judged by REGENERATING it and by re-resolving
// every `kaynak` back into the contract that supposedly declared it.
//
// WHAT IT ENFORCES — four gates, and only the first is the generator's word:
//   1. regen-and-diff, tolerance ZERO BYTES (the Go/Kubernetes/Bazel pattern,
//      already the precedent here in engine/tests/vocab_source_check.sh). Runs
//      twice into mktemp: DETERMINISM is checked, not claimed, and the gate
//      never writes into the tree it is judging.
//   2. every `kaynak` / `bilesenKaynak` path is re-walked in the named contract
//      file, INDEPENDENTLY of the generator. A record whose source does not
//      resolve is a hand-edit that survived gate 1 by being regenerated from a
//      generator someone also edited.
//   3. no anchor may land on zero panels, and no anchor name may carry two
//      distinct position tokens (the `frontCenterback` class). Both are
//      re-derived from contract/primitives-v1.json here, not read off the JSON.
//   4. `_dogmayan` still tells the truth: every name it says was not born must
//      really be absent from `anchors`, with a usable reason. Gate 1 alone can
//      be passed by a lie, because the generator writes both sides.
//
// HOW TO GO GREEN. Never by editing contract/anchors-v1.json. Edit the contract
// the anchor comes from (edit-locality / composition / primitives), then
//   node engine/tools/gen-anchors.mjs
// and commit the contract and the regenerated JSON in the same commit.
import { readFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const GEN = 'engine/tools/gen-anchors.mjs';
const OUT = 'contract/anchors-v1.json';

let fails = 0;
const fail = (m) => { console.log('FAIL:', m); fails++; };
const ok = (m) => console.log('ok:', m);

// A MISSING LAW IS NEVER A PASS.
for (const f of [GEN, OUT, 'contract/edit-locality-v1.json', 'contract/composition.json',
  'contract/primitives-v1.json']) {
  try { readFileSync(join(ROOT, f)); } catch {
    console.log(`FAIL: ${f} missing — a missing law is never a pass.`);
    process.exit(1);
  }
}

const tmp = mkdtempSync(join(tmpdir(), 'anchors-'));
process.on('exit', () => { try { rmSync(tmp, { recursive: true, force: true }); } catch { /* best effort */ } });

// ── 1. deterministic + byte-identical ────────────────────────────────────────
const run = (args) => execFileSync('node', [join(ROOT, GEN), ...args], { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
let a;
let b;
try {
  run(['--out', join(tmp, 'a.json')]);
  run(['--out', join(tmp, 'b.json')]);
  a = readFileSync(join(tmp, 'a.json'), 'utf8');
  b = readFileSync(join(tmp, 'b.json'), 'utf8');
} catch (e) {
  console.log(`FAIL: ${GEN} exited nonzero:\n${e.stderr || e.message}`);
  process.exit(1);
}
if (a !== b) fail(`${GEN} is NOT deterministic — two runs, different bytes.`);
else ok(`generator deterministic — two runs, byte-identical (${a.length} bytes)`);

// --check is the flag the ctest entry and humans use; it must agree with the diff.
let checkExit = 0;
try { run(['--check']); } catch (e) { checkExit = e.status === undefined ? 1 : e.status; }
const onDisk = readFileSync(join(ROOT, OUT), 'utf8');
if (onDisk !== a) {
  fail(`${OUT} is STALE or HAND-EDITED — it is not what ${GEN} produces. fix: node ${GEN}`);
  if (checkExit === 0) fail(`${GEN} --check exited 0 on a file it does NOT reproduce — the flag is broken`);
} else if (checkExit !== 0) {
  fail(`${GEN} --check exited ${checkExit} on a byte-identical file — the flag is broken`);
} else {
  ok(`${OUT} byte-identical to the generator, and --check agrees (exit 0)`);
}

const doc = JSON.parse(onDisk);
if (!String(onDisk.split('\n')[0] || '').includes('GENERATED by engine/tools/gen-anchors.mjs — DO NOT EDIT')) {
  fail('line 1 does not carry the GENERATED / DO NOT EDIT stamp');
}

// ── 2. every kaynak re-resolves, independently of the generator ──────────────
const cache = new Map();
const load = (rel) => {
  if (!cache.has(rel)) cache.set(rel, JSON.parse(readFileSync(join(ROOT, rel), 'utf8')));
  return cache.get(rel);
};
// Keys in these contracts contain dots ("op.attach"), so a naive split is wrong.
// Walk greedily: at each node try the longest key prefix that exists.
function resolve(node, segs) {
  if (!segs.length) return { found: true, value: node };
  if (node === null || node === undefined) return { found: false };
  if (Array.isArray(node)) {
    if (segs.length === 1) return { found: node.includes(segs[0]), value: segs[0] };
    // e.g. bilesenler.<c>.primitifler.op.attach -> array membership then stop
    const joined = segs.join('.');
    return { found: node.includes(joined), value: joined };
  }
  if (typeof node !== 'object') return { found: false };
  // `components[7].conflictClass` — an array index inside a segment.
  const m0 = /^(.+?)\[(\d+)\]$/.exec(segs[0]);
  if (m0 && Array.isArray(node[m0[1]])) {
    const arr = node[m0[1]];
    const i = Number(m0[2]);
    if (i < 0 || i >= arr.length) return { found: false };
    return resolve(arr[i], segs.slice(1));
  }
  for (let take = segs.length; take >= 1; take--) {
    const key = segs.slice(0, take).join('.');
    if (Object.prototype.hasOwnProperty.call(node, key)) {
      const r = resolve(node[key], segs.slice(take));
      if (r.found) return r;
    }
  }
  return { found: false };
}
function checkSource(path, where) {
  const i = path.indexOf(':');
  if (i < 0) { fail(`${where}: kaynak '${path}' is not dosya:anahtar`); return; }
  const file = path.slice(0, i);
  const key = path.slice(i + 1);
  let root;
  try { root = load(file); } catch { fail(`${where}: kaynak names '${file}', which does not parse`); return; }
  if (!resolve(root, key.split('.')).found) {
    fail(`${where}: kaynak '${path}' does NOT resolve — '${key}' is absent from ${file}`);
  }
}

if (!Array.isArray(doc.anchors) || !doc.anchors.length) fail('anchors is empty or absent — an empty dictionary is not a pass');
for (const an of doc.anchors || []) {
  const w = `anchor '${an.ad}'`;
  if (!an.ad || !an.kaynak) { fail(`${w}: missing ad/kaynak`); continue; }
  checkSource(an.kaynak, w);
  for (const bk of an.bilesenKaynak || []) checkSource(bk, w);
  if (!Array.isArray(an.bilesen) || !an.bilesen.length) fail(`${w}: no bilesen — an anchor no component declares is a menu entry`);
  if (!(an.bilesenKaynak || []).length) fail(`${w}: bilesen has no source path`);
  if (an.kenarOrani && !an.kenarOraniKaynak) fail(`${w}: claims kenarOrani with no source`);
  if (an.kenarOraniKaynak) checkSource(an.kenarOraniKaynak, `${w} kenarOrani`);
}

// A resolving index is not enough: components[7] exists whatever is in it. For
// every zone anchor, re-derive the declaring components straight from
// composition.json and demand the same set, in the same order.
const composition = load('contract/composition.json');
const declaring = new Map();
composition.components.forEach((c, i) => {
  for (const z of String(c.conflictClass || '').split(/[|+]/).map((s) => s.trim()).filter(Boolean)) {
    if (!declaring.has(z)) declaring.set(z, []);
    declaring.get(z).push({ id: c.id, idx: i });
  }
});
for (const an of (doc.anchors || []).filter((x) => x.aile === 'bolge')) {
  const want = (declaring.get(an.ad) || []).slice().sort((x, y) => x.id.localeCompare(y.id));
  const got = an.bilesen || [];
  if (JSON.stringify(want.map((x) => x.id)) !== JSON.stringify(got)) {
    fail(`anchor '${an.ad}': bilesen ${JSON.stringify(got)} != composition.json's declarers ${JSON.stringify(want.map((x) => x.id))}`);
  }
  const wantPaths = want.map((x) => `contract/composition.json:components[${x.idx}].conflictClass`);
  if (JSON.stringify(wantPaths) !== JSON.stringify(an.bilesenKaynak || [])) {
    fail(`anchor '${an.ad}': bilesenKaynak indices point at the wrong components (composition.json reordered?)`);
  }
}

// ── 3. lands somewhere, and is not self-contradictory ────────────────────────
const prim = load('contract/primitives-v1.json');
const POSITION_PARAM = /landmark|position|region/i;
const tokens = new Set();
for (const op of Object.values(prim.primitifler || {})) {
  for (const [pName, p] of Object.entries(op.parametreler || {})) {
    if (POSITION_PARAM.test(pName) && Array.isArray(p.degerler)) p.degerler.forEach((v) => tokens.add(v));
  }
}
for (const z of Object.keys(load('contract/edit-locality-v1.json').zones || {})) tokens.add(z);
if (tokens.size < 8) fail(`position token set collapsed to ${tokens.size} — the re-derivation is broken, not the data`);

const locality = load('contract/edit-locality-v1.json');
for (const an of doc.anchors || []) {
  const landed = ((an.panelDeseni || {}).eslesen) || [];
  if (!landed.length) {
    fail(`anchor '${an.ad}' lands on ZERO panels — the frontCenterback class: a name with nowhere to go`);
  }
  // two distinct position tokens inside one name = the cross product leaked in
  const norm = String(an.ad).toLowerCase().replace(/[^a-z]/g, '');
  const hit = [...tokens].filter((t) => norm.includes(t.toLowerCase()));
  const maximal = hit.filter((t) => !hit.some((o) => o !== t && o.toLowerCase().includes(t.toLowerCase())));
  if (maximal.length > 1) {
    fail(`anchor '${an.ad}' carries ${maximal.length} position tokens (${maximal.join(', ')}) — self-contradictory name`);
  }
  // an operator anchor must not name a zone that excludes every panel it claims
  if (an.aile === 'operator') {
    if (!an.bolge || !locality.zones[an.bolge]) { fail(`anchor '${an.ad}': bolge '${an.bolge}' is not a declared zone`); continue; }
    const pats = (locality.zones[an.bolge].untouchable || []).map((p) => new RegExp(p));
    const bad = landed.filter((n) => pats.some((re) => re.test(n)));
    if (bad.length) fail(`anchor '${an.ad}': zone '${an.bolge}' declares ${bad.length} of its landed panels untouchable (${bad[0]})`);
  }
}

// ── 4. _dogmayan still tells the truth ───────────────────────────────────────
const born = new Set((doc.anchors || []).map((x) => x.ad));
const unborn = doc._dogmayan || [];
if (!unborn.length) fail('_dogmayan is empty — nothing was rejected, so nothing was filtered; the generator is a pass-through');
for (const u of unborn) {
  if (born.has(u.ad)) fail(`'${u.ad}' is in BOTH anchors and _dogmayan`);
  if (!u.sebep || u.sebep.length < 20) fail(`_dogmayan['${u.ad}'] has no usable reason`);
}

// the measurement block must match what is actually in the file
const m = doc._olcum || {};
if (m.cipa !== (doc.anchors || []).length) fail(`_olcum.cipa=${m.cipa} but anchors has ${(doc.anchors || []).length}`);
if (m.dogmayanAd !== unborn.length) fail(`_olcum.dogmayanAd=${m.dogmayanAd} but _dogmayan has ${unborn.length}`);
if (m.kenarOraniTasiyan !== (doc.anchors || []).filter((x) => x.kenarOrani).length) fail('_olcum.kenarOraniTasiyan does not match the records');

console.log('----');
if (fails) {
  console.log(`anchor_source_check: HUKUM FAIL (${fails})`);
  console.log('The anchor dictionary is a BUILD PRODUCT. It stopped matching its sources.');
  process.exit(1);
}
console.log(
  `anchor_source_check: HUKUM YESIL — ${(doc.anchors || []).length} anchors, every kaynak resolved, ` +
  `${(doc.anchors || []).filter((x) => x.kenarOrani).length} carry an edge fraction, ${unborn.length} names refused.`,
);
process.exit(0);
