#!/usr/bin/env node
// Generates the three vocabulary tables from engine/vocab.json (the single
// source). Deterministic: same input, byte-identical output — run twice, git
// diff must be empty. Outputs:
//   engine/src/vocab.gen.hpp  (C++ tables for the WASM boundary)
//   web/js/vocab.gen.js       (JS maps for engine.js + tools)
//   backend/vocab.gen.js      (same maps for the Cloudflare Worker)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '../..');
const vocab = JSON.parse(readFileSync(join(root, 'engine/vocab.json'), 'utf8'));
const fields = vocab.fields;

const HEADER = 'GENERATED by engine/tools/gen-vocab.mjs from engine/vocab.json — DO NOT EDIT.';

// ---- C++ ---------------------------------------------------------------------
const cap = (s) => s[0].toUpperCase() + s.slice(1);
let hpp = `#pragma once\n// ${HEADER}\n// values[] order == enum declaration order, so index == enum value.\n\nnamespace stitchu {\nnamespace vocab {\n\n`;
for (const [field, def] of Object.entries(fields)) {
  const vals = def.values.map((v) => `"${v}"`).join(', ');
  hpp += `// ${def.enum} (${def.type})\ninline constexpr const char* k${cap(field)}[] = { ${vals} };\ninline constexpr int k${cap(field)}Count = ${def.values.length};\n`;
}
hpp += `\n} // namespace vocab\n} // namespace stitchu\n`;
writeFileSync(join(root, 'engine/src/vocab.gen.hpp'), hpp);

// ---- JS (web + worker share the same content) --------------------------------
let js = `// ${HEADER}\n// values order == C++ enum declaration order, so indexOf(name) == enum int.\n// synonyms map alternate inputs (vision phrasing, legacy aliases) to canonical\n// values — resolve them BEFORE the engine boundary; the boundary itself only\n// accepts canonical values.\n\nexport const VOCAB = ${JSON.stringify(fields, null, 2)};\n\n// Canonical value name -> enum int for an int-typed field; -1 when unknown.\nexport function enumInt(field, name) {\n  const def = VOCAB[field];\n  if (!def) return -1;\n  return def.values.indexOf(name);\n}\n\n// Resolve a synonym to its canonical value (returns the input when it is\n// already canonical, undefined when the value is unknown to the field).\nexport function canonical(field, name) {\n  const def = VOCAB[field];\n  if (!def) return undefined;\n  if (def.values.includes(name)) return name;\n  if (def.synonyms && Object.prototype.hasOwnProperty.call(def.synonyms, name)) return def.synonyms[name];\n  return undefined;\n}\n`;
writeFileSync(join(root, 'web/js/vocab.gen.js'), js);
writeFileSync(join(root, 'backend/vocab.gen.js'), js);

console.log('wrote engine/src/vocab.gen.hpp, web/js/vocab.gen.js, backend/vocab.gen.js');
