// specv2.mjs — the garment-spec v2 compiler front end (H2.1, 2026-08-17).
//
// Two jobs, one place:
//   1. buildSchema()  — turns contract/garment-spec-v2.json into a JSON Schema
//                       (closed enums, additionalProperties:false everywhere).
//   2. checkSpec()    — answers the ONLY question the bitiş tanımı asks of a
//                       spec: can this garment be expressed? If not, the answer
//                       NAMES the missing operator.
//
// The second job is why this file exists at all. A schema that only says
// "well-formed / malformed" cannot produce the sentence "kalan 2'si eksik
// operatörünü ADIYLA söyleyerek reddeder". So validity here has THREE outcomes,
// not two:
//   ok          — every axis is a legal enum value and every operator it
//                 requires is `shipped`.
//   invalid     — the JSON is not in the language (unknown field, unknown enum
//                 value, scalar out of its declared band). This is a WRITER
//                 error; the LLM wrote something the language does not contain.
//   unsupported — the JSON is perfectly legal and the engine cannot build it.
//                 This is OUR limit, and the refusal carries the operator id,
//                 its status, and its own refusalReason sentence.
//
// DERSLER, and the reason there is no fourth outcome: a silent enum fallback
// (puff -> None) is hallucination. Nothing in this file substitutes a nearest
// neighbour, and nothing defaults a rejected value. Refusal is the product.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
export const root = join(here, '../..');
export const CONTRACT_PATH = join(root, 'contract/garment-spec-v2.json');
export const SCHEMA_PATH = join(root, 'contract/garment-spec-v2.schema.json');

export function loadContract(path = CONTRACT_PATH) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

// ---- 1. schema generation ---------------------------------------------------
// The generated schema is a DERIVATIVE, never hand-edited: gen-spec-v2.mjs
// writes it and specv2_check fails if the file on disk differs from what this
// function produces (the same ratchet contract_check runs on contract.gen.*).
export function buildSchema(c) {
  const topology = {};
  for (const [axis, def] of Object.entries(c.topology)) {
    if (axis.startsWith('_')) continue;
    topology[axis] = { enum: Object.keys(def.values) };
  }
  const quantities = {};
  for (const [name, q] of Object.entries(c.quantities)) {
    if (name.startsWith('_')) continue;
    quantities[name] = { type: 'number', minimum: q.min, maximum: q.max };
  }
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://nosey-dewdrop.github.io/stitchu/contract/garment-spec-v2.schema.json',
    title: 'stitchu garment spec v2 (GENERATED — edit contract/garment-spec-v2.json)',
    description:
      'Generated by engine/tools/gen-spec-v2.mjs from contract/garment-spec-v2.json. ' +
      'CLOSED: additionalProperties is false at every level, so a field the language does ' +
      'not declare is rejected rather than ignored. Passing this schema means the JSON is ' +
      'in the LANGUAGE; it does NOT mean the engine can build the garment — that second ' +
      'question is the operator registry, answered by specv2.mjs checkSpec(), and its ' +
      'refusal names the operator. Solver knobs (contract solverKnobs) are deliberately ' +
      'absent: an LLM that writes arapRounds is writing code.',
    version: c.version,
    type: 'object',
    additionalProperties: false,
    required: ['spec', 'topology'],
    properties: {
      spec: { const: c.specVersion },
      size: { enum: ['EU34', 'EU36', 'EU38', 'EU40', 'EU42', 'EU44', 'EU46', 'EU48'] },
      topology: {
        type: 'object',
        additionalProperties: false,
        required: Object.keys(topology),
        properties: topology,
      },
      quantities: {
        type: 'object',
        additionalProperties: false,
        properties: quantities,
      },
    },
  };
}

// ---- 2. the language check (no ajv: the schema shape is ours, so is the walk)
function checkLanguage(c, spec, errors) {
  if (spec === null || typeof spec !== 'object' || Array.isArray(spec)) {
    errors.push('spec is not a JSON object');
    return;
  }
  const allowedTop = new Set(['spec', 'size', 'topology', 'quantities']);
  for (const k of Object.keys(spec)) {
    if (!allowedTop.has(k)) errors.push(`unknown field '${k}' (the schema is closed)`);
  }
  if (spec.spec !== c.specVersion) {
    errors.push(`spec version must be '${c.specVersion}', got ${JSON.stringify(spec.spec)}`);
  }
  const topo = spec.topology;
  if (topo === undefined) { errors.push("missing 'topology'"); }
  else if (topo === null || typeof topo !== 'object' || Array.isArray(topo)) {
    errors.push("'topology' is not an object");
  } else {
    for (const [axis, def] of Object.entries(c.topology)) {
      if (axis.startsWith('_')) continue;
      const v = topo[axis];
      if (v === undefined) { errors.push(`topology.${axis} missing (every axis is required)`); continue; }
      if (!Object.prototype.hasOwnProperty.call(def.values, v)) {
        errors.push(
          `topology.${axis} = ${JSON.stringify(v)} is not in the closed enum ` +
          `[${Object.keys(def.values).join(', ')}] — NOT substituted, rejected`);
      }
    }
    for (const k of Object.keys(topo)) {
      if (!Object.prototype.hasOwnProperty.call(c.topology, k) || k.startsWith('_')) {
        errors.push(`unknown topology axis '${k}'`);
      }
    }
  }
  const qs = spec.quantities;
  if (qs !== undefined) {
    if (qs === null || typeof qs !== 'object' || Array.isArray(qs)) {
      errors.push("'quantities' is not an object");
    } else {
      for (const [k, v] of Object.entries(qs)) {
        const q = c.quantities[k];
        if (!q || k.startsWith('_')) { errors.push(`unknown quantity '${k}'`); continue; }
        if (typeof v !== 'number' || !Number.isFinite(v)) {
          errors.push(`quantities.${k} is not a finite number`); continue;
        }
        if (v < q.min || v > q.max) {
          errors.push(`quantities.${k} = ${v} outside declared band [${q.min}, ${q.max}] ${q.unit}`);
        }
      }
    }
  }
}

// ---- 3. the registry query — H2.7's foundation ------------------------------
// Every enum value the spec chose declares the operators it needs. An operator
// that is not `shipped` blocks the spec, and the block carries its NAME.
export function requiredOperators(c, spec) {
  const req = new Map(); // operatorId -> [axis=value, ...]
  const topo = (spec && spec.topology) || {};
  for (const [axis, def] of Object.entries(c.topology)) {
    if (axis.startsWith('_')) continue;
    const chosen = def.values[topo[axis]];
    if (!chosen) continue; // unknown value: already a language error
    for (const op of chosen.requires) {
      if (!req.has(op)) req.set(op, []);
      req.get(op).push(`${axis}=${topo[axis]}`);
    }
  }
  const qs = (spec && spec.quantities) || {};
  for (const [k, v] of Object.entries(qs)) {
    const q = c.quantities[k];
    if (q && q.requiresOperator && typeof v === 'number') {
      const op = q.requiresOperator;
      if (!req.has(op)) req.set(op, []);
      req.get(op).push(`quantities.${k}`);
    }
  }
  return req;
}

export function checkSpec(c, spec) {
  const errors = [];
  checkLanguage(c, spec, errors);
  if (errors.length) return { verdict: 'invalid', errors, missing: [] };

  const req = requiredOperators(c, spec);
  const missing = [];
  for (const [id, askedBy] of req) {
    const op = c.operators[id];
    if (!op) { errors.push(`spec requires operator '${id}' which is not in the registry at all`); continue; }
    if (op.status !== 'shipped') {
      missing.push({
        operator: id,
        tr: op.tr,
        status: op.status,
        askedBy,
        reason: op.refusalReason || `operatör '${id}' sicilde ${op.status}`,
        ring: op.ring || null,
        blockedBy: op.blockedBy || null,
      });
    }
  }
  if (errors.length) return { verdict: 'invalid', errors, missing };
  if (missing.length) return { verdict: 'unsupported', errors: [], missing };
  return { verdict: 'ok', errors: [], missing: [] };
}

// The refusal SENTENCE. Named operators first, in the order they were asked
// for; the sentence is the product, so it is built here once and printed
// wherever a refusal surfaces (test, CLI, later the web).
export function refusalSentence(result) {
  if (result.verdict === 'ok') return '';
  if (result.verdict === 'invalid') {
    return 'GEÇERSİZ SPEC (dil hatası): ' + result.errors.join(' · ');
  }
  const names = result.missing.map((m) => m.operator).join(', ');
  const detail = result.missing
    .map((m) => `  - ${m.operator} (${m.tr}) [${m.status}] — ${m.reason}` +
                (m.blockedBy ? ` (önce: ${m.blockedBy})` : '') +
                `  ← istendi: ${m.askedBy.join(', ')}`)
    .join('\n');
  return `BU GİYSİYİ ÇIKARAMIYORUM. Eksik operatör: ${names}\n${detail}`;
}
