#pragma once
// GENERATED by engine/tools/gen-contract.mjs from contract/body-v1.json — DO NOT EDIT.
// kNoValue (NaN) = contract'ta null (kaynak bulunamadi); body.cpp bunu 'yok' okur.
#include <limits>

namespace stitchu {
namespace contract {

constexpr double kNoValue = std::numeric_limits<double>::quiet_NaN();

struct BodyLandmarkRow { const char* name; double x, y; };
struct BodyGirthRow { const char* name; double girthMM, backFrac; };
struct BodyScalarRow { const char* name; double v; };

inline constexpr BodyLandmarkRow kBodyLandmarks_gercek36[] = {
    {"nape", 0, -20},
    {"neckBase", 66, 0},
    {"neckFront", 0, 36.3},
    {"shoulderTip", 177.5, 44.3},
    {"underarm", 210, 186},
    {"bustApex", 85, 259.3},
    {"bustLine", 210, 259.3},
    {"underbust", 181.4, 324.3},
    {"waist", 165, 390},
    {"highHip", 195, 490},
    {"hip", 225, 593},
    {"crotch", 0, 663},
    {"knee", 0, 970},
    {"ankle", 0, 1350},
    {"elbow", 177.5, 374.3},
    {"wrist", 177.5, 634.3},
};
inline constexpr BodyGirthRow kBodyGirths_gercek36[] = {
    {"girth.neckBase", 360, 0.5},
    {"girth.upperBust", 770, kNoValue},
    {"girth.bust", 840, 0.473232},
    {"girth.underbust", 725.8, kNoValue},
    {"girth.waist", 660, 0.455643},
    {"girth.highHip", 780, kNoValue},
    {"girth.hip", 900, 0.535263},
    {"girth.biceps", 270, kNoValue},
    {"girth.elbow", kNoValue, kNoValue},
    {"girth.wrist", 155, kNoValue},
    {"girth.armhole", kNoValue, kNoValue},
    {"girth.knee", kNoValue, kNoValue},
};
inline constexpr BodyScalarRow kBodyScalars_gercek36[] = {
    {"length.napeToShoulderLine", 20},
    {"length.backNapeToWaist", 410},
    {"length.frontNeckToWaist", kNoValue},
    {"length.frontShoulderToWaistOverApex", 440},
    {"length.shoulder", 120},
    {"length.armholeDepth", 206},
    {"length.bustDepth", 260},
    {"length.waistToHip", 203},
    {"length.waistToHighHip", 100},
    {"length.waistToKnee", 580},
    {"length.waistToFloor", 1030},
    {"length.waistToAnkle", 960},
    {"length.arm", 590},
    {"length.shoulderToElbow", 330},
    {"length.stature", 1680},
    {"width.shoulderToShoulder", 355},
    {"width.crossFront", 312},
    {"width.crossBack", 334},
    {"width.apexToApex", 170},
    {"width.neckBase", 132},
    {"angle.shoulderSlope", 21.6777},
};

inline constexpr BodyLandmarkRow kBodyLandmarks_croquis36[] = {
    {"nape", 0, -20},
    {"neckBase", 47.2, 0},
    {"neckFront", 0, 26},
    {"shoulderTip", 183.8, 49.7},
    {"underarm", 210, 156},
    {"bustApex", 73.1, 172},
    {"bustLine", 210, 172},
    {"underbust", 181.4, 230},
    {"waist", 170.5, 390},
    {"highHip", 195, 490},
    {"hip", 225, 593},
    {"crotch", 0, 663},
    {"knee", 0, 970},
    {"ankle", 0, 1350},
    {"elbow", 183.8, 390},
    {"wrist", 183.8, 593},
};
inline constexpr BodyGirthRow kBodyGirths_croquis36[] = {
    {"girth.neckBase", 360, 0.5},
    {"girth.upperBust", 770, kNoValue},
    {"girth.bust", 840, 0.473232},
    {"girth.underbust", 725.8, kNoValue},
    {"girth.waist", 682, 0.455643},
    {"girth.highHip", 780, kNoValue},
    {"girth.hip", 900, 0.535263},
    {"girth.biceps", 270, kNoValue},
    {"girth.elbow", kNoValue, kNoValue},
    {"girth.wrist", 155, kNoValue},
    {"girth.armhole", kNoValue, kNoValue},
    {"girth.knee", kNoValue, kNoValue},
};
inline constexpr BodyScalarRow kBodyScalars_croquis36[] = {
    {"length.napeToShoulderLine", 20},
    {"length.backNapeToWaist", 410},
    {"length.frontNeckToWaist", kNoValue},
    {"length.frontShoulderToWaistOverApex", 440},
    {"length.shoulder", 145.4},
    {"length.armholeDepth", 206},
    {"length.bustDepth", 173.9},
    {"length.waistToHip", 203},
    {"length.waistToHighHip", 100},
    {"length.waistToKnee", 580},
    {"length.waistToFloor", 1030},
    {"length.waistToAnkle", 960},
    {"length.arm", 543.3},
    {"length.shoulderToElbow", 340.3},
    {"length.stature", 1680},
    {"width.shoulderToShoulder", 367.6},
    {"width.crossFront", 312.5},
    {"width.crossBack", 312.5},
    {"width.apexToApex", 146.2},
    {"width.neckBase", 94.4},
    {"angle.shoulderSlope", 20},
};

// farkTablosu: croquis36 - gercek36 (dx, dy), mm
inline constexpr BodyLandmarkRow kBodyFark[] = {
    {"nape", 0, 0},
    {"neckBase", -18.8, 0},
    {"neckFront", 0, -10.3},
    {"shoulderTip", 6.3, 5.4},
    {"underarm", 0, -30},
    {"bustApex", -11.9, -87.3},
    {"bustLine", 0, -87.3},
    {"underbust", 0, -94.3},
    {"waist", 5.5, 0},
    {"highHip", 0, 0},
    {"hip", 0, 0},
    {"crotch", 0, 0},
    {"knee", 0, 0},
    {"ankle", 0, 0},
    {"elbow", 6.3, 15.7},
    {"wrist", 6.3, -41.3},
};

inline constexpr int kBodyGradeCount = 6;
inline constexpr const char* kBodyGradeSizes[kBodyGradeCount] = {"EU34", "EU36", "EU38", "EU40", "EU42", "EU44"};
struct BodyGradeCol { const char* name; double v[kBodyGradeCount]; };
inline constexpr BodyGradeCol kBodyGradeCols[] = {
    {"girth.bust", {800, 840, 880, 920, 960, 1000}},
    {"girth.waist", {620, 660, 700, 740, 780, 820}},
    {"girth.hip", {860, 900, 940, 980, 1020, 1060}},
    {"girth.neckBase", {350, 360, 370, 380, 390, 400}},
    {"girth.highHip", {740, 780, 820, 860, 900, 940}},
    {"girth.biceps", {260, 270, 280, 290, 300, 310}},
    {"girth.wrist", {150, 155, 160, 165, 170, 175}},
    {"length.backNapeToWaist", {405, 410, 415, 420, 425, 430}},
    {"length.frontShoulderToWaistOverApex", {430, 440, 450, 460, 470, 480}},
    {"length.shoulder", {117.5, 120, 122.5, 125, 127.5, 130}},
    {"length.armholeDepth", {202, 206, 210, 214, 218, 222}},
    {"length.bustDepth", {250, 260, 270, 280, 290, 300}},
    {"length.waistToHip", {200, 203, 206, 209, 212, 215}},
    {"length.waistToKnee", {575, 580, 585, 590, 595, 600}},
    {"length.waistToFloor", {1020, 1030, 1040, 1050, 1060, 1070}},
    {"length.bodyRise", {266, 273, 280, 287, 294, 301}},
    {"length.arm", {590, 590, 600, 600, 610, 610}},
    {"length.stature", {1680, 1680, 1680, 1680, 1680, 1680}},
    {"width.crossFront", {300, 312, 324, 336, 348, 360}},
    {"width.crossBack", {324, 334, 344, 354, 364, 374}},
    {"width.neckBase", {130, 132, 134, 136, 138, 140}},
    {"angle.shoulderSlope", {21.6777, 21.6777, 21.6777, 21.6777, 21.6777, 21.6777}},
    {"arkaPay.bust", {0.471891, 0.473232, 0.474451, 0.475564, 0.476584, 0.477522}},
    {"arkaPay.waist", {0.452885, 0.455643, 0.458096, 0.460292, 0.462269, 0.464058}},
    {"arkaPay.hip", {0.536952, 0.535263, 0.533721, 0.532308, 0.531009, 0.52981}},
};
inline constexpr BodyScalarRow kBodyGradeConst[] = {
    {"length.napeToShoulderLine", 20},
    {"length.waistToHighHip", 100},
    {"length.shoulderToElbow_oran", 0.559322033898305},
    {"width.apexToApex_oran", 0.20238095238095238},
    {"girth.upperBust_fark", 70},
    {"girth.underbust_oran", 0.864},
    {"ankleFloor", 70},
    {"underbustApexDropMM", 65},
    {"neckFrontOverHalfNeck", 0.55},
};

inline constexpr BodyScalarRow kCroquisOran[] = {
    {"waistHalfOverBustHalf", 0.812},
    {"shoulderTipXOverBustHalf", 0.875},
    {"neckHalfOverBustHalf", 0.225},
    {"apexXOverBustHalf", 0.348},
    {"apexDropOverTorso", 0.441},
    {"underarmOverTorso", 0.4},
    {"underbustDropMM", 58},
    {"shoulderSlopeDeg", 20},
    {"dikeyUzatma", 1},
};

inline constexpr BodyScalarRow kBodyKesitOran[] = {
    {"girth.neckBase", 1.05},
    {"girth.upperBust", 1.35},
    {"girth.bust", 1.35},
    {"girth.underbust", 1.35},
    {"girth.waist", 1.3},
    {"girth.highHip", 1.4},
    {"girth.hip", 1.4},
    {"girth.biceps", 1},
    {"girth.elbow", 1},
    {"girth.wrist", 1},
    {"girth.knee", 1},
    {"girth.armhole", 1},
};

inline constexpr double kBodyKapiToleransMM = 0.5;
inline constexpr double kAyniInsanToleransMM = 2;

} // namespace contract
} // namespace stitchu
