#pragma once
// GENERATED by engine/tools/gen-contract.mjs from contract/body-v1.json — DO NOT EDIT.
// kNoValue (NaN) = contract'ta null (kaynak bulunamadi); body.cpp bunu 'yok' okur.
#include <limits>

namespace stitchu {
namespace contract {

constexpr double kNoValue = std::numeric_limits<double>::quiet_NaN();

struct BodyLandmarkRow { const char* name; double x, y; };
struct BodyGirthRow { const char* name; double girthMM, backFrac; };
struct BodyScalarRow { const char* name; double v; };

inline constexpr BodyLandmarkRow kBodyLandmarks_gercek36[] = {
    {"landmark.nape", 0, -20},
    {"landmark.neckBase", 66, 0},
    {"landmark.neckFront", 0, 36.3},
    {"landmark.shoulderTip", 177.5, 44.3},
    {"landmark.underarm", 114.1, 186},
    {"landmark.bustApex", 85, 200.2},
    {"landmark.bustLine", 124.5, 200.2},
    {"landmark.underbust", 118.1, 265.2},
    {"landmark.waist", 117, 390},
    {"landmark.highHip", 137.2, 490},
    {"landmark.hip", 156.9, 593},
    {"landmark.crotch", 0, 663},
    {"landmark.knee", 0, 970},
    {"landmark.ankle", 0, 1350},
    {"landmark.elbow", 177.5, 374.3},
    {"landmark.wrist", 177.5, 634.3},
};
inline constexpr BodyGirthRow kBodyGirths_gercek36[] = {
    {"girth.neckBase", 360, 0.5},
    {"girth.upperBust", 770, kNoValue},
    {"girth.bust", 840, 0.473232},
    {"girth.underbust", 725.8, kNoValue},
    {"girth.waist", 660, 0.455643},
    {"girth.highHip", 780, kNoValue},
    {"girth.hip", 900, 0.535263},
    {"girth.biceps", 270, kNoValue},
    {"girth.elbow", kNoValue, kNoValue},
    {"girth.wrist", 155, kNoValue},
    {"girth.armhole", kNoValue, kNoValue},
    {"girth.knee", kNoValue, kNoValue},
};
inline constexpr BodyScalarRow kBodyScalars_gercek36[] = {
    {"length.napeToShoulderLine", 20},
    {"length.backNapeToWaist", 410},
    {"length.frontNeckToWaist", kNoValue},
    {"length.frontShoulderToWaistOverApex", 440},
    {"length.shoulder", 120},
    {"length.armholeDepth", 206},
    {"length.bustDepth", 260},
    {"length.waistToHip", 203},
    {"length.waistToHighHip", 100},
    {"length.waistToKnee", 580},
    {"length.waistToFloor", 1030},
    {"length.waistToAnkle", 960},
    {"length.arm", 590},
    {"length.shoulderToElbow", 330},
    {"length.stature", 1680},
    {"width.shoulderToShoulder", 355},
    {"width.crossFront", 312},
    {"width.crossBack", 334},
    {"width.apexToApex", 170},
    {"width.neckBase", 132},
    {"angle.shoulderSlope", 21.6777},
};

inline constexpr BodyLandmarkRow kBodyLandmarks_croquis36[] = {
    {"landmark.nape", 0, -20},
    {"landmark.neckBase", 70.7, 0},
    {"landmark.neckFront", 0, 38.9},
    {"landmark.shoulderTip", 188.8, 46.9},
    {"landmark.underarm", 123, 198.3},
    {"landmark.bustApex", 91.1, 213.3},
    {"landmark.bustLine", 133.4, 213.3},
    {"landmark.underbust", 126.5, 278.3},
    {"landmark.waist", 106.4, 414.4},
    {"landmark.highHip", 137.2, 514.4},
    {"landmark.hip", 156.9, 629.5},
    {"landmark.crotch", 0, 703.7},
    {"landmark.knee", 0, 1028.9},
    {"landmark.ankle", 0, 1435.7},
    {"landmark.elbow", 236.2, 393.3},
    {"landmark.wrist", 273.6, 666.2},
};
inline constexpr BodyGirthRow kBodyGirths_croquis36[] = {
    {"girth.neckBase", 385.7, 0.5},
    {"girth.upperBust", 830, 0.5},
    {"girth.bust", 900, 0.5},
    {"girth.underbust", 777.6, 0.5},
    {"girth.waist", 600, 0.5},
    {"girth.highHip", 780, 0.5},
    {"girth.hip", 900, 0.5},
    {"girth.biceps", 245.5, 0.5},
    {"girth.elbow", kNoValue, kNoValue},
    {"girth.wrist", 140.9, 0.5},
    {"girth.armhole", kNoValue, kNoValue},
    {"girth.knee", kNoValue, kNoValue},
};
inline constexpr BodyScalarRow kBodyScalars_croquis36[] = {
    {"length.napeToShoulderLine", 20},
    {"length.backNapeToWaist", 434.4},
    {"length.frontNeckToWaist", kNoValue},
    {"length.frontShoulderToWaistOverApex", 466.2},
    {"length.shoulder", 127.1},
    {"length.armholeDepth", 218.3},
    {"length.bustDepth", 275.5},
    {"length.waistToHip", 215.1},
    {"length.waistToHighHip", 100},
    {"length.waistToKnee", 614.5},
    {"length.waistToFloor", 1091.3},
    {"length.waistToAnkle", 1021.3},
    {"length.arm", 625.1},
    {"length.shoulderToElbow", 349.6},
    {"length.stature", 1780},
    {"width.shoulderToShoulder", 377.6},
    {"width.crossFront", 334.3},
    {"width.crossBack", 357.9},
    {"width.apexToApex", 182.1},
    {"width.neckBase", 141.4},
    {"angle.shoulderSlope", 21.7},
};

// farkTablosu: croquis36 - gercek36 (dx, dy), mm
inline constexpr BodyLandmarkRow kBodyFark[] = {
    {"landmark.nape", 0, 0},
    {"landmark.neckBase", 4.7, 0},
    {"landmark.neckFront", 0, 2.6},
    {"landmark.shoulderTip", 11.3, 2.6},
    {"landmark.underarm", 8.9, 12.3},
    {"landmark.bustApex", 6.1, 13.1},
    {"landmark.bustLine", 8.9, 13.1},
    {"landmark.underbust", 8.4, 13.1},
    {"landmark.waist", -10.6, 24.4},
    {"landmark.highHip", 0, 24.4},
    {"landmark.hip", 0, 36.5},
    {"landmark.crotch", 0, 40.7},
    {"landmark.knee", 0, 58.9},
    {"landmark.ankle", 0, 85.7},
    {"landmark.elbow", 58.7, 19},
    {"landmark.wrist", 96.1, 31.9},
};

inline constexpr int kBodyGradeCount = 6;
inline constexpr const char* kBodyGradeSizes[kBodyGradeCount] = {"EU34", "EU36", "EU38", "EU40", "EU42", "EU44"};
struct BodyGradeCol { const char* name; double v[kBodyGradeCount]; };
inline constexpr BodyGradeCol kBodyGradeCols[] = {
    {"girth.bust", {800, 840, 880, 920, 960, 1000}},
    {"girth.waist", {620, 660, 700, 740, 780, 820}},
    {"girth.hip", {860, 900, 940, 980, 1020, 1060}},
    {"girth.neckBase", {350, 360, 370, 380, 390, 400}},
    {"girth.highHip", {740, 780, 820, 860, 900, 940}},
    {"girth.biceps", {260, 270, 280, 290, 300, 310}},
    {"girth.wrist", {150, 155, 160, 165, 170, 175}},
    {"length.backNapeToWaist", {405, 410, 415, 420, 425, 430}},
    {"length.frontShoulderToWaistOverApex", {430, 440, 450, 460, 470, 480}},
    {"length.shoulder", {117.5, 120, 122.5, 125, 127.5, 130}},
    {"length.armholeDepth", {202, 206, 210, 214, 218, 222}},
    {"length.bustDepth", {250, 260, 270, 280, 290, 300}},
    {"length.waistToHip", {200, 203, 206, 209, 212, 215}},
    {"length.waistToKnee", {575, 580, 585, 590, 595, 600}},
    {"length.waistToFloor", {1020, 1030, 1040, 1050, 1060, 1070}},
    {"length.bodyRise", {266, 273, 280, 287, 294, 301}},
    {"length.arm", {590, 590, 600, 600, 610, 610}},
    {"length.stature", {1680, 1680, 1680, 1680, 1680, 1680}},
    {"width.crossFront", {300, 312, 324, 336, 348, 360}},
    {"width.crossBack", {324, 334, 344, 354, 364, 374}},
    {"width.neckBase", {130, 132, 134, 136, 138, 140}},
    {"angle.shoulderSlope", {21.6777, 21.6777, 21.6777, 21.6777, 21.6777, 21.6777}},
    {"arkaPay.bust", {0.471891, 0.473232, 0.474451, 0.475564, 0.476584, 0.477522}},
    {"arkaPay.waist", {0.452885, 0.455643, 0.458096, 0.460292, 0.462269, 0.464058}},
    {"arkaPay.hip", {0.536952, 0.535263, 0.533721, 0.532308, 0.531009, 0.52981}},
};
inline constexpr BodyScalarRow kBodyGradeConst[] = {
    {"length.napeToShoulderLine", 20},
    {"length.waistToHighHip", 100},
    {"length.shoulderToElbow_oran", 0.559322033898305},
    {"width.apexToApex_oran", 0.20238095238095238},
    {"girth.upperBust_fark", 70},
    {"girth.underbust_oran", 0.864},
    {"ankleFloor", 70},
    {"underbustApexDropMM", 65},
    {"neckFrontOverHalfNeck", 0.55},
    {"cervicaleToApexOverNapeToWaist", 0.5371},
};

inline constexpr BodyScalarRow kCroquisManken[] = {
    {"girth.bust", 900},
    {"girth.waist", 600},
    {"girth.hip", 900},
    {"boyMM", 1780},
    {"kiloKG", 55},
    {"gercekBoyMM", 1680},
};
inline constexpr BodyScalarRow kCroquisOran[] = {
    {"waistHalfOverBustHalf", 0.812},
    {"shoulderTipXOverBustHalf", 0.875},
    {"neckHalfOverShoulderTipX", 0.267},
    {"apexXOverShoulderTipX", 0.42},
    {"apexDropOverTorso", 0.6535},
    {"underarmOverTorso", 0.625},
    {"underbustDropMM", 58},
    {"shoulderSlopeDeg", 20},
    {"crossOverShoulderToShoulder", 0.85},
    {"dikeyUzatma", 1},
    {"kolAcisiDeg", 82.2},
};
inline constexpr BodyScalarRow kCroquisBolluk[] = {
    {"girth.waist", 0.0333},
};
inline constexpr const char* kCroquisOmuzHukmu = "croquis36 OMUZ HUKMU (karar ajani 2, F1 tur 5): croquis girth x = cevre/4 (duz serilmis giysi, on+arka ust uste, iki kat), omuz cizgisi duz serilince KATLANMAZ; bu yuzden croquis omuz ucu (sevkPoz omuzGogusOran x gogus yarimi) gogus yariminin ICINDE kalir ve body_check (g) 'shoulderTip.x >= bustLine.x' hukmu GERCEK bedene (ANSUR on izdusum: 1986/1986 kadinda biacromial > chestbreadth) aittir, croquis'e uygulanmaz; croquis omuz/gogus yalniz (f) sevkPoz bandi [0.85, 0.90] ile yargilanir. Kaynak: satilan flat 13 Mica omuz ucu / oyuk yarimi 0.67; Bugra Locket-38 kesim cizgisi omuz ucu / gogus yarimi 0.957 (flat-convention sevkPoz.omuzGogusOran._kaynak). farkTablosu.ozet 'omuz ucu +6.3' bu hukmun sayisidir.";

inline constexpr BodyScalarRow kBodyKesitOran[] = {
    {"girth.neckBase", 1.05},
    {"girth.upperBust", 1.163},
    {"girth.bust", 1.163},
    {"girth.underbust", 1.297},
    {"girth.waist", 1.437},
    {"girth.highHip", 1.499},
    {"girth.hip", 1.571},
    {"girth.biceps", 1},
    {"girth.elbow", 1},
    {"girth.wrist", 1},
    {"girth.knee", 1},
    {"girth.armhole", 1},
    {"breadthOverGirth.girth.bust", 0.2964},
    {"depthOverGirth.girth.bust", 0.2549},
    {"breadthOverGirth.girth.upperBust", 0.2964},
    {"depthOverGirth.girth.upperBust", 0.2549},
    {"breadthOverGirth.girth.underbust", 0.3253},
    {"depthOverGirth.girth.underbust", 0.2509},
    {"breadthOverGirth.girth.waist", 0.3546},
    {"depthOverGirth.girth.waist", 0.2468},
    {"breadthOverGirth.girth.highHip", 0.3517},
    {"depthOverGirth.girth.highHip", 0.2346},
    {"breadthOverGirth.girth.hip", 0.3487},
    {"depthOverGirth.girth.hip", 0.222},
    {"lobYukseklikMM.girth.bust", 60},
    {"lobSigmaOverApexX", 0.5},
};

struct BodyOrderRow { const char* name; int tier; };
inline constexpr BodyOrderRow kBodyOrder_gercek36[] = {
    {"landmark.nape", 0},
    {"landmark.neckBase", 1},
    {"landmark.neckFront", 2},
    {"landmark.shoulderTip", 3},
    {"landmark.underarm", 4},
    {"landmark.bustLine", 5},
    {"landmark.bustApex", 5},
    {"landmark.underbust", 6},
    {"landmark.waist", 7},
    {"landmark.highHip", 8},
    {"landmark.hip", 9},
    {"landmark.crotch", 10},
    {"landmark.knee", 11},
    {"landmark.ankle", 12},
};
inline constexpr BodyOrderRow kBodyOrder_croquis36[] = {
    {"landmark.nape", 0},
    {"landmark.neckBase", 1},
    {"landmark.neckFront", 2},
    {"landmark.shoulderTip", 3},
    {"landmark.underarm", 4},
    {"landmark.bustLine", 5},
    {"landmark.bustApex", 5},
    {"landmark.underbust", 6},
    {"landmark.waist", 7},
    {"landmark.highHip", 8},
    {"landmark.hip", 9},
    {"landmark.crotch", 10},
    {"landmark.knee", 11},
    {"landmark.ankle", 12},
};

inline constexpr BodyScalarRow kBodyCizimYardimcisi[] = {
    {"bacakDisDizOverHip", 0.55},
    {"bacakDisBilekOverHip", 0.35},
    {"bacakIcDizOverHip", 0.2},
    {"bacakIcBilekOverHip", 0.15},
    {"agHalkaYarimOverHip", 0.45},
};

struct BodyBandRow { const char* name; double lo, hi; const char* kaynak; };
inline constexpr BodyBandRow kCroquisBand[] = {
    {"waistHalfOverBustHalf", 0.72, 0.84, "figure-bands ratios.waist_bust.band"},
    {"bustHalfOverHipHalf", 0.88, 0.98, "figure-bands ratios.bust_hip.band"},
    {"shoulderTipXOverBustHalf", 0.85, 0.9, "flat-convention sevkPoz.omuzGogusOran"},
    {"shoulderSlopeDeg", 15, 22, "flat-convention sevkPoz.omuzEgimiDeg"},
};

inline constexpr double kBodyKapiToleransMM = 0.5;
inline constexpr double kAyniInsanToleransMM = 2;

} // namespace contract
} // namespace stitchu
