#pragma once
// GENERATED by engine/tools/gen-contract.mjs from contract/tables.json — DO NOT EDIT.
// The K1 contract relocates shared values; it never changes them. The golden
// reference is the guard: a value drift here fails the byte-identical diff.

namespace stitchu {
namespace contract {

// draft.skirtLengthMM — real hem drop in millimetres (measurements.hpp reads these)
inline constexpr double kSkirtLength_mini = 450;
inline constexpr double kSkirtLength_midi = 650;
inline constexpr double kSkirtLength_maxi = 900;

// draft.gatherRatios — flat cut width / finished gathered width (gather.cpp reads these)
inline constexpr double kGatherRatio_drawstring = 1.8;
inline constexpr double kGatherRatio_shirred = 2;
inline constexpr double kGatherRatio_smocked = 3;
inline constexpr double kGatherRatio_sleeveCapPuffed = 1.29;
inline constexpr double kGatherRatio_sleeveCapGathered = 1.235;
inline constexpr double kGatherRatio_sleeveCapPuffedLift = 1.095;

// draft.euSizeChart — standard bodies (sizechart.hpp expands this X-macro).
// Columns: bustCM, waistCM, hipCM, shoulderCM, backLengthCM, armLengthCM, neckCM
#define STITCHU_CONTRACT_EU_SIZE_CHART(X) \
    X("EU34", 80, 62, 86, 36, 39.5, 57, 34) \
    X("EU36", 84, 66, 90, 36.5, 40, 57.5, 34.5) \
    X("EU38", 88, 70, 94, 37, 40.5, 58, 35) \
    X("EU40", 92, 74, 98, 37.5, 41, 58.5, 36) \
    X("EU42", 96, 78, 102, 38, 41.5, 59, 36.5) \
    X("EU44", 100, 82, 106, 38.5, 42, 59.5, 37) \
    X("EU46", 104, 86, 110, 39, 42, 60, 38) \
    X("EU48", 110, 92, 116, 40, 42.5, 60.5, 39) \
    X("EU50", 116, 98, 122, 41, 43, 61, 40) \
    X("EU52", 122, 104, 128, 42, 43.5, 61.5, 41)

// contract/parca-gecis-v1.json — geçiş kuralı + pens eskalasyonu (F5-parca).
// Baş çevresi referansı: theknitwit.org "minimum neck opening = head circumference / stretch ratio".
inline constexpr double kHeadCircumferenceMM = 510;
// Tek pens ağzı tavanı (anicka.design, KAYNAK ZAYIF — blog): üstü iki pense bölünür.
inline constexpr double kMaxSingleDartMouthMM = 30;
// Supresyon dağılım bandı (anicka.design, KAYNAK ZAYIF) — KAYIT, tele bağlı değil
// (contract dosyasındaki _uygulama notu: Aldrich pens derinliği kararıyla çelişir).
inline constexpr double kSuppressionSideShare = 0.6;
inline constexpr double kSuppressionDartShare = 0.4;
// FBA -> prenses bandı (curvysewingcollective, KAYNAK ZAYIF) — KAYIT.
inline constexpr double kFbaPrincessMinMM = 25;
inline constexpr double kFbaPrincessMaxMM = 50;

} // namespace contract
} // namespace stitchu
