#pragma once
// GENERATED by engine/pattern-bridge/gen-shape-ratios.py from mapping.py
// via contract/layers/shape-ratios.json — DO NOT EDIT.
//
// BACK share of the girth ARC per ring. Semantics verified in
// GarmentCode's own programs (bodice.py:22, bands.py:50,
// circle_skirt.py:150): back_width is an arc of the girth, not a chord.
// 0.5 would mean "no front and no back", which is what the engine had.
// The neck ring has NO source and stays 0.5 as a declared assumption.
//
// A plain table, not an X-macro: this one is consumed inside a function
// body, and a macro expanding to statements there is a parse trap.

namespace stitchu {
namespace contract {

struct BackArcRow {
    const char* label;
    double bust, waist, hip;
};

// Sizes absent here (EU50/EU52) have no published ratio and keep 0, so
// the surface visibly falls back to the symmetric section.
inline constexpr BackArcRow kBackArcFraction[] = {
    {"EU34", 0.471891, 0.452885, 0.536952},
    {"EU36", 0.473232, 0.455643, 0.535263},
    {"EU38", 0.474451, 0.458096, 0.533721},
    {"EU40", 0.475564, 0.460292, 0.532308},
    {"EU42", 0.476584, 0.462269, 0.531009},
    {"EU44", 0.477522, 0.464058, 0.52981},
    {"EU46", 0.478388, 0.465686, 0.528701},
    {"EU48", 0.479189, 0.467172, 0.527671},
};

} // namespace contract
} // namespace stitchu
