#pragma once
// GENERATED by engine/tools/gen-vocab.mjs from engine/vocab.json — DO NOT EDIT.
// values[] order == enum declaration order, so index == enum value.

namespace stitchu {
namespace vocab {

// GarmentType (string)
inline constexpr const char* kGarment[] = { "skirt", "dress", "top" };
inline constexpr int kGarmentCount = 3;
// Shaping (string)
inline constexpr const char* kShaping[] = { "princess", "dart" };
inline constexpr int kShapingCount = 2;
// Waistline (string)
inline constexpr const char* kWaistline[] = { "natural", "empire" };
inline constexpr int kWaistlineCount = 2;
// Fabric (string)
inline constexpr const char* kFabric[] = { "woven", "knit" };
inline constexpr int kFabricCount = 2;
// Neckline (string)
inline constexpr const char* kNeckline[] = { "crew", "scoop", "vNeck", "square", "boat", "sweetheart", "halter", "cowl", "pussyBow" };
inline constexpr int kNecklineCount = 9;
// SleeveStyle (string)
inline constexpr const char* kSleeveStyle[] = { "none", "straight", "balloon" };
inline constexpr int kSleeveStyleCount = 3;
// SleeveLength (string)
inline constexpr const char* kSleeveLength[] = { "short", "elbow", "long" };
inline constexpr int kSleeveLengthCount = 3;
// SkirtStyle (string)
inline constexpr const char* kSkirtStyle[] = { "aLine", "straight", "gathered", "halfCircle", "pleated", "gore" };
inline constexpr int kSkirtStyleCount = 6;
// SkirtLength (string)
inline constexpr const char* kSkirtLength[] = { "mini", "midi", "maxi" };
inline constexpr int kSkirtLengthCount = 3;
// TopLength (string)
inline constexpr const char* kTopLength[] = { "cropped", "hip", "tunic" };
inline constexpr int kTopLengthCount = 3;
// TiePlacement (int)
inline constexpr const char* kTieClosure[] = { "none", "backWaist", "backWaistBow", "frontNeckBow", "tieBack", "cuffTies", "frontWaistTie", "wrapFront", "frontWaistBow" };
inline constexpr int kTieClosureCount = 9;
// SleeveCap (int)
inline constexpr const char* kSleeveCap[] = { "plain", "gathered", "puffed", "cap" };
inline constexpr int kSleeveCapCount = 4;
// CollarType (int)
inline constexpr const char* kCollarType[] = { "none", "stand", "mock", "flat", "peterPan", "shirt", "crescent" };
inline constexpr int kCollarTypeCount = 7;
// CollarEdge (int)
inline constexpr const char* kCollarEdge[] = { "round", "pointed", "scallop" };
inline constexpr int kCollarEdgeCount = 3;
// GatherType (int)
inline constexpr const char* kGatherType[] = { "none", "drawstring", "shirred", "smocked" };
inline constexpr int kGatherTypeCount = 4;
// GatherZone (int)
inline constexpr const char* kGatherZone[] = { "neckline", "bust", "waist", "sleeve" };
inline constexpr int kGatherZoneCount = 4;
// BackOpening (int)
inline constexpr const char* kBackOpening[] = { "none", "round", "lowV", "square", "keyhole" };
inline constexpr int kBackOpeningCount = 5;
// LaceUpBack (int)
inline constexpr const char* kLaceUpBack[] = { "none", "corset" };
inline constexpr int kLaceUpBackCount = 2;
// WrapFront (int)
inline constexpr const char* kWrapFront[] = { "none", "surplice" };
inline constexpr int kWrapFrontCount = 2;
// HemSlit (int)
inline constexpr const char* kBackSlit[] = { "none", "vent", "slit" };
inline constexpr int kBackSlitCount = 3;
// StrapStyle (int)
inline constexpr const char* kRuffledStraps[] = { "none", "ruffled", "wide", "spaghetti" };
inline constexpr int kRuffledStrapsCount = 4;
// PeplumStyle (int)
inline constexpr const char* kPeplum[] = { "none", "full", "half", "pointed" };
inline constexpr int kPeplumCount = 4;
// HemFlounce (int)
inline constexpr const char* kHemFlounce[] = { "none", "gathered" };
inline constexpr int kHemFlounceCount = 2;
// PlacketStyle (int)
inline constexpr const char* kPlacketStyle[] = { "none", "standard", "asymmetric" };
inline constexpr int kPlacketStyleCount = 3;
// EdgeFinish (int)
inline constexpr const char* kEdgeFinish[] = { "biasBinding", "facing" };
inline constexpr int kEdgeFinishCount = 2;
// PocketStyle (int)
inline constexpr const char* kPocketStyle[] = { "none", "patch", "sideSeam", "slash" };
inline constexpr int kPocketStyleCount = 4;
// CuffStyle (int)
inline constexpr const char* kCuffStyle[] = { "none", "button", "ribbed" };
inline constexpr int kCuffStyleCount = 3;
// HemShape (int)
inline constexpr const char* kHemShape[] = { "straight", "shirttail", "highLow", "pointedV", "boxPleatHem" };
inline constexpr int kHemShapeCount = 5;
// ShoulderStyle (int)
inline constexpr const char* kShoulderStyle[] = { "set", "dropped", "raglan" };
inline constexpr int kShoulderStyleCount = 3;
// ButtonRow (int)
inline constexpr const char* kButtonRow[] = { "none", "functional", "decorative" };
inline constexpr int kButtonRowCount = 3;
// ExposedZip (int)
inline constexpr const char* kExposedZip[] = { "none", "centerFront", "centerBack" };
inline constexpr int kExposedZipCount = 3;
// BackDetail (int)
inline constexpr const char* kBackDetail[] = { "none", "ruffle", "cape", "flounce" };
inline constexpr int kBackDetailCount = 4;
// BardotStyle (int)
inline constexpr const char* kBardotStyle[] = { "none", "plain", "frill" };
inline constexpr int kBardotStyleCount = 3;
// CupSeam (int)
inline constexpr const char* kCupSeam[] = { "none", "horizontal", "bugra" };
inline constexpr int kCupSeamCount = 3;
// LocketTop (int)
inline constexpr const char* kLocketTop[] = { "none", "bugra" };
inline constexpr int kLocketTopCount = 2;
// Yoke (int)
inline constexpr const char* kYoke[] = { "none", "plain", "gathered" };
inline constexpr int kYokeCount = 3;
// BoxPleat (int)
inline constexpr const char* kBoxPleat[] = { "none", "centerInverted" };
inline constexpr int kBoxPleatCount = 2;

} // namespace vocab
} // namespace stitchu
